const messages = {
    // Login
    'Email': 'Mon email',
    'Login': 'Me connecter',
    'Password': 'Mon mot de passe',
    'Provided by your administrator': 'Fourni par votre administrateur',
    'Remember me': 'Se souvenir de moi',
    'no-identification-info': 'Si vous n\'avez pas vos identifiants, veuillez contacter votre administrateur',
    'bad-credentials': 'Vos identifiants sont incorrects. Veuillez réessayer svp.',
    'not-enough-rights': 'Vous n\'avez pas les droits suffisants pour vous connecter.Veuillez contacter votre administrateur',
    'user-not-found': 'Le collaborateur n\'a pas été trouvé.',
    'login-form-email-placeholder': 'Ex : KarineM@monentreprise.com',
    'login-form-password-placeholder': '8 caractères mini ...',

    // General
    'more-info': 'Plus d\'infos',
    'from': 'Du',
    'to': 'au',
    'real-time': 'en temps réel',
    'update': 'Modifier',
    'delete': 'Supprimer',
    'previous': 'Précédent',
    'next': 'Suivant',
    'send': 'Envoyer',
    'export-all': 'Exporter tout',
    'yes': 'Oui',
    'no': 'Non',
    'open': 'Ouvert',
    'fullname': 'Mon Nom et Prénom ',
    'job-position': 'Mon Métier',
    'assistance': 'Besoin d’aide ? Contactez jessie@whasq.com. Plus d\'info sur https://whasq.com.',
    'download-attachment': 'Télécharger la pièce jointe',
    'day': 'jour',
    'days': 'jours',
    'waiting': 'En réfléxion...',
    'loading': 'En cours de réflexion...',
    'read': 'Déjà lu',
    'unread': 'Non lu',

    // Menu
    // 'activity': 'Activité',
    // 'actives-users': 'Collaborateurs Actifs',
    // 'registered-users': 'Collaborateurs Inscrits',
    // 'whasqs-answers': 'Whasqs & Réponses',
    // 'skills': 'Savoirs',
    // 'time-savings': 'Gain de temps',
    // 'whasqers': 'Animation Whasqers',
    // 'podium': 'Podium',
    // 'search': 'Recherche',
    // 'manage': 'Gestion de la plateforme',
    // 'skills-categories': 'Savoirs & Catégories',
    // 'whasqs': 'Whasqs',
    // 'whasqs-reports': 'Whasqs signalés',
    // 'answers': 'Réponses',
    // // 'answers-reports': 'Réponses signalées',
    // 'users': 'Collaborateurs',
    // 'admin': 'Administration',
    // 'targets': 'Objectifs & Gamification',
    // 'notifications': 'Notifications',
    // 'learning': 'Formation',
    // 'training-centers': 'Organismes de formation',
    // 'trainings': 'Sessions de formations',
    // 'training-references': 'Formations',
    // 'training-reporting': 'Reporting de formation',
    // 'interns': 'Stagiaires',
    // 'training-center-reporting': 'Reporting d\'organisme de formation',

    // NewMenu
    'dashboard': 'Mon dashboard',
    'my-kpis': 'Mes chiffres clés',
    'skills-kpis': 'Infos Skills ',
    'time-savings-kpis': 'Gain de temps ?',
    'training-lab': 'Lab\'Formation',
    'my-users': 'Mes collaborateurs',
    'skills-management': 'Base de données des savoirs',
    'my-training-centers': 'Mes Organismes de Formations',
    'training-center-reporting': 'Chiffres clés de l\'organisme de formation',
    'my-training-references': 'Mon catalogue formations',
    'training-reference-reporting': 'Chiffres clés de l\'organisme de formation',
    'my-trainings': 'Mes sessions de formation',
    'training-reporting': 'Chiffres clés de la formation',
    'training-evaluation': 'Evaluation de la formation',
    'my-interns': 'Mes stagiaires',
    'my-community': 'Ma communauté',
    'active-users-kpis': 'Whasqers actifs',
    'ranking': 'Podium',
    'search': 'Recherche de Skills',
    'platform-activity': 'Flux de Whasqs',
    'whasqs': 'Les Whasqs',
    'answers': 'Les Réponses',

    // Activity
    'eve-computed-kpi': 'Cet indicateur est calculé à J-1',
    'no-data-for-selected-period': 'Aucune donnée disponible pour la période sélectionnée',
    'no-data-available': 'Aucune donnée disponible',

    // ActivityActiveUsers
    'actives-title': 'Collaborateurs/trices Actifs/ves',
    'actives-kpi-title': 'Actifs',
    'actives-kpi-help-title': 'Actifs',
    'actives-kpi-help-message': 'Cet indicateur représente le nombre de personnes qui se sont connecté au moins une fois au cours du mois de "{month}".',
    'actives-dda-kpi-title': 'Actifs depuis le début',
    'actives-dda-kpi-help-title': 'Actifs depuis le début',
    'actives-dda-kpi-help-message': 'Cet indicateur représente le nombre de personnes qui se sont connecté au moins 1 fois depuis le lancement de l\'application.',
    'actives-target-kpi-title': 'Actifs/Objectifs du trimestre',
    'actives-target-kpi-help-title': 'Actifs/Objectifs du trimestre',
    'actives-target-kpi-help-message': 'Cet indicateur représente le % entre le nombre de collaborateurs qui se sont connecté au moins une fois au cours du mois de "{month}" par rapport à l\'objectif défini par l\'administrateur (voir onglet administration).',
    'actives-evolution-title': 'Evolution des actifs',
    'actives-evolution-help-title': 'Evolution des actifs',
    'actives-evolution-help-message': 'Cet indicateur représente le nombre de collaborateurs actifs.',
    'actives-dda-evolution-title': 'Evolution cumulée des actifs  depuis le début',
    'actives-dda-evolution-period-selector' : "Filtrer par date", 
    'actives-dda-evolution-help-title': 'Evolution des actifs depuis le début',
    'actives-dda-evolution-help-message': 'Cet indicateur représente le nombre cumulé de personnes  qui se sont connecté au moins une fois par jour  depuis le lancement de l\'application.',
    'actives-notregistered-evolution-title': 'Evolution des actifs - inscription',
    'actives-notregistered-evolution-help-title': 'Evolution des actifs - inscription',
    'actives-notregistered-evolution-help-message': 'Cet indicateur représente le nombre de personnes actives Moins les collaborateurs inscrits.',

    // ActivityRegisteredUsers
    'registered-title': 'Collaborateurs Inscrits - {month}',
    'registered-kpi-title': 'Inscrits',
    'registered-kpi-help-title': 'Inscrits',
    'registered-kpi-help-message': 'Cet indicateur représente le nombre de collaborateurs qui se sont inscrits au mois de "{month}".',
    'registered-inactives-kpi-title': 'Pourcentage d\'inscrits non actifs',
    'registered-inactives-kpi-help-title': 'Pourcentage d\'inscrits non actifs',
    'registered-inactives-kpi-help-message': 'Cet indicateur représente le rapport entre le nombre de collaborateurs qui se sont inscrits au mois de "{month}" sans s\'être connectés par rapport au nombre de collaborateurs total inscrits dans le mois.',
    'registered-inactives-evolution-title': 'Evolution des inscriptions',
    'registered-inactives-evolution-help-title': 'Evolution des inscriptions',
    'registered-inactives-evolution-help-message': 'Cet indicateur représente le nombre de collaborateurs inscrits.',

    // ActivityWhasqs
    'whasqs-answers-title': 'Whasqs & Réponses - {month}',
    'whasqs-answers-kpi-title': 'Nombre total de Whasqs et de réponses ce mois-ci',
    'whasqs-answers-kpi-help-title': 'Nombre total de Whasqs et de réponses ce mois-ci',
    'whasqs-answers-kpi-help-message': 'Cet indicateur représente le nombre de whasqs et de réponses postés au mois de "{month}".',
    'whasqs-by-whasqer-kpi-title': 'Nombre de Whasqs / Whasqer actif ce mois-ci',
    'whasqs-by-whasqer-kpi-help-title': 'Nombre de Whasqs / Whasqer actif',
    'whasqs-by-whasqer-kpi-help-message': 'Cet indicateur représente le nombre de whasqs postés au mois de "{month}" par whasqer actif.',
    'answers-kpi-title': 'Nombre de réponses ce mois-ci',
    'answers-kpi-help-title': 'Nombre de réponses',
    'answers-kpi-help-message': 'Cet indicateur représente le nombre de réponses postées au mois de "{month}".',
    'answers-by-creator-kpi-title': 'Nombre de réponses / Whasqer actif ce mois-ci',
    'answers-by-creator-kpi-help-title': 'Nombre de réponses / Whasqer actif',
    'answers-by-creator-kpi-help-message': 'Cet indicateur représente le nombre de réponses postées au mois de "{month}" par whasqer actif.',
    'whasqs-with-contribution-kpi-title': 'Pourcentage de Whasqs avec réponse ce mois-ci',
    'whasqs-with-contribution-kpi-help-title': 'Pourcentage de Whasqs ayant eu au moins une réponse',
    'whasqs-with-contribution-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont reçu au moins une réponse au mois de "{month}".',
    'whasqs-with-contribution-dda-kpi-title': 'Pourcentage de Whasqs avec réponse depuis le début',
    'whasqs-with-contribution-dda-kpi-help-title': 'Pourcentage de Whasqs avec réponse depuis le début',
    'whasqs-with-contribution-dda-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont reçu au moins 1 réponse depuis le lancement de l\'application.',
    'whasqs-resolved-part-kpi-title': 'Pourcentage de Whasqs résolus ce mois-ci',
    'whasqs-resolved-part-kpi-help-title': 'Pourcentage de Whasqs résolus',
    'whasqs-resolved-part-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont été résolus au mois de "{month}".',
    'whasqs-resolved-part-dda-kpi-title': 'Pourcentage de Whasqs résolus depuis le début',
    'whasqs-resolved-part-dda-kpi-help-title': 'Pourcentage de Whasqs résolus depuis le début',
    'whasqs-resolved-part-dda-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont été résolus depuis le lancement de l\'application.',
    'whasqs-evolution-title': 'Suivi du nombre de whasqs par jour',
    'whasqs-evolution-help-title': 'Suivi du nombre de whasqs par  jour',
    'whasqs-evolution-help-message': 'Cet indicateur représente le nombre de whasqs par jour.',
    'answers-evolution-title': 'Suivi du nombre de réponses par jour',
    'answers-evolution-help-title': 'Suivi du nombre de réponses',
    'answers-evolution-help-message': 'Cet indicateur représente le nombre de réponses par jour.',

    // ActivitySkills
    'skills-title': 'Skills',
    'skills-dda-kpi-title': 'Nombre total de Skills dans votre organisation ',
    'skills-dda-kpi-help-title': 'Nombre total de Skills dans votre organisation',
    'skills-dda-kpi-help-message': 'Cet indicateur représente le nombre total de Skills présents dans le profil de vos collborateurs , depuis le lancement de l\'application.',
    'skills-part-kpi-title': '% de Skills uniques identifiés',
    'skills-part-kpi-help-title': '% de Skills uniques identifiés',
    'skills-part-kpi-help-message': 'Cet indicateur représente le % de Skills uniques présents dans les profils des whasqers par rapport au nombre de savoirs existants depuis le lancement de l\'application.',
    'skills-evolution-title': 'Suivi du nombre de Skills identifiés dans les whasqs chaque jour',
    'skills-evolution-help-title': 'Suivi du nombre de Skills identifiés dans les whasqs chaque jour',
    'skills-evolution-help-message': 'Cet indicateur représente le nombre de Skills identifiés dans les whasqs chaquejour.',
    'most-used-cats-whasqs-kpi-title': 'Thèmes les plus utilisés dans les whasqs',
    'most-used-cats-whasqs-kpi-help-title': 'Thèmes les plus utilisés dans les whasqs',
    'most-used-cats-whasqs-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 thèmes regroupant les Skills les plus utilisés dans les whasqs..',
    'most-used-cats-whasqs-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où les skills du thème en question sont utilisés.',
    'most-used-skills-whasqs-kpi-title': 'Skills les plus utilisés dans les whasqs',
    'most-used-skills-whasqs-kpi-help-title': 'Skills les plus utilisés dans les whasqs',
    'most-used-skills-whasqs-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 skills les plus utilisés dans les Whasqs .',
    'most-used-skills-whasqs-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où un Skill est utilisé dans un Whasq.',
    'most-used-whasqers-kpi-title': 'Skills les plus présents dans les profils',
    'most-used-whasqers-kpi-help-title': 'Skills les plus présents dans les profils',
    'most-used-whasqers-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 skills les plus présents dans les profils de vos collaborateurs/trices.'
    'most-used-whasqers-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où le skill est présent.',
    'less-used-whasqers-kpi-title': 'Skills les moins utilisés dans les profils',
    'less-used-whasqers-kpi-help-title': 'Skills les moins utilisés dans les profils',
    'less-used-whasqers-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 Skills les moins utilisés dans les profils de vos collaborateurs/trices..',
    'less-used-whasqers-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où le Skill a été utilisé dans le profil d\'un whasqer.',
    'activity-skills-top-five': 'TOP 5 !',

    // TimeSavings
    'time-savings-title': 'Gain de temps - {month}',
    'minutes-earned-kpi-title': 'Minutes gagnées ce mois',
    'minutes-earned-kpi-help-title': 'Minutes gagnées ce mois',
    'minutes-earned-kpi-help-message': 'Cet indicateur représente le nombre de minutes gagnées  grâce à l\'entraide collaborative au cours du mois de "{month}".',
    'minutes-earned-dda-kpi-title': 'Minutes gagnées depuis le début',
    'minutes-earned-dda-kpi-help-title': 'Minutes gagnées depuis le début',
    'minutes-earned-dda-kpi-help-message': 'Cet indicateur représente le nombre de minutes gagnées depuis le début du lancement de l\'application.',
    'minutes-earned-month-kpi-title': 'Minutes gagnées du mois',

    // Podium
    'podium-title': 'PODIUM',
    'whasqers-of-month': 'Whasqers du mois de',
    'no-podium-for-selected-month': 'Aucun podium n\'est disponible pour le mois sélectionné',

    // Card-user
    'answers-label': 'REPONSES',
    'points-label': 'Points',
    'solutions-label': 'Solutions',
    'see-profile': 'Voir le profil',

    // Search
    'search-title': 'Recherche',
    'search-by-name-placeholder': 'Recherche par nom, prenom ou e-mail...',
    'no-result-select-criteria': 'Pas de résultat. Veuillez saisir au moins un critère.',
    'search-export': 'Exporter les données',

    // CategoriesSearchBlock
    'dynamic-search-title': 'Recherche dynamique',
    'categories-search-block-selected-filters': '{count} fitre(s) sélectionné(s)',

    // SkillsCategories
    'skills-categories-title': 'Gestion des savoirs',
    'update-cat-for-lang': 'Modification du thème pour la langue {lang}',
    'update-skill-for-cat-and-lang-fr': 'Modification du savoir pour le thème "{cat}" et la langue FR',
    'add-cat-for-lang-fr': 'Ajout du thème pour la langue FR',
    'add-skill-for-cat-and-lang-fr': 'Ajout du savoir pour le thème "{cat}" et la langue FR',
    'skills-categories-remove-cat-confirm': 'Etes-vous sûr de vouloir supprimer ce thème ?',
    'skills-categories-remove-skill-confirm': 'Etes-vous sûr de vouloir supprimer ce savoir ?',
    'choose-lang': 'Choisir la langue',
    'add-lang': 'Ajouter une langue',
    'add-cat': 'Ajouter un thème',
    'skills-unavailable': 'Aucun thème et savoir créé pour le moment.',
    'skills-categories-add': 'Ajouter',
    'skills-categories-cat-added': 'Le thème "{catLabel}" a bien été ajouté.',
    'skills-categories-error-adding-cat': 'Une erreur s\'est produite lors de l\'ajout du thème "{catLabel}".',
    'skills-categories-cat-updated': 'Le thème a bien été modifié en "{catLabel}"',
    'skills-categories-error-updating-cat': 'Une erreur s\'est produite lors de la modification du thème.',
    'skills-categories-skill-created': 'Le savoir "{skillLabel}" a bien été ajouté.',
    'skills-categories-skill-error-creating-skill': 'Une erreur s\'est produite lors de l\'ajout du savoir "{skillLabel}".',
    'skills-categories-skill-updated': 'Le savoir a bien été modifié en "{skillLabel}"',
    'skills-categories-skill-error-updating-skill': 'Une erreur s\'est produite lors de la modification du savoir.',
    'skills-categories-lang-added': 'La langue a bien été ajoutée.',
    'skills-categories-error-adding-lang': 'Une erreur s\'est produite lors de l\'ajout de la langue',

    // InfoMessage
    'cat-deleted': 'La catégorie "{cat}" a été supprimée.',
    'error-deleting-cat': 'Un problème est survenu lors de la suppression de la catégorie "{cat}".',
    'skill-deleted': 'Le savoir "{skill}" a été supprimé.',
    'error-deleting-skill': 'Un problème est survenu lors de la suppression du savoir "{skill}".',

    // WhasqsList
    'whasqs-title': 'Whasqs',
    'block-whasq-confirm-message': 'Etes-vous sûr de vouloir bloquer ce whasq ?',
    'unblock-whasq-confirm-message': 'Etes-vous sûr de vouloir débloquer ce whasq ?',
    'ban-user-confirm-message': 'Etes-vous sûr de vouloir bannir ce collaborateur ?',
    'unban-user-confirm-message': 'Etes-vous sûr de vouloir retirer le bannissement de ce collaborateur ?',
    'remove-whasq-confirm-message': 'Etes-vous sûr de vouloir supprimer ce whasq ?',
    'add-whasq': 'Ajouter un Whasq',
    'whasqs-list': 'Liste de Whasqs',
    'whasqs-column-id': 'Id',
    'whasqs-column-creation': 'Création',
    'whasqs-column-update': 'Mise à jour',
    'whasqs-column-title': 'Sujet',
    'whasqs-column-status': 'Statut',
    'whasqs-column-urgent': 'Urgent',
    'whasqs-column-answers': 'Réponses',
    'whasqs-column-read': 'Lus',
    'whasqs-column-creator': 'Créateur',
    'whasqs-column-skills': 'Savoirs',
    'whasqs-column-actions': 'Actions',
    'whasqs-column-type': 'Type de whasq',
    'whasq-resolved-by': 'Résolu par',
    'whasq-resolved-at': 'le',
    'whasq-resolved': 'Résolu',
    'whasq-not-resolved': 'Non résolu',
    'whasq-archived': 'Archivé',
    'whasqs-action-save-updates': 'Sauvegarder les modifications',
    'whasqs-action-edit-whasq': 'Editer le whasq',
    'whasqs-action-unblock-whasq': 'Débloquer le whasq',
    'whasqs-action-block-whasq': 'Bloquer le whasq',
    'whasqs-action-see-whasq-channel': 'Voir la chaine de discussion du whasq',
    'whasqs-action-unban-user': 'Retirer le bannissement du collaborateur',
    'whasqs-action-ban-user': 'Bannir le collaborateur',
    'whasqs-action-remove-whasq': 'Suppression du whasq',
    'whasqs-notify-around': 'Notifier autour',
    'whasqs-language': 'Langue',
    'whasqs-list-reported-filter': 'Signalés',
    'whasqs-list-all-filter': 'Tous',
    'whasqs-list-training-filter': 'Type de whasqs',
    'whasqs-list-training': 'Whasqs de formation',
    'whasqs-list-not-training': 'Whasqs d\'entraide collaborative',
    'whasqs-list-add-btn': 'Ajouter',
    'whasqs-list-add-whasq-success': 'Le whasq a bien été créé',
    'whasqs-community': 'Entraide collaborative',
    'whasqs-training': 'Formation',
    'whasqs-user-locked': 'Bloqué',

    // WhasqChannelModal
    'whasq-channel-title': 'Chaîne de discussion',
    'usefull-answer': 'utile(s)',
    'champion-answer': 'CHAMPION(NE)',
    'whasq-channel-edit-whasq-title': 'Titre',
    'whasq-channel-edit-whasq-message': 'Message',
    'whasq-channel-edit-answer-message': 'Message',
    'whasq-channel-block-answer-confirm': 'Etes vous sûr de vouloir bloquer cette réponse ?',
    'whasq-channel-unblock-answer-confirm': 'Etes vous sûr de vouloir débloquer cette réponse ?',
    'whasq-channel-delete-answer-confirm': 'Etes vous sûr de vouloir supprimer cette réponse ?',
    'whasq-channel-modal-unblock-answer': 'Débloquer la réponse',
    'whasq-channel-modal-block-answer': 'Bloquer la réponse',
    'whasq-channel-modal-delete-answer': 'Supprimer la réponse',

    // AddWhasqModal
    'add-whasq-title': 'Ajout d\'un nouveau whasq',
    'add-whasq-item-title': 'Sujet',
    'add-whasq-item-message': 'Posez votre question',
    'add-whasq-item-import': 'Importer un fichier',
    'add-whasq-item-exchange': 'Qu\'offrez-vous en échange ?',
    'add-whasq-item-optionnal': 'Optionnel',
    'add-whasq-item-channel': 'Dans quelle langue ?',
    'add-whasq-item-skills': 'Savoirs concernés* (3 maximum)',
    'add-whasq-item-urgent': 'Urgent',
    'add-whasq-item-send-everyone': 'Envoyer à tout le monde',
    'add-whasq-skill-required': 'Il est obligatoire de renseigner au moins un savoir.',
    'add-whasq-title-required': 'Il est obligatoire de renseigner le sujet.',
    'add-whasq-message-required': 'Il est obligatoire d\'ajouter soit une question textuelle soit un fichier.',
    'add-whasq-modal-drop-file': 'Déposez votre fichier',
    'add-whasq-modal-file-type': 'Fichier de type image, audio, vidéo ou Microsoft Office',
    'add-whasq-modal-file-size': 'Taille maximale autorisée 1mo',
    'add-whasq-modal-error-importing-file': 'Une erreur s\'est produite lors du l\'import du fichier',
    'add-whasq-modal-import-file': 'Importer',
    'add-whasq-modal-media-attachment-no-preview': 'Pas de prévisualisation disponible',
    'add-whasq-modal-change-attachment': 'Changer de média',
    'add-whasq-modal-add': 'Ajouter',

    // Answers
    'answers-title': 'Réponses',
    'answers-unblock-answer-confirm-message': 'Etes-vous sûr de vouloir débloquer cette réponse ?',
    'answers-block-answer-confirm-message': 'Etes-vous sûr de vouloir bloquer cette réponse ?',
    'answers-unban-user-confirm-message': 'Etes-vous sûr de vouloir retirer le bannissement de ce collaborateur ?',
    'answers-ban-user-confirm-message': 'Etes-vous sûr de vouloir bannir ce collaborateur ?',
    'answers-remove-answer-confirm-message': 'Etes-vous sûr de vouloir supprimer cette réponse ?',
    'answers-list': 'Liste des réponses',
    'answers-column-id': 'Id',
    'answers-column-creation': 'Date de création',
    'answers-column-last-update': 'Dernière mise à jour',
    'answers-column-message': 'Message',
    'answers-column-usefull-count': 'Nb Utiles',
    'answers-column-champion': 'Champion ?',
    'answers-column-creator': 'Créateur',
    'answers-column-reported-by': 'Signalé par',
    'answers-column-actions': 'Actions',
    'answers-action-save-updates': 'Sauvegarder les modifications',
    'answers-action-edit-answer': 'Editer la réponse',
    'answers-action-block-answer': 'Bloquer la réponse',
    'answers-action-unblock-answer': 'Débloquer la réponse',
    'answers-action-see-whasq-channel': 'Voir la chaine de discussion du whasq',
    'answers-action-unban-user': 'Retirer le bannissement du collaborateur',
    'answers-action-ban-user': 'Bannir le collaborateur',
    'answers-action-remove-answer': 'Suppression de la réponse',
    'answers-reported-filter': 'Signalés',
    'answers-all-filter': 'Tous',

    // Users
    'users-title': 'Mes collaborateurs',
    'helper-filter-roles-title': 'Filtrer les collaborateurs selon le rôle', 
    'helper-filter-roles-message': 'Applique le filtre sur le rôle choisi', 
    'helper-user-status-title': 'Filtrer les collaborateurs selon leur status', 
    'helper-user-status-message': 'Applique le filtre sur le status choisi', 
    'users-ban-confirm-message': 'Etes-vous sûr de vouloir bannir ce collaborateur ?',
    'users-unban-confirm-message': 'Etes-vous sûr de vouloir retirer le bannissement de ce collaborateur ?',
    'users-archive-confirm-message': 'Etes-vous sur de vouloir archiver ce collaborateur ?',
    'users-add': 'Ajouter',
    'users-import-csv': 'Importer CSV',
    'users-list': 'Liste de Whasqers',
    'users-column-id': 'Id',
    'users-column-register-date': 'Date d\'inscription',
    'users-column-last-connection': 'Dernière connexion',
    'users-column-avatar': 'Avatar',
    'users-column-fullname': 'Nom',
    'users-column-title': 'Métier',
    'users-column-email': 'Email',
    'users-column-actions': 'Actions',
    'users-column-role': 'Rôle',
    'users-column-manager': 'Manager',
    'users-column-status': 'Statut',
    'users-action-see-profile': 'Voir le profil',
    'users-action-unban-user': 'Retirer le bannissement du collaborateur',
    'users-action-ban-user': 'Bannir le collaborateur',
    'users-action-archive-user': 'Archiver un collaborateur',
    'users-import-starting': 'L\'import des collaborateurs a bien débuté',
    'users-action-consider-user-admin': 'Considérer ce collaborateur comme étant admin',
    'users-action-stop-consider-user-admin': 'Ne plus considérer ce collaborateur comme étant admin',
    'users-confirm-consider-admin': 'Etes-vous sûr de vouloir considérer ce collaborateur comme étant admin ?',
    'users-confirm-dont-consider-admin': 'Etes-vous sûr de ne plus vouloir considérer ce collaborateur comme étant admin ?',
    'users-action-consider-user-admin-success': 'Le collaborateur d\'id {userId} est maintenant administrateur.',
    'users-action-stop-consider-user-admin-success': 'Le collaborateur d\'id {userId} n\'est maintenant plus administrateur.',
    'users-action-switch-role': 'Changer le rôle de ce collaborateur',
    'users-column-geolocated': 'Géolocalisé',
    'error-file-format': 'Le format du fichier n\'est pas correct',
    'users-roles-filter': 'Rôles',
    'users-roles-filter-all': 'TOUS',
    'users-roles-filter-user': 'COLLABORATEUR',
    'users-roles-filter-admin': 'ADMINISTRATEUR',
    'users-roles-filter-trainer': 'FORMATEUR',
    'users-actives-filter': 'Collaborateur actifs',
    'users-actives-filter-all': 'TOUS',
    'users-actives-filter-actives': 'ACTIFS',
    'users-actives-filter-deleted': 'ARCHIVES',
    'users-sessions-count': 'Nombre de sessions de formation',
    'users-acquired-skills': 'Nombre total de savoirs',
    'users-training-skills': 'Nombre de savoirs de formation',
    'users-role-TRAINEE': 'Stagiaire',
    'users-role-TRAINER_INT': 'Formateur interne',
    'users-role-TRAINER_EXT': 'Formateur externe',
    'users-role-CONTACT_TC': 'Contact O.F.',
    'users-role-ADMIN': 'DRH',
    'users-role-SUPER_ADMIN': 'Super Administrateur',
    'users-role-USER': 'Utilisateur',
    'users-user-created': 'Le collaborateur a bien été ajouté',
    'users-imported': 'Les collaborateurs ont bien été importés',
    'error-importing-users': 'Une erreur s\'est produite lors de l\'import des collaborateurs.',

    // ImportUsersModal
    'users-import-title': 'Import de collaborateurs',
    'import-users-file-limit': 'Seuls les fichiers CSV d\'une taille inférieure à 1Mo sont acceptés',
    'import-users-error': 'Une erreur est survenue lors de l\'import. Veuillez réessayer.',
    'import-users-btn': 'Importer les collaborateurs',
    'import-users-expected-format': 'Format attendu',
    'import-users-fullname': 'Nom complet',
    'import-users-email': 'Email',
    'import-users-job-position': 'Poste',
    'import-users-phone': 'Téléphone',
    'import-users-download-exemple': 'Télécharger l\'exemple',
    'import-users-instructions-part-1': 'Complétez l\'exemple téléchargé et sauvegardez le en format csv (valeurs séparées par des point-virgules)',
    'import-users-instructions-part-2': '(4 colonnes SEULEMENT dans l\'ordre DEFINI)',
    'import-users-err': 'Une erreur s\'est produite lors de l\'importation des collaborateurs',

    // Targets
    'targets-title': 'Objectifs & Gamification',
    'targets-update-message': 'L\'objectif "{target}" a bien été mis à jour',
    'targets-geoloc-perimeter-updated': 'Le périmètre de géolocalisation a bien été mis à jour',
    'targets-points-atribution-updated': 'L\'attribution de points a bien été mise à jour',
    'targets-target': 'Objectifs',
    'targets-trimester': '3 mois',
    'targets-bimester': '6 mois',
    'targets-year': '12 mois',
    'targets-active-users': 'collaborateurs actifs',
    'targets-geoloc-perimeter': 'Périmètre de géolocalisation',
    'targets-perimeter': 'Périmètre',
    'targets-gamification': 'Gamification',
    'targets-approved-answer': 'Réponse approuvée',
    'targets-usefull-answer': 'Réponse utile',
    'targets-recommended-skill': 'Savoir recommandé',
    'targets-points': 'points',

    // Header
    'header-profile': 'Profil',
    'header-logout': 'Se déconnecter',
    'french': 'Français',
    'english': 'Anglais',
    'spanish': 'Espagnol',
    'italian': 'Italien',
    'russian': 'Russe',
    'portuguese': 'Portugais',
    'header-choose-lang': 'Choisir la langue',
    'header-french': 'Français',
    'header-spanish': 'Español',
    'header-english': 'English',
    'header-italian': 'Italiano',
    'header-portuguese': 'Português',
    'header-russian': 'русский',

    // Sidebar
    'sidebar-navigation': 'Navigation',
    'sidebar-dashboard': 'Mon dashboard',
    'sidebar-my-kpis': 'Mes chiffres clés',
    'sidebar-my-skills-kpis': 'Mes chiffres clés savoirs',
    'sidebar-time-savings-kpis': 'KPI gain de temps',
    'sidebar-training-lab': 'Lab\' Formation',
    'sidebar-my-users': 'Mes collaborateurs',
    'sidebar-skills-management': 'Gestion des savoirs',
    'sidebar-my-training-centers': 'Mes O.F.',
    'sidebar-my-training-references': 'Mes formations',
    'sidebar-my-trainings': 'Mes sessions',
    'sidebar-my-interns': 'Mes stagiaires',
    'sidebar-my-community': 'Ma communauté',
    'sidebar-search': 'Recherche',
    'sidebar-active-users': 'Whasqers actifs',
    'sidebar-whasqs-answers': 'Whasqs et réponses',
    'sidebar-podium': 'Podium',
    'sidebar-platform-activity': 'Activité plateforme',
    'sidebar-whasqs': 'Les Whasqs',
    'sidebar-answers': 'Les Réponses',

    // Profile
    'profile': 'Profil',
    'profile-title': 'Profil collaborateur',
    'profile-ranking-position': 'Position de l\'utilisateur dans le classement',
    'profile-whasqs-sent': 'Nombre de whasqs envoyés',
    'profile-answers-sent': 'Nombre de réponses envoyées',
    'profile-my-training-reporting': 'Mon suivi formation',
    'profile-his-training-reporting': 'Son suivi formation',
    'profile-my-skills-title': 'Mes savoirs',
    'profile-his-skills-title': 'Ses savoirs',
    'profile-my-channels-title': 'Mes langues',
    'profile-his-channels-title': 'Ses langues',
    'profile-skills-add': 'Ajouter',
    'profile-trainings-count': 'Nombre de formations suivies',
    'profile-success-rate': 'Taux de réussite global',
    'profile-skills-count': 'Nombre de savoirs',
    'profile-training-whasqs': 'Whasqs formation en attente',
    'profile-channels-add': 'Ajouter',
    'profile-edit-label': 'Modifier',
    'profile-save-label': 'Sauvegarder',
    'profile-image-size-limit': 'Seuls les fichiers images d\'une taille inférieure à 1Mo sont acceptés.',
    'profile-image-square-required': 'L\'image doit avoir un format carré.',
    'import-profile-image': 'Importer l\'image',
    'pick-profile-avatar': 'Choisir un avatar',
    'profile-delete-channel-confirm': 'Etes-vous sûr de vouloir supprimer la langue "{channelName}" ?',
    'profile-delete-last-channel-impossible': 'Désolé, vous devez avoir au moins une langue dans votre profil.',
    'profile-channel-removed': 'La langue {channelName} a bien été supprimée.',
    'profile-delete-skill-confirm': 'Etes-vous sûr de vouloir supprimer le savoir "{skillName}" ?',
    'profile-skill-removed': 'Le savoir "{skillName}" a bien été supprimé.',
    'profile-error-removing-skill': 'Une erreur s\'est produite lors de la suppression du savoir "{skillName}".',
    'profile-error-updating-gdpr': 'Une erreur s\'est produite lors de la modification de la visibilité RGPD.',
    'profile-error-updating-user': 'Une erreur s\'est produite lors de la modification de l\'utilisateur.',
    'profile-user-updated': 'L\'utilisateur a bien été modifié.',
    'profile-error-getting-available-skills': 'Une erreur s\'est produite lors de la récupération des savoirs disponibles.',
    'profile-skill-added': 'Le talent a bien été ajouté.',
    'profile-error-adding-skill': 'Une erreur s\'est produite lors de l\'ajout du savoir',
    'profile-error-getting-available-channels': 'Une erreur s\'est produite lors de la récupération des langues disponibles',
    'profile-channel-added': 'La langue {channelName} a bien été ajoutée.',
    'profile-error-adding-channel': 'Une erreur s\'est produite lors de l\'ajout de la langue',
    'profile-training-trace': 'Mon suivi formation',
    'profile-collaborative-trace': 'Mon suivi collaboratif',
    'profile-whasqs-count': 'Nombre de whasqs envoyés',
    'profile-answers-count': 'Nombre de réponses données',
    'profile-likes-count': 'Nombre de likes reçus',
    'profile-solutions-count': 'Nombre de solutions trouvées',
    'profile-trainings-name-col': 'Formation',
    'profile-trainings-start-col': 'Début',
    'profile-trainings-remaining-days-col': 'Jours restants',
    'profile-trainings-skills-col': 'Savoirs acquis',
    'profile-participation-rate': 'Taux de participation',
    'profile-mean-success-rate': 'Taux de réussite moyen',
    'profile-evolution-rate': 'Evolution Q1/Q2',
    'profile-training-planned': '(à venir)',
    'profile-email-not-available': 'L\'email n\'est pas renseigné ou n\'est pas disponible',
    'profile-phone-not-available': 'Le numéro de téléphone n\'est pas renseigné ou n\'est pas disponible',
    'profile-job-position-not-available': 'Le poste n\'est pas renseigné ou n\'est pas disponible',
    'profile-place-not-available': 'Le lieu de travail n\'est pas renseigné ou n\'est pas disponible',
    'profile-fixed-line-phone-not-available': 'Le numéro de téléphone fixe n\'est pas renseigné ou n\'est pas disponible',
    'profile-manager-not-available': 'Le manager pas renseigné ou n\'est pas disponible',
    'profile-manager-label': 'Manager :',
    'profile-add-manager': 'Ajouter un manager',
    'profile-set-manager-succeeded': 'Le manager {fullname} a bien été ajouté.',
    'profile-set-manager-failed': 'Une erreur s\'est produite lors de l\'ajout du manager',
    'profile-no-skill': 'Aucun savoir n\'est renseigné',
    'profile-no-channel': 'Aucune langue n\'est renseignée',
    'profile-stat-consult': 'Consulter',

    // AddUserSkillModal
    'add-user-skill-title': 'Ajout d\'un savoir',
    'add-user-skill-subtitle': 'Vous avez sûrement d\'autres savoirs, vous pouvez les ajouter !',
    'add-user-skill-suggest': 'Il manque un savoir ?',

    // AddUserChannelModal
    'add-user-channel-title': 'Ajout d\'une langue',
    'add-user-channel-subtitle': 'Sélectionnez les langues que vous parlez',

    // SuperAdminStores
    'store-selection': 'Choix du store',
    'store-choice-validation': 'Valider le choix du store',

    // StoreLogoUpload
    'choose-company-logo': 'Choisir le logo de votre société',
    'drop-file-here-or-click': 'Déposez votre fichier ici ou cliquez pour sélectionner le fichier à importer.',
    'company-logo-size-limit': 'Seuls les fichiers images d\'une taille inférieure à 1Mo sont acceptés.',
    'company-logo-square-required': 'L\'image doit avoir un format carré.',
    'error-importing-company-logo': 'Une erreur est survenue lors de l\'import. Veuillez réessayer.',
    'import-company-logo': 'Importer le logo',

    // Notifications
    'notifications-title': 'Notifications',
    'notifications-list': 'Liste de notifications',
    'notifications-column-id': 'Id',
    'notifications-column-type': 'Type',
    'notifications-column-data': 'Données',
    'notifications-column-owner': 'Propriétaire',
    'notifications-column-shared': 'Partagé ?',
    'notifications-column-creation': 'Date de création',
    'notifications-column-message': 'Message',
    'notifications-no-data': 'Vous n\'avez actuellement aucune notification',

    // TrainingCenters
    'training-centers-id-col': 'Id',
    'training-centers-title': 'Mes organismes de formation',
    'training-centers-add-btn': 'Ajouter',
    'training-centers-not-defined': 'Aucun organisme de formation n\'est défini à ce jour. Veuillez en ajouter.',
    'training-centers-archive-confirm': 'Etes-vous sûr de vouloir archiver cet organisme de formation ?',
    'training-centers-name-col': 'Nom',
    'training-centers-url-col': 'Url',
    'training-centers-training-ref-count-col': 'Nb de formations', 
    'training-centers-training-count-col': 'Nb de sessions', 
    'training-centers-respondents-count-col': 'Nb de stagiaires',
    'training-centers-date-col': 'Date de création',
    'training-centers-success-rate-col': 'Taux de réussite',
    'training-centers-actions-col': 'Actions',
    'helper-training-tutorial-title': 'Tutoriel d\'utilisation',
    'helper-training-tutorial-message': 'La vidéo est en cours de création.. En attendant vous pouvez nous écrire sur jessie@whasq.com si vous avez une question.',
    'training-center-action-show-trainings' : 'Accéder aux formations attachées',
    'training-center-action-no-trainings': 'Aucune formation créée pour cet organisme de formation',
    'training-centers-import-btn': 'Importer CSV',
    'training-centers-recommendation-rate-col': 'Taux de recommandation',
    'training-centers-acquired-skills-col': 'Nombre moyen de savoirs acquis',
    'training-centers-update': 'Modifier',
    'training-centers-reporting': 'Accèder au reporting',
    'training-centers-archive': 'Archiver l\'organisme de formation',

    // Trainings
    'trainings-id-col': 'Id', 
    'trainings-state-col': 'Statut', 
    'trainings-title': 'Mes sessions de formations',
    'trainings-add-btn': 'Ajouter',
    'trainings-import-btn': 'Importer CSV',
    'trainings-name-col': 'Nom',
    'trainings-level-col': 'Niveau',
    'trainings-training-center-col': 'Nom de l\'organisme',
    'trainings-start-col': 'Début',
    'trainings-end-col': 'Fin',
    'trainings-recommendation-rate-col': 'Taux de recommandation',
    'trainings-acquired-skills-col': 'Nb de savoirs acquis',
    'trainings-support-end-col': 'Fin support',
    'trainings-trainers-count-col': 'Nb de formateurs',
    'trainings-participants-count-col': 'Nb de stagiaires',
    'trainings-whasqs-count-col': 'Nb de whasqs',
    'trainings-remaining-days-col': 'Jours restants',
    'trainings-success-rate-col': 'Taux de réussite',
    'trainings-language-col': 'Langue',
    'trainings-respondents-count-col': 'Nb de répondants',
    'trainings-actions-col': 'Actions',
    'trainings-not-defined': 'Aucune session de formation n\'est définie à ce jour. Veuillez en ajouter.',
    'trainings-no-with-search': 'Aucune session de formation ne correspond à votre recherche. Veuillez en ajouter.',
    'trainings-archive-confirm': 'Etes-vous sûr de vouloir archiver cette session de formation ?',
    'trainings-action-plan': 'Planifier les réponses',
    'trainings-action-update': 'Modifier la session de formation',
    'trainings-action-duplicate': 'Dupliquer la session de formation',
    'trainings-action-reporting': 'Accèder au reporting de la session de formation',
    'trainings-action-evaluation': 'Accèder à l\'évaluation de la session de formation',
    'trainings-action-no-evaluation': 'Pas d\'évaluation pour le moment',
    'trainings-action-archive': 'Archiver la session de formation',
    'trainings-whasqs-count-insufficient': '⚠ Vous ne pouvez pas accèder à la planification des questions tant que vous n\'avez pas ajouté au moins 10 questions à la session de formation.',
    'trainings-confirm-duplicate': 'Etes-vous sûr de vouloir dupliquer cette session de formation ?',
    'trainings-training-center-filter': 'Filtrer par organisme de formation',
    'trainings-training-center-filter-all': 'TOUS',
    'trainings-training-reference-filter': 'Filtrer par formation',
    'trainings-training-reference-filter-all': 'TOUTES',

    // AddTrainingCenterModal
    'add-training-center-modal-title': 'Ajouter un organisme de formation',
    'add-training-center-modal-title-edit': 'Modification de l\'organisme de formation{br}"{name}"',
    'add-training-center-modal-desc-tab': 'Description',
    'add-training-center-modal-trainers-tab': 'Contact',
    'add-training-center-modal-name': 'Nom',
    'add-training-center-modal-url': 'Site web',
    'add-training-center-modal-validate': 'Ajouter',
    'add-training-center-modal-validate-update': 'Modifier',
    'add-training-center-modal-col-name': 'Nom',
    'add-training-center-modal-col-email': 'Email',
    'add-training-center-modal-col-job': 'Poste',
    'add-training-center-modal-col-actions': 'Actions',
    'add-training-center-modal-delete-trainer-confirm': 'Etes-vous sûr de vouloir retirer ce formateur de cet organisme de formation ?',
    'add-training-center-modal-update-successful': '👍 L\'organisme de formation "{name}" a bien été mis à jour !',
    'add-training-center-modal-insert-successful': '👍 L\'organisme de formation "{name}" a bien été créé !',
    'add-training-center-modal-trainer-deleted': '👍 Le formateur d\'email "{email}" a bien été supprimé de cet organisme de formation.',
    'add-training-center-modal-trainer-added': '👍 Le formateur d\'email "{email}" a bien été ajouté à cet organisme de formation.',
    'add-training-center-modal-activation-link-trainer-sent': 'Un lien d\'activation vient d\'être envoyé au formateur concerné',
    'add-training-center-close-confirm': 'Etes-vous sûr de vouloir quitter sans enregistrer ?',

    // AddTrainerModal
    'add-trainer-modal-training-center-title': 'Ajouter un contact à l\'organisme de formation',
    'add-trainer-modal-training-title': 'Ajouter un formateur à la session de formation',
    'add-trainer-modal-participant-title': 'Ajouter un participant à la session de formation',
    'add-trainer-modal-trainer-email': 'Email du contact',
    'add-trainer-modal-participant-email': 'Email du participant',
    'add-trainer-modal-no-matched-trainer': 'Aucun formateur correspond à l\'email renseigné',
    'add-trainer-modal-validate': 'Validate',
    'add-trainer-modal-email-invalid': 'L\'adresse email n\'est pas valide',
    'add-trainer-modal-grant-user-confirm': 'Vous êtes sur le point de donner le rôle CONTACT OF à un collaborateur. Etes-vous sûr de vouloir continuer ?',
    'add-trainer-modal-at-least-three': 'Veuillez renseigner au moins 3 caractères pour lancer la recherche parmi les collaborateurs déjà inscrits.',
    'add-trainer-modal-external-trainer': 'Si le contact est extérieur à votre organisation, écrivez l\'email complet. Une invitation lui sera envoyée.',

    // AddTrainingModal
    'add-training-modal-title': 'Ajout d\'une session de formation',
    'add-training-modal-edit-title': 'Ajout d\'une session de formation',
    'add-training-modal-desc-tab': 'Description',
    'add-training-modal-trainers-tab': 'Formateurs',
    'add-training-modal-participants-tab': 'Participants',
    'add-training-modal-memory-quiz-tab': 'Quiz mémoriel',
    'add-training-modal-levels-tab': 'Niveaux de difficulté',
    'add-training-modal-training-reference': 'Formation',
    'add-training-modal-start': 'Début',
    'add-training-modal-end': 'Fin',
    'add-training-modal-pro-assessment-starts-at': 'Positionnement',
    'add-training-modal-pro-assessment-starts-at-placeholder': 'Cliquez ici...',
    'add-training-modal-end-support': 'Bilan',
    'add-training-modal-start-placeholder': 'Cliquez ici...',
    'add-training-modal-end-placeholder': 'Cliquez ici...',
    'add-training-modal-time': 'Heure',
    'add-training-modal-validate': 'Valider',
    'add-training-modal-trainers-name-col': 'Nom',
    'add-training-modal-trainers-email-col': 'Email',
    'add-training-modal-trainers-job-col': 'Poste',
    'add-training-modal-trainers-actions-col': 'Actions',
    'add-training-modal-add-trainer-btn': 'Ajouter un formateur',
    'add-training-modal-add-participant-btn': 'Ajouter un participant',
    'add-training-modal-import-participant-btn': 'Import CSV',
    'add-training-modal-participants-name-col': 'Nom',
    'add-training-modal-participants-email-col': 'Email',
    'add-training-modal-participants-job-col': 'Poste',
    'add-training-modal-participants-actions-col': 'Actions',
    'add-training-modal-add-question-btn': 'Ajouter',
    'add-training-modal-edit-question-planning-btn': 'Planning',
    'add-training-modal-quiz-question-number-col': 'N°', 
    'add-training-modal-quiz-index-col': 'Id',
    'add-training-modal-quiz-question-col': 'Thème de la question',
    'add-training-modal-quiz-type-col': 'Type',
    'add-training-modal-quiz-scheduled-col': 'Prévue le',
    'add-training-modal-quiz-level-col': 'Niveau',
    'add-training-modal-quiz-actions-col': 'Actions',
    'add-training-modal-delete-question-confirm': 'Etes-vous sûr de vouloir supprimer cette question ?',
    'add-training-modal-delete-participant-confirm': 'Etes-vous sûr de vouloir supprimer ce participant ?',
    'add-training-modal-delete-trainer-confirm': 'Etes-vous sûr de vouloir supprimer ce formateur ?',
    'add-training-modal-level-lvl-col': 'Niveau',
    'add-training-modal-level-label-col': 'Label',
    'add-training-modal-level-succes-threshold-col': 'Taux de réussite attendu',
    'add-training-modal-level-actions-col': 'Actions',
    'add-training-modal-remove-lvl-confirm': 'Etes-vous sûr de vouloir supprimer ce niveau ?',
    'add-training-modal-add-lvl-btn': 'Ajouter',
    'add-training-modal-add-question-no-level': 'Vous devez ajouter des niveaux avant de créer vos questions 😉',
    'add-training-modal-training-center': 'Organisme de formation',
    'add-training-modal-quiz': 'Quiz',
    'add-training-modal-bad-mode-configuration': 'Mauvaise configuration des options',
    'add-training-modal-has-preassessment': 'Positionnement',
    'add-training-modal-has-assessment': 'Formation',
    'add-training-modal-has-evaluation': 'Evalution',
    'add-training-modal-training-center-placeholder': 'Choisissez votre organisme de formation ! 😃',
    'add-training-modal-training-reference-placeholder': 'Choisissez votre formation ! 😃',
    'add-training-modal-missing-field': 'Le champs "{field}" est requis. Merci de le compléter pour pouvoir créer la session de formation 😉',
    'add-training-modal-invalid-field': 'Le champs "{field}" est invalide. Merci de le corriger pour pouvoir créer la session de formation 😉',
    'add-training-modal-insert-successfull': 'La session de formation a bien été créée ! 😃',
    'add-training-modal-error-insert': 'Une erreur s\'est produite lors de la création de la session de formation.',
    'add-training-modal-update-successfull': 'La session de formation a bien été mise à jour ! 😃',
    'add-training-modal-error-updating': 'Une erreur s\'est produite lors de la modification de la session de formation.',
    'add-training-modal-trainer-added': 'Le formateur a bien été ajouté à la session de formation ! 😃',
    'add-training-modal-trainer-invited': 'Le formateur a bien été invité pour cette session de formation ! 😃',
    'add-training-modal-trainer-deleted': 'Le formateur a bien été retiré de la session de formation ! 😃',
    'add-training-modal-participant-added': 'Le participant a bien été ajouté à la session de formation ! 😃',
    'add-training-modal-participant-invited': 'Le participant a bien été invité pour cette session de formation ! 😃',
    'add-training-modal-participant-deleted': 'Le participant a bien été retiré de la session de formation ! 😃',
    'add-training-modal-level-added': 'Le niveau {level} a bien été ajouté ! 😃',
    'add-training-modal-level-updated': 'Le niveau {level} a bien été modifié ! 😃',
    'add-training-modal-level-deleted': 'Le niveau {level} a bien été supprimé ! 😃',
    'add-training-modal-question-deleted': 'La question a bien été supprimée ! 😃',
    'add-training-modal-minimum-whasqs': 'Attention, vous devez ajouter au moins 10 questions à la session de formation',
    'add-training-modal-qcm': 'Choix multiple',
    'add-training-modal-qcu': 'Choix unique',
    'add-training-modal-planification-tab': 'Planification',
    'add-training-modal-update-impossible': 'La modification n\'est pas possible car le support de la session de formation a débuté.',
    'add-training-modal-pending': 'En attente...',
    'add-training-close-confirm': 'Etes-vous sûr de vouloir quitter sans enregistrer ?',
    'add-training-modal-insufficient-rights': 'Vous n\'êtes pas autorisé à réaliser cette action.',
    'add-training-modal-switch-whasq-position-success': 'La position des deux whasqs a bien été modifiée',
    'add-training-modal-action-duplicate': 'Dupliquer la question',
    'add-training-modal-action-update': 'Modifier la question',
    'add-training-modal-action-see': 'Voir la question',
    'add-training-modal-action-delete': 'Supprimer la question',
    'add-training-modal-previous-month': 'Mois précédent',
    'add-training-modal-next-month': 'Mois suivant',
    'add-training-modal-support-start': 'Début de support',
    'add-training-modal-support-end': 'Fin de support',

    // AddQuestionModal
    'add-question-modal-title': 'Ajout d\'une question au quiz',
    'add-question-modal-duplicate-title': 'Duplication d\'une question du quiz',
    'add-question-modal-edit-title': 'Edition d\'une question du quiz',
    'add-question-modal-type': 'Choix du questionnaire',
    'add-question-modal-options': 'Choix des réponses',
    'add-question-modal-qcm': 'Questionnaire à choix multiple',
    'add-question-modal-qcu': 'Questionnaire à choix unique',
    'add-question-modal-open': 'Question ouverte',
    'add-question-modal-add-option': 'Ajouter une réponse',
    'add-question-modal-whasq-title': 'Thème de la question',
    'add-question-modal-whasq-message': 'Posez votre question',
    'add-question-modal-save': 'Enregistrer la question',
    'add-question-modal-option-label-col': 'Réponse',
    'add-question-modal-option-solution-col': 'Solution',
    'add-question-modal-option-explanation-col': 'Si vous souhaitez ajouter une explication',
    'add-question-modal-option-order-col': 'Ordre',
    'add-question-modal-option-actions-col': 'Actions',
    'add-question-modal-explanations': 'Explications',
    'add-question-modal-level': 'Niveau',
    'add-question-modal-whasq-media': 'Media',
    'add-question-modal-import-drop-here': 'Déposez ici votre média.',
    'add-question-modal-import-size-limit': 'La taille maximale du fichier est 1Mo',
    'add-question-modal-error-importing-file': 'Une erreur s\'est produite lors de l\'import du fichier.',
    'add-question-modal-import-file-button': 'Importer le fichier',
    'add-question-modal-skills': 'Savoir (1 maximum)',
    'add-question-modal-skill': 'Savoir',
    'add-question-modal-skills-add': 'Ajouter',
    'add-question-modal-media-attachment-no-preview': 'Pas de prévisualisation possible',
    'add-question-modal-change-attachment': 'Changer de fichier',
    'add-question-modal-delete-option-confirm': 'Etes-vous sûr de vouloir supprimer cette réponse ?',
    'add-question-modal-missing-title': 'Le thème de la question est obligatoire',
    'add-question-modal-missing-message-or-media': 'Vous devez renseigner une question pour valider ce formulaire',
    'add-question-modal-missing-skill': 'Au moins un savoir est requis pour valider ce formulaire',
    'add-question-modal-missing-options': 'Au moins deux choix de réponses doivent être renseignées',
    'add-question-modal-missing-assert-options': 'Parmi les réponses, au moins une doit être une solution',
    'add-question-modal-qcu-bad-assert-options': 'Votre questionnaire est à choix unique, vous devez avoir une unique solution parmi les choix de réponses',
    'add-question-modal-options-all-assert-confirm': 'Tous les choix de réponses sont des solutions de la question. Etes-vous sûr de vouloir valider cela ?',
    'add-question-modal-close-confirm': 'Voulez-vous quitter sans enregistrer ?',
    'add-question-modal-switch-options-position-success': 'La position des deux réponses a bien été modifiée',
    'add-question-modal-action-edit': 'Modifier la question',
    'add-question-modal-action-delete': 'Supprimer la question',

    // AddTrainingSkillModal
    'add-training-skill-modal-title': 'Ajout de savoirs à la session de formation',
    'add-training-skill-modal-suggest': 'Un savoir est manquant ? Demandez l\'ajout',

    // EditPlanningModal
    'edit-planning-modal-title': 'Planification des questions',
    'edit-planning-modal-legend-title': 'Légende',
    'edit-planning-modal-legend-level': 'Niveau {level}',
    'edit-planning-modal-bad-date': 'Vous ne pouvez pas déplacer la planification de cette question à cette date. Veuillez la modifier. 😉',
    'edit-planning-modal-too-many-events': 'Vous ne pouvez pas planifier plus de 2 questions le même jour.',

    // AddLevelModal
    'add-level-modal-title': 'Ajout du niveau {level}',
    'add-level-modal-edit-title': 'Edition du niveau {level}',
    'add-lvl-modal-label': 'Titre du niveau', 
    'add-lvl-modal-success-treshold': 'Taux de réussite attendu (en %)',
    'add-lvl-modal-validate-btn': 'Valider',
    'add-level-modal-fields-required': 'Merci de compléter tous les champs pour pouvoir valider ce formulaire.',
    'add-lvl-modal-helper': 'Un niveau est un indication du niveau de difficulté qui sera attribué à vos questions.', // todo

    // PlanQuestionModal
    'plan-question-modal-title': 'Planifier une question le {date}',
    'plan-question-modal-move-question-title': 'Déplacer la question {question} au {date}',
    'plan-question-modal-move-question-title-unknown-date': 'Déplacer la question {question}',
    'plan-question-modal-plan-btn': 'Planifier',
    'plan-question-modal-move-btn': 'Déplacer',
    'plan-question-modal-question': 'Question #{id}',
    'plan-question-modal-question-level': 'niveau {level}',
    'plan-question-modal-choose-question': 'Quelle question souhaitez-vous planifier ?',
    'plan-question-modal-prior-warning-confirm': '⚠ Attention ⚠\r\nVous ne pouvez pas planifier une question de difficulté {level} après une ou plusieurs questions de niveau supérieur.',
    'plan-question-modal-later-warning-confirm': '⚠ Attention ⚠\r\nVous ne pouvez pas planifier une question de difficulté {level} avant une ou plusieurs questions de niveau inférieur.',
    'edit-planning-modal-all-questions-planned': 'Toutes les questions sont planifiées 😃',
    'plan-question-modal-date-placeholder': 'Date de report',
    'plan-question-modal-select-move-date': 'Nouvelle date de planification',
    'plan-question-modal-question-title': 'Titre',
    'plan-question-modal-question-message': 'Détails',
    'plan-question-modal-bad-date': 'Vous ne pouvez pas déplacer la planification de cette question à cette date. Veuillez la modifier. 😉',
    'plan-question-modal-update-question': 'Modifier la question',

    // AddQuestionSkillModal
    'add-question-skill-modal-title': 'Ajout d\'un savoir',
    'add-question-skill-modal-conditions': 'Vous pouvez ajouter jusqu\'à 3 savoirs sur cette question',

    // AddQuestionOptionModal
    'add-question-option-modal-title': 'Ajout d\'une réponse',
    'add-question-option-modal-title-update': 'Edition d\'une réponse',
    'add-question-option-modal-label': 'Réponse',
    'add-question-option-modal-assert': 'Solution',
    'add-question-option-modal-explanation': 'Explication',
    'add-question-option-modal-add': '+ Ajouter',
    'add-question-option-modal-update': 'Editer',
    'add-question-option-modal-solution-ever-defined': '(une réponse est déjà définie comme solution de la question)',
    'add-question-option-modal-error': 'Merci de renseigner la réponse pour pouvoir valider ce formulaire',

    // TrainingReporting
    'training-kpis-title': 'Chiffres clés',
    'training-kpis-updated-at': 'Mis à jour le {date} à {hours}h{minutes}',
    'training-reporting-no-data-title': 'Reporting : pas de donnée à ce jour',
    'training-reporting-participants-count-kpi-title': 'Nombre d\'inscriptions à la session',
    'training-reporting-participants-count-help-title': 'Nombre de stagiaires inscrits à la session de formation ayant validés ou non leurs comptes',
    'training-reporting-participants-count-help-message': 'Moyenne calculée sur cette session de formation (Somme des stagiaires ayant été inscrits à une session de formation)',
    'training-reporting-success-rate-pre-kpi-title': 'Taux de réussite (positionnenement)',
    'training-reporting-success-rate-pre-help-title': 'Pourcentage de bonnes réponses au questionnaire de positionnement',
    'training-reporting-success-rate-pre-help-message': 'Moyenne calculée sur cette  session de formation (nb bonnes réponses Q1 / nb questions répondues Q1) * 100',
    'training-reporting-success-rate-kpi-title': 'Taux de réussite (formation)',
    'training-reporting-success-rate-help-title': 'Pourcentage de bonnes réponses au questionnaire après formation',
    'training-reporting-success-rate-help-message': 'Moyenne calculée sur cette  session de formation (nb bonnes réponses Questionnaire formation / nb questions répondues Questionnaire formation) * 100',
    'training-reporting-commitment-rate-kpi-title': 'Taux d\'engagement',
    'training-reporting-commitment-rate-help-title': 'Pourcentage des stagiaires ayant répondu au minimum à un questionnaire',
    'training-reporting-commitment-rate-help-message': 'Moyenne calculée sur cette  session de formation (Nombre de stagiaires uniques répondants à au moins 1 questionnaire pré évaluation, satisfaction post formation par session / Nombre de stagiaires uniques inscrits à la session de formation)',
    'training-reporting-satisfaction-rate-kpi-title': 'Taux de satisfaction',
    'training-reporting-satisfaction-rate-help-title': 'Pourcentage des avis positifs des stagiaires suite à la formation',
    'training-reporting-satisfaction-rate-help-message': 'Moyenne calculée sur cette  session de formation (Nombre d\'avis positifs (3 et 4 étoiles sur la 1ère question) du questionnaire de satisfaction de la session formation / Nombre d\'avis du questionnaire de satisfaction de la session formation)',
    'training-reporting-attendance-rate-kpi-title': 'Taux de présence',
    'training-reporting-attendance-rate-help-title': 'Pourcentage des stagiaires présents lors des formations',
    'training-reporting-attendance-rate-help-message': 'Moyenne calculée sur cette session de formation (Nombre de stagiaires présents à J+1 / Nombre de stagiaires inscrits à J-1) * 100',
    'training-reporting-acquired-skills-participant-kpi-title': 'Moyenne des savoirs acquis',
    'training-reporting-acquired-skills-participant-help-title': 'Ce chiffre donne le nombre de savoirs acquis en moyenne par les stagiaires répondants',
    'training-reporting-acquired-skills-participant-help-message': 'Moyenne calculée sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Nombre de savoirs acquis / Nombre de stagiaires ayant répondu à 100% au Questionnaire formation) * 100',
    'training-reporting-acquired-skills-kpi-title': 'Nombre d\'acquisitions de savoirs',
    'training-reporting-acquired-skills-help-title': 'Nombre de l\'ensemble des savoirs acquis par les participants depuis le debut de la période',
    'training-reporting-acquired-skills-help-message': 'Nombre calculé sur cette session de formation (Somme des savoirs acquis lors des formations)',
    'training-reporting-levels-tab-title': 'Chiffres clés concernant les niveaux ({count})',
    'training-reporting-levels-tab-id-col': 'Id',
    'training-reporting-levels-tab-title-col': 'Titre',
    'training-reporting-levels-tab-whasqs-count-col': 'Nb de whasqs',
    'training-reporting-levels-tab-participants-count-col': 'Nb de participants',
    'training-reporting-levels-tab-participants-giving-answers-count-col': 'Nb de répondants',
    'training-reporting-levels-tab-participation-rate-col': 'Taux de participation',
    'training-reporting-levels-tab-success-rate-col': 'Taux de réussite',
    'training-reporting-whasqs-tab-title': 'Chiffres clés concernant les questions formation ({count})',
    'training-reporting-whasqs-tab-id-col': 'Id',
    'training-reporting-whasqs-tab-skill-col': 'Savoir',
    'training-reporting-whasqs-tab-title-col': 'Question',
    'training-reporting-whasqs-tab-users-pre-count-col': 'Répondants positionnement',
    'training-reporting-whasqs-tab-success-rate-pre-col': 'Taux de réussite positionnement',
    'training-reporting-whasqs-tab-sent-on-col': 'Date d\'envoi whasqs formation',
    'training-reporting-whasqs-tab-users-count-col': 'Répondants formation',
    'training-reporting-whasqs-tab-success-rate-col': 'Taux de réussite formation',
    'training-reporting-users-tab-title': 'Chiffres clés concernant les stagiaires ({count})',
    'training-reporting-users-tab-fullname-col': 'Nom', 
    'training-reporting-users-tab-last-whasq-pre-col': 'Dernière réponse positionnement',
    'training-reporting-users-tab-whasqs-pre-count-col': 'Réponses positionnement',
    'training-reporting-users-tab-success-rate-pre-col': 'Taux de réussite positionnement',
    'training-reporting-users-tab-last-whasq-col': 'Dernière réponse formation',
    'training-reporting-users-tab-whasqs-count-col': 'Réponses formation',
    'training-reporting-users-tab-success-rate-col': 'Taux de réussite formation',
    'training-reporting-users-tab-acquired-skills-col': 'Nombre de savoirs acquis',
    'training-reporting-users-tab-attendance-confirmation-col': 'Confirmation de présence',

    'training-reporting-skills-tab-title': 'Chiffres clés concernant les savoirs ({count})',
    'training-reporting-skills-tab-id-col': 'Id',
    'training-reporting-skills-tab-name-col': 'Savoir',
    'training-reporting-skills-tab-level-col': 'Niveau',
    'training-reporting-skills-tab-nb-whasqs-col': 'Nombre de questions',
    'training-reporting-skills-tab-participants-giving-answers-count-col': 'Nombre de répondants',
    'training-reporting-skills-tab-participation-rate-col': 'Taux de participation',
    'training-reporting-skills-tab-success-rate-col': 'Taux de réussite',

    // TrainingEvaluation
    'training-evaluation-title': 'Evaluation de session de formation',
    'training-evaluation-title-name': 'Evaluation de la session de formation "{name}"',
    'training-evaluation-title-participation': '(taux de participation {participationRate}%)',
    'training-evaluation-label-col': 'Label',  
    'training-evaluation-participants-count-col': 'Nb de participants ({count})', 
    'training-evaluation-participants-rate-col': '% de participants',  
    'training-evaluation-not-available': 'L\'évaluation de cette session de formation n\'est pas encore disponible', 
    'training-reporting-users-tab-answered-whasqs-rate-col': 'Taux de réponses', 
    'training-reporting-users-tab-last-answer-date-col': 'Date de la derniére réponse', 
    'training-reporting-users-tab-max-reached-level-col': 'Le niveau atteint',  
    
    // SwitchUserRoleModal
    'switch-user-role-modal-title': 'Changement de rôle pour le collaborateur "{name}"',
    'switch-user-role-modal-new-role': 'Ajouter un rôle au collaborateur :',
    'switch-user-role-modal-remove-role': 'Retirer un rôle au collaborateur :',
    'switch-user-role-modal-role-user': 'Collaborateur',
    'switch-user-role-modal-role-trainer': 'Formateur',
    'switch-user-role-modal-role-admin': 'Administrateur',
    'switch-user-role-modal-add': 'Ajouter',
    'switch-user-role-modal-remove': 'Supprimer',
    'switch-user-role-modal-current-roles': 'L\'utilisateur actuel possède le(s) rôle(s) suivant(s) :',
    'switch-user-role-modal-role-added': 'Le rôle "{role}" a bien été ajouté à ce collaborateur.',
    'switch-user-role-modal-error-adding-role': 'Une erreur s\'est produite lors de l\'ajout du rôle "{role}" à ce collaborateur.',
    'switch-user-role-modal-role-removed': 'Le rôle "{role}" a bien été retiré à ce collaborateur.',
    'switch-user-role-modal-error-removing-role': 'Une erreur s\'est produite lors du retrait du rôle "{role}" à ce collaborateur.',
    'switch-user-role-modal-manager-btn': 'Déclarer ce collaborateur comme manager',
    'switch-user-role-modal-unset-manager-btn': 'Ne plus considérer ce collaborateur comme manager',
    'switch-user-role-modal-defining-manager-success': 'Le collaborateur est maintenant manager',
    'switch-user-role-modal-undefining-manager-success': 'Le collaborateur n\'est maintenant plus manager',
    'switch-user-role-modal-error-defining-manager': 'Une erreur s\'est produite lors de la définition du collaborateur en tant que manager',
    'switch-user-role-modal-error-undefining-manager': 'Une erreur s\'est produite lors du retrait du type manager du collaborateur',

    // ProfileAddChannel
    'profile-add-channel-title': 'Ajout de langue sur votre profil',

    // ExportSearchUsers
    'export-search-users-sheet-name': 'Collaborateurs recherchés',
    'export-search-users-id-col': 'Id',
    'export-search-users-fullname-col': 'Nom complet',
    'export-search-users-job-position-col': 'Poste',
    'export-search-users-answers-count-col': 'Nb de réponses',
    'export-search-users-solutions-count-col': 'Nb de solutions',
    'export-search-users-search-text-col': 'Texte de recherche',
    'export-search-users-skills-col': 'Savoirs',
    'export-search-users-search-skills-col': 'Filtres de savoirs',
    'export-search-users-common-skills-col': 'Savoirs communs',
    'export-search-users-relevance-ratio-col': 'Ratio de correspondance',

    // TrainingReferences
    'training-references-title': 'Mes formations',
    'training-references-archive-confirm': 'Etes-vous sûr de vouloir archiver cette formation ?',
    'training-references-add-btn': 'Ajouter',
    'training-references-state-col': 'Statut',
    'training-references-id-col': 'Id',
    'training-references-name-col': 'Nom',
    'training-references-level-col': 'Niveau',
    'training-references-goal-col': 'Objectif',
    'training-references-code-col': 'Code',
    'training-references-estimated-duration-col': 'Durée estimée',
    'training-references-domain-col': 'Domaine',
    'training-references-skills-col': 'Savoirs',
    'training-references-training-count-col': 'Nb de sessions',
    'training-references-participants-count-col': 'Nb de stagiaires',
    'training-references-actions-col': 'Actions',
    'training-references-action-show-trainings': 'Voir les sessions de formation',
    'training-references-action-no-trainings': 'Aucune session de formation',
    'training-references-not-defined': 'Aucune formation disponible',
    'training-references-update': 'Modifier la formation',
    'training-references-archive': 'Archiver la formation',
    'training-references-see-reporting': 'Voir le reporting',
    'training-references-add-session': 'Ajouter une session',
    'training-references-duplicate': 'Dupliquer la formation',
    'training-references-confirm-duplicate': 'Etes-vous sûr de vouloir dupliquer cette formation ?',
    'training-references-recommendation-rate-col': 'Taux de recommendation',
    'training-references-success-rate-col': 'Taux de réussite',
    'training-references-acquired-skills-col': 'Nombre de savoirs acquis',
    'training-references-training-reference-filter': 'Filtrer par formation',
    'training-references-training-center-filter': 'Filter par organisme de formation',

    // AddTrainingReferenceModal
    'add-training-reference-modal-title': 'Ajout d\'une formation',
    'add-training-reference-modal-update-title': 'Modification de la formation {br}"{name}"',
    'add-training-reference-modal-name': 'Nom',
    'add-training-reference-modal-level': 'Niveau',
    'add-training-reference-modal-code': 'Code',
    'add-training-reference-modal-content': 'Contenu',
    'add-training-reference-modal-goal': 'Objectifs',
    'add-training-reference-modal-audience': 'Public concerné',
    'add-training-reference-modal-estimated-duration': 'Durée estimée',
    'add-training-reference-modal-prerequisite': 'Prérequis',
    'add-training-reference-modal-domain': 'Thème',
    'add-training-reference-modal-skills': 'Savoirs',
    'add-training-reference-modal-add-skill': 'Ajouter',
    'add-training-reference-modal-locale': 'Langue',
    'add-training-reference-modal-add-training': 'Ajouter une session',
    'add-training-reference-modal-update': 'Modifier',
    'add-training-reference-modal-create': 'Ajouter',
    'add-training-reference-modal-missing-field': 'Le champs "{field}" est requis. Merci de le compléter pour pouvoir créer la formation 😉',
    'add-training-reference-modal-lang-placeholder': 'Langue de la formation',
    'add-training-reference-modal-level-placeholder': 'Niveau de la formation',
    'add-training-reference-modal-added': 'La formation a bien été ajoutée',
    'add-training-reference-modal-updated': 'La formation a bien été modifiée',
    'add-training-reference-close-confirm': 'Etes-vous sûr de vouloir quitter sans enregistrer ?',

    // TrainingReferenceReporting
    'training-ref-kpis-title': 'Chiffres clés',
    'training-ref-kpis-updated-at': 'Mis à jour le {date} à {hours}h{minutes}',
    'training-ref-reporting-title': 'Reporting de formation',
    'training-ref-reporting-title-name': 'Reporting "{name}"',
    'training-ref-reporting-no-data-title': 'Reporting : pas de donnée à ce jour',
    'training-ref-reporting-respondents': '{respondentsCount} répondants',
    'training-ref-reporting-participants-count-kpi-title': 'Nombre d\'inscriptions aux formations',
    'training-ref-reporting-participants-count-help-title': 'Nombre de stagiaires inscrits aux formations ayant validés ou non leurs comptes',
    'training-ref-reporting-participants-count-help-message': 'Moyenne calculée sur toutes les sessions de formation de cette formation (somme des stagiaires ayant été inscrit à une session de formation)',
    'training-ref-reporting-success-rate-pre-kpi-title': 'Taux de réussite (positionnenement)',
    'training-ref-reporting-success-rate-pre-help-title': 'Pourcentage de bonnes réponses aux questionnaires de positionnement',
    'training-ref-reporting-success-rate-pre-help-message': 'Moyenne calculée sur toutes les sessions de formation de cette formation (nb bonnes réponses Q1 / nb questions répondues Q1) * 100',
    'training-ref-reporting-success-rate-kpi-title': 'Taux de réussite (formation)',
    'training-ref-reporting-success-rate-help-title': 'Pourcentage de bonnes réponses aux questionnaires après formation',
    'training-ref-reporting-success-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de cette formation (nb bonnes réponses Questionnaire formation / nb questions répondues Questionnaire formation) * 100',
    'training-ref-reporting-commitment-rate-kpi-title': 'Taux d\'engagement',
    'training-ref-reporting-commitment-rate-help-title': 'Pourcentage des stagiaires ayant répondu au minimum à un questionnaire',
    'training-ref-reporting-commitment-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de cette formation  (Nombre de stagiaires uniques répondants à au moins 1 questionnaire pré évaluation, satisfaction post formation par session/Nombre de stagiaires uniques inscrits à la session de formation)',
    'training-ref-reporting-satisfaction-rate-kpi-title': 'Taux de satisfaction',
    'training-ref-reporting-satisfaction-rate-help-title': 'Pourcentage des avis positifs des stagiaires suite à la formation',
    'training-ref-reporting-satisfaction-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de cette formation (Nombre d\'avis positifs (3 et 4 étoiles sur la 1ère question) du questionnaire de satisfaction de la session formation / Nombre d\'avis du questionnaire de satisfaction de la session formation)',
    'training-ref-reporting-attendance-rate-kpi-title': 'Taux de présence',
    'training-ref-reporting-attendance-rate-help-title': 'Pourcentage des stagiaires présents lors des formations',
    'training-ref-reporting-attendance-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de cette formation (Nombre de stagiaires présents à J+1 / Nombre de stagiaires inscrits à J-1) * 100',
    'training-ref-reporting-acquired-skills-participant-kpi-title': 'Moyenne des savoirs acquis',
    'training-ref-reporting-acquired-skills-participant-help-title': 'Ce chiffre donne le nombre de savoirs acquis en moyenne par les stagiaires répondants',
    'training-ref-reporting-acquired-skills-participant-help-message': 'Moyenne calculée sur toutes les sessions de formation de cette formation (Nombre de savoirs acquis / Nombre de stagiaires ayant répondu à 100% au Questionnaire formation) * 100',
    'training-ref-reporting-sessions-count-kpi-title': 'Nombre de sessions de formation',
    'training-ref-reporting-sessions-count-help-title': 'Nombre des sessions de formations programmées',
    'training-ref-reporting-sessions-count-help-message': 'Nombre calculé sur toutes les sessions de formation de cette formation (Nombre total de sessions programmées dans la base whasq)',
    'training-ref-reporting-sessions-tab-title': 'Chiffres clés concernant les sessions ({count})',
    'training-ref-reporting-sessions-tab-id-col': 'Id',
    'training-ref-reporting-sessions-tab-session-col': 'Session',
    'training-ref-reporting-sessions-tab-periode-col': 'Période',
    'training-ref-reporting-sessions-tab-support-ends-at-col': 'Fin de support',
    'training-ref-reporting-sessions-tab-whasqs-count-col': 'Nb de whasqs',
    'training-ref-reporting-sessions-tab-participants-count-col': 'Nb de participants',
    'training-ref-reporting-sessions-tab-participation-rate-col': 'Taux de participation',
    'training-ref-reporting-sessions-tab-respondents-col': 'Nb de répondants',
    'training-ref-reporting-sessions-tab-success-rate-col': 'Taux de réussite',
    'training-ref-reporting-sessions-tab-action-col': 'Actions',

    // AddUserModal
    'add-user-modal-title': 'Ajouter un collaborateur',
    'add-user-modal-fullname': 'Nom complet (*)',
    'add-user-modal-email': 'Email (*)',
    'add-user-modal-phone': 'Téléphone (*)',
    'add-user-modal-job-position': 'Poste (*)',
    'add-user-modal-add-btn': 'Ajouter',
    'add-user-modal-missing-field': 'Le champs "{field}" est requis. Merci de le compléter pour pouvoir ajouter le collaborateur 😉',
    'add-user-modal-close-confirm': 'Etes-vous sûr de vouloir quitter sans enregistrer ?',

    // MyKPIs
    'my-kpis-title': 'Mes Chiffres clés',
    'my-kpis-no-data-title': 'Mes Chiffres clés : Pas de donnée disponible',
    'my-kpis-trainer': 'FORMATEUR',
    'my-kpis-drh': 'DRH',
    'my-kpis-contact-of': 'CONTACT O.F.',
    'my-kpis-participants-count-kpi-title': 'Nombre d\'inscriptions aux formations',
    'my-kpis-participants-count-help-title': 'Nombre de stagiaires inscrits aux formations (ayant validés ou non leurs comptes)',
    'my-kpis-participants-count-help-message': 'Somme calculée sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Somme des stagiaires ayant été inscrit à une session de formation)',
    'my-kpis-participants-count-trainer-help-message': 'Somme calculée sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (Somme des stagiaires ayant été inscrit à une session de formation)',
    'my-kpis-participants-count-contact-of-help-message': 'Somme calculée sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (Somme des stagiaires ayant été inscrit à une session de formation)',
    'my-kpis-success-rate-kpi-title': 'Taux de réussite (formation)',
    'my-kpis-success-rate-help-title': 'Pourcentage de bonnes réponses aux questionnaires d\'après formation',
    'my-kpis-success-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (nb bonnes réponses du questionnaire formation / nb questions répondues aux questionnaires formation ) * 100',
    'my-kpis-success-rate-trainer-help-message': 'Moyenne calculée sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (nb bonnes réponses du questionnaire formation / nb questions répondues aux questionnaires formation) * 100',
    'my-kpis-success-rate-contact-of-help-message': 'Moyenne calculée sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (nb bonnes réponses du questionnaire formation / nb questions répondues aux questionnaires formation) * 100',
    'my-kpis-commitment-rate-kpi-title': 'Taux d\'engagement',
    'my-kpis-commitment-rate-help-title': 'Pourcentage des stagiaires répondants à au moins un questionnaire',
    'my-kpis-commitment-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Nombre de stagiaires uniques répondants à au moins 1 questionnaire positionnement, satisfaction, de formation par session / Nombre de stagiaires uniques inscrits à la session de formation)',
    'my-kpis-commitment-rate-contact-of-help-message': 'Moyenne calculée sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (Nombre de stagiaires uniques répondants à au moins 1 questionnaire positionnement, satisfaction, de formation par session / Nombre de stagiaires uniques inscrits à la session de formation)',
    'my-kpis-commitment-rate-trainer-help-message': 'Moyenne calculée sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (Nombre de stagiaires uniques répondants à au moins 1 questionnaire positionnement, satisfaction, de formation par session / Nombre de stagiaires uniques inscrits à la session de formation)',
    'my-kpis-satisfaction-rate-kpi-title': 'Taux de satisfaction',
    'my-kpis-satisfaction-rate-help-title': 'Pourcentage des avis positifs des stagiaires suite à la formation',
    'my-kpis-satisfaction-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Nombre d\'avis positifs (3 et 4 étoiles sur la 1ère question) du questionnaire de satisfaction de la session formation / Nombre d\'avis du questionnaire de satisfaction de la session formation)',
    'my-kpis-satisfaction-rate-trainer-help-message': 'Moyenne calculée sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (Nombre d\'avis positifs (3 et 4 étoiles sur la 1ère question) du questionnaire de satisfaction de la session formation / Nombre d\'avis du questionnaire de satisfaction de la session formation)',
    'my-kpis-satisfaction-rate-contact-of-help-message': 'Moyenne calculée sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (Nombre d\'avis positifs (3 et 4 étoiles sur la 1ère question) du questionnaire de satisfaction de la session formation / Nombre d\'avis du questionnaire de satisfaction de la session formation)',
    'my-kpis-attendance-rate-kpi-title': 'Taux de présence',
    'my-kpis-attendance-rate-help-title': 'Pourcentage des stagiaires présents lors des formations',
    'my-kpis-attendance-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Nombre de stagiaires présents à J+1 / Nombre de stagiaires inscrits à J-1) * 100',
    'my-kpis-attendance-rate-trainer-help-message': 'Moyenne calculée sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (Nombre de stagiaires présents à J+2 / Nombre de stagiaires inscrits à J+1) * 100',
    'my-kpis-attendance-rate-contact-of-help-message': 'Moyenne calculée sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (Nombre de stagiaires présents à J+2 / Nombre de stagiaires inscrits à J+1) * 100',
    'my-kpis-acquired-skills-per-participant-kpi-title': 'Moyenne des savoirs acquis',
    'my-kpis-acquired-skills-per-participant-help-title': 'Ce chiffre donne le nombre de savoirs acquis en moyenne par les stagiaires répondants',
    'my-kpis-acquired-skills-per-participant-help-message': 'Moyenne calculée sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Nombre de savoirs acquis / Nombre de stagiaires ayant répondu à 100% au Questionnaire formation) * 100',
    'my-kpis-acquired-skills-per-participant-trainer-help-message': 'Moyenne calculée sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (Nombre de savoirs acquis / Nombre de stagiaires ayant répondu à 100% au Questionnaire formation) * 100',
    'my-kpis-acquired-skills-per-participant-contact-of-help-message': 'Moyenne calculée sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (Nombre de savoirs acquis / Nombre de stagiaires ayant répondu à 100% au Questionnaire formation) * 100',
    'my-kpis-acquired-skills-kpi-title': 'Nombre d\'acquisitions de savoirs',
    'my-kpis-acquired-skills-help-title': 'Nombre de l\'ensemble des savoirs acquis par les participants depuis le debut de la période',
    'my-kpis-acquired-skills-help-message': 'Nombre calculé sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Somme des savoirs acquis lors des formations)',
    'my-kpis-acquired-skills-trainer-help-message': 'Nombre calculé sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (Somme des savoirs acquis lors des formations)',
    'my-kpis-acquired-skills-contact-of-help-message': 'Nombre calculé sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (Somme des savoirs acquis lors des formations)',
    'my-kpis-trainings-count-kpi-title': 'Nombre de formations',
    'my-kpis-trainings-count-help-title': 'Ce chiffre donne le nombre de formations',
    'my-kpis-trainings-count-help-message': 'Nombre calculé sur toutes les sessions de formation de TOUS LES OF ayant débuté dans l\'année séléctionnée (Nombre total de formations ayant au moins une session programmée dans la base whasq)',
    'my-kpis-trainings-count-trainer-help-message': 'Nombre calculé sur toutes les sessions de formation du formateur ayant débuté dans l\'année séléctionnée (Nombre total de formations ayant au moins une session programmée dans la base whasq)',
    'my-kpis-trainings-count-contact-of-help-message': 'Nombre calculé sur toutes les sessions de formation de cet OF ayant débuté dans l\'année séléctionnée (Nombre total de formations ayant au moins une session programmée dans la base whasq)',
    'my-kpis-training-centers-count-kpi-title': 'Nombre d\'OF',
    'my-kpis-training-centers-count-help-title': 'Nombre d\'OF dans la base',
    'my-kpis-training-centers-count-help-message': 'Nombre total d\'OF dans la base ayant accès à Whasq',
    'my-kpis-training-sessions-count-kpi-title': 'Nombre de sessions de formation',
    'my-kpis-training-sessions-count-help-title': 'Nombre des sessions de formations programmées',
    'my-kpis-training-sessions-count-help-message': 'Nombre total des sessions programmées dans la base whasq',
    'my-kpis-training-sessions-count-trainer-help-message': 'Nombre total des sessions programmées dans la base whasq pour ce formateur',
    'my-kpis-training-sessions-count-contact-of-help-message': 'Nombre total des sessions programmées dans la base whasq pour cet OF',
    'my-kpis-recommendation-rate-kpi-title': 'Taux de recommandation',
    'my-kpis-recommendation-rate-help-title': 'Pourcentage des stagiaires recommandant les formations',
    'my-kpis-recommendation-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de TOUS LES OF (Nombre de stagiaires répondants, recommandant la formation / nombre de stagiaires répondants total) * 100',
    'my-kpis-recommendation-rate-trainer-help-message': 'Moyenne calculée sur toutes les sessions de formation du formateur (Nombre de stagiaires répondants, recommandant la formation / nombre de stagiaires répondants total) * 100',
    'my-kpis-recommendation-rate-contact-of-help-message': 'Moyenne calculée sur toutes les sessions de formation de cet OF (Nombre de stagiaires répondants, recommandant la formation / nombre de stagiaires répondants total) * 100',
    'my-kpis-roi-kpi-title': 'ROI',
    'my-kpis-roi-help-title': 'Retour sur investissement',
    'my-kpis-roi-help-message': 'Budget d\'une session de formation * nombre de particpants / nombre de partipants répondants ayant réussi le formation',

    // LevelChoiceModal
    'level-choice-modal-title': 'Choisir le(s) niveau(x)',
    'level-choice-modal-subtitle': 'Choisissez le ou les niveau(x) pour le savoir "{skillName}"',
    'level-choice-modal-expert': 'Expert',
    'level-choice-modal-confirmed': 'Confirmé',
    'level-choice-modal-intermediate': 'Intermédiaire',
    'level-choice-modal-begginer': 'Débutant',
    'level-choice-modal-declared': 'Déclaratif',
    'level-choice-modal-error-title': 'Erreur',
    'level-choice-modal-error-message': 'Vous devez sélectionner au minimum un niveau pour lancer la recherche.',

    // Interns
    'interns-title': 'Mes stagiaires',

    // TrainingCenterReporting
    'training-center-kpis-title': 'Chiffres clés',
    'training-center-kpis-updated-at': 'Mis à jour le {date} à {hours}h{minutes}',
    'training-center-reporting-no-data-title': 'Pas de donnée de reporting pour cet organisme de formation.',
    'training-center-reporting-participants-count-kpi-title': 'Nombre d\'inscriptions aux formations',
    'training-center-reporting-participants-count-help-title': 'Nombre de stagiaires inscrits aux formations ayant validés ou non leurs comptes',
    'training-center-reporting-participants-count-help-message': 'Moyenne calculée sur toutes les sessions de formation de l\'OF (Somme des stagiaires ayant été inscrit à une session de formation)',
    'training-center-reporting-success-rate-pre-kpi-title': 'Taux de réussite (positionnenement)',
    'training-center-reporting-success-rate-pre-help-title': 'Pourcentage de bonnes réponses aux questionnaires de positionnement',
    'training-center-reporting-success-rate-pre-help-message': 'Moyenne calculée sur toutes les sessions de formation de L\'OF (nb bonnes réponses Q1 / nb questions répondues Q1) * 100',
    'training-center-reporting-success-rate-kpi-title': 'Taux de réussite (formation)',
    'training-center-reporting-success-rate-help-title': 'Pourcentage de bonnes réponses aux questionnaires après formation',
    'training-center-reporting-success-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de L\'OF (nb bonnes réponses Questionnaire formation / nb questions répondues Questionnaire formation) * 100',
    'training-center-reporting-commitment-rate-kpi-title': 'Taux d\'engagement',
    'training-center-reporting-commitment-rate-help-title': 'Pourcentage des stagiaires ayant répondu au minimum à un questionnaire',
    'training-center-reporting-commitment-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de l\'OF (Nombre de stagiaires uniques répondants à au moins 1 questionnaire pré évaluation, satisfaction post formation par session / Nombre de stagiaires uniques inscrits à la session de formation)',
    'training-center-reporting-satisfaction-rate-kpi-title': 'Taux de satisfaction',
    'training-center-reporting-satisfaction-rate-help-title': 'Pourcentage des avis positifs des stagiaires suite à la formation',
    'training-center-reporting-satisfaction-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de l\'OF (Nombre d\'avis positifs (3 et 4 étoiles sur la 1ère question) du questionnaire de satisfaction de la session formation / Nombre d\'avis du questionnaire de satisfaction de la session formation)',
    'training-center-reporting-attendance-rate-kpi-title': 'Taux de présence',
    'training-center-reporting-attendance-rate-help-title': 'Pourcentage des stagiaires présents lors des formations',
    'training-center-reporting-attendance-rate-help-message': 'Moyenne calculée sur toutes les sessions de formation de l\'OF (Nombre de stagiaires présents à J+1 / Nombre de stagiaires inscrits à J-1) * 100',
    'training-center-reporting-acquired-skills-kpi-title': 'Moyenne des savoirs acquis',
    'training-center-reporting-acquired-skills-help-title': 'Ce chiffre donne le nombre de savoirs acquis en moyenne par les stagiaires répondants',
    'training-center-reporting-acquired-skills-help-message': 'Moyenne calculée sur toutes les sessions de formation de l\'OF (Nombre de savoirs acquis / Nombre de stagiaires ayant répondu à 100% au Questionnaire formation) * 100',
    'training-center-reporting-sessions-count-kpi-title': 'Nombre de sessions de formation',
    'training-center-reporting-sessions-count-help-title': 'Nombre des sessions de formations programmées',
    'training-center-reporting-sessions-count-help-message': 'Nombre calculé sur toutes les sessions de formation de l\'OF (Nombre total de sessions programmées dans la base whasq)',

    // CardUser
    'card-user-collaborative-actions': 'Actions collaboratives',

    // Podium
    'ranking-title': 'Podium',
    'ranking-ytd-label': 'Depuis le début {year}',
    'ranking-all-label': 'Depuis le début de l\'activité',
    'ranking-no-podium-for-selected-month': 'Il n\'y a pas de podium pour la période sélectionnée',

    // LanguageDropdown
    'language-dropdown-placeholder': 'Choisir la langue',
    'language-dropdown-empty-list': 'Il n\'y a aucune langue disponible',

    // AddSkillCatLangModal
    'add-skill-cat-lang-modal-title': 'Ajout d\'une langue',
    'add-skill-cat-lang-modal-explanation': 'L\'ajout d\'une langue permet à vos collaborateurs de naviguer dans une autre langue',
    'add-skill-cat-lang-modal-unavailable': 'Menu déjà disponible en',
    'add-skill-cat-lang-modal-add': 'Ajouter',
    'add-skill-cat-lang-modal-remember': 'N\'oubliez pas de traduire votre référenciel de savoirs après l\'avoir dupliqué',
    'add-skill-cat-lang-modal-error-adding': 'Vous devez sélectionner une langue pour pouvoir l\'ajouter',

    // AddCategoryModal
    'add-category-modal-add-cat-title': 'Ajout d\'un thème',
    'add-category-modal-update-cat-title': 'Modification d\'un thème',
    'add-category-modal-add-skill-title': 'Ajout d\'un savoir',
    'add-category-modal-update-skill-title': 'Modification d\'un savoir',
    'add-category-modal-existing-cats': 'Thèmes existants',
    'add-category-modal-existing-skills': 'Savoirs existants',
    'add-category-modal-add': 'Ajouter',
    'add-category-modal-update': 'Modifier',
    'add-category-modal-no-filtered-cats': 'Aucun thème ne correspond à votre recherche.',
    'add-category-modal-no-filtered-skills': 'Aucun savoir ne correspond à votre recherche.',
    'add-category-modal-cat-ever-exist': 'Vous ne pouvez pas choisir ce label car un thème porte déjà ce nom.',
    'add-category-modal-skill-ever-exist': 'Vous ne pouvez pas choisir ce label car un savoir porte déjà ce nom.',

    // AddManagerModal
    'add-manager-modal-title': 'Ajout d\'un manager',
    'add-manager-modal-update-title': 'Modification d\'un manager',
    'add-manager-modal-select': 'Veuillez choisir un manager dans la liste déroulante :',
    'add-manager-modal-select-placeholder': 'Cliquer pour sélectionner un manager',
    'add-manager-modal-validate': 'Valider',

    // AddWhasqSkillModal
    'add-whasq-skill-title': 'Ajouter au maximum 3 savoirs',

    // UploadProfileImageModal
    'choose-profile-image': 'Choisir une image de profil',
}

export default messages
