const messages = {
    // Login
    'Email': 'Mon email',
    'Login': 'Me connecter',
    'Password': 'Mon mot de passe',
    'Provided by your administrator': 'Fourni par votre administrateur',
    'Remember me': 'Se souvenir de moi',
    'no-identification-info': 'Si vous n\'avez pas vos identifiants, veuillez contacter votre administrateur',
    'bad-credentials': 'Vos identifiants sont incorrects. Veuillez réessayer svp.',
    'not-enough-rights': 'Vous n\'avez pas les droits suffisants pour vous connecter.Veuillez contacter votre administrateur',
    'user-not-found': 'Le collaborateur n\'a pas été trouvé.',
    'login-form-email-placeholder': 'Ex : KarineM@monentreprise.com',
    'login-form-password-placeholder': '8 caractères mini ...',

    // General
    'more-info': 'Plus d\'infos',
    'from': 'Du',
    'to': 'au',
    'real-time': 'en temps réel',
    'update': 'Modifier',
    'delete': 'Supprimer',
    'previous': 'Précédent',
    'next': 'Suivant',
    'send': 'Envoyer',
    'export-all': 'Exporter tout',
    'yes': 'Oui',
    'no': 'Non',
    'open': 'Ouvert',
    'fullname': 'Mon Nom et Prénom ',
    'job-position': 'Mon Métier',
    'assistance': 'Besoin d’aide ? Contactez jessie@whasq.com. Plus d\'info sur https://whasq.com.',
    'download-attachment': 'Télécharger la pièce jointe',
    'day': 'jour',
    'days': 'jours',
    'waiting': 'En réfléxion...',
    'loading': 'En cours de réflexion...',
    'read': 'Déjà lu',
    'unread': 'Non lu',

    // Menu
    // 'activity': 'Activité',
    // 'actives-users': 'Collaborateurs Actifs',
    // 'registered-users': 'Collaborateurs Inscrits',
    // 'whasqs-answers': 'Whasqs & Réponses',
    // 'skills': 'Skills',
    // 'time-savings': 'Gain de temps',
    // 'whasqers': 'Animation Whasqers',
    // 'podium': 'Podium',
    // 'search': 'Recherche',
    // 'manage': 'Gestion de la plateforme',
    // 'skills-categories': 'Skills & Catégories',
    // 'whasqs': 'Whasqs',
    // 'whasqs-reports': 'Whasqs signalés',
    // 'answers': 'Réponses',
    // // 'answers-reports': 'Réponses signalées',
    // 'users': 'Collaborateurs',
    // 'admin': 'Administration',
    // 'targets': 'Objectifs & Gamification',
    // 'notifications': 'Notifications',
    // 'learning': 'Formation',
    // 'training-centers': 'Organismes de formation',
    // 'trainings': 'Sessions de formations',
    // 'training-references': 'Formations',
    // 'training-reporting': 'Reporting de formation',
    // 'interns': 'Stagiaires',
    // 'training-center-reporting': 'Reporting d\'organisme de formation',

    // NewMenu
    'dashboard': 'Mon dashboard',
    'my-kpis': 'Mes chiffres clés',
    'skills-kpis': 'Infos Skills ',
    'time-savings-kpis': 'Gain de temps ?',
    'training-lab': 'Lab\'Formation',
    'my-users': 'Mes collaborateurs',
    'skills-management': 'Base de données des Skills',
    'my-training-centers': 'Mes Organismes de Formations',
    'training-center-reporting': 'Chiffres clés de l\'organisme de formation',
    'my-training-references': 'Mon catalogue formations',
    'training-reference-reporting': 'Chiffres clés de l\'organisme de formation',
    'my-trainings': 'Mes sessions de formation',
    'training-reporting': 'Chiffres clés de la formation',
    'training-evaluation': 'Evaluation de la formation',
    'my-interns': 'Mes stagiaires',
    'my-community': 'Ma communauté',
    'active-users-kpis': 'Whasqers actifs',
    'ranking': 'Podium',
    'search': 'Recherche de Skills',
    'platform-activity': 'Flux de Whasqs',
    'whasqs': 'Les Whasqs',
    'answers': 'Les Réponses',

    // Activity
    'eve-computed-kpi': 'Cet indicateur est calculé à J-1',
    'no-data-for-selected-period': 'Aucune donnée disponible pour la période sélectionnée',
    'no-data-available': 'Aucune donnée disponible',

    // ActivityActiveUsers
    'actives-title': 'Personnes actives',
    'actives-kpi-title': 'Actifs',
    'actives-kpi-help-title': 'Personnes Actives',
    'actives-kpi-help-message': 'Cet indicateur représente le nombre de personnes qui se sont connecté au moins une fois au cours du mois de "{month}".',
    'actives-dda-kpi-title': 'Actifs depuis le tout début',
    'actives-dda-kpi-help-title': 'Actifs depuis le tout début',
    'actives-dda-kpi-help-message': 'Cet indicateur représente le nombre de personnes qui se sont connecté au moins 1 fois depuis le lancement de l\'application.',
    'actives-target-kpi-title': 'Actifs/Objectifs du trimestre',
    'actives-target-kpi-help-title': 'Actifs/Objectifs du trimestre',
    'actives-target-kpi-help-message': 'Cet indicateur représente le % entre le nombre de personnes qui se sont connecté au moins une fois au cours du mois de "{month}" par rapport à l\'objectif défini par l\'administrateur (voir onglet administration).',
    'actives-evolution-title': 'Evolution des actifs',
    'actives-evolution-help-title': 'Evolution des actifs',
    'actives-evolution-help-message': 'Cet indicateur représente le nombre de personnes actives.',
    'actives-dda-evolution-title': 'Evolution cumulée des actifs  depuis le tout début',
    'actives-dda-evolution-period-selector' : "Filtrer par date", 
    'actives-dda-evolution-help-title': 'Evolution des actifs depuis le tout début',
    'actives-dda-evolution-help-message': 'Cet indicateur représente le nombre cumulé de personnes qui se sont connecté au moins une fois par jour depuis le lancement de l\'application.',
    'actives-notregistered-evolution-title': 'Evolution des actifs - inscription',
    'actives-notregistered-evolution-help-title': 'Evolution des actifs - inscription',
    'actives-notregistered-evolution-help-message': 'Cet indicateur représente le nombre de personnes actives Moins les collaborateurs inscrits.',

    // ActivityRegisteredUsers
    //'registered-title': 'Collaborateurs Inscrits - {month}',
    //'registered-kpi-title': 'Inscrits',
    //'registered-kpi-help-title': 'Personnes ayant un compte',
    //'registered-kpi-help-message': 'Cet indicateur représente le nombre de personnes qui se sont inscrits au mois de "{month}".',
    //'registered-inactives-kpi-title': 'Pourcentage d\'inscrits non actifs',
    //'registered-inactives-kpi-help-title': 'Pourcentage d\'inscrits non actifs',
    //'registered-inactives-kpi-help-message': 'Cet indicateur représente le rapport entre le nombre de personnes qui se sont inscrits au mois de "{month}" sans s\'être connectés par rapport au nombre de collaborateurs total inscrits dans le mois.',
    //'registered-inactives-evolution-title': 'Evolution des inscriptions',
    //'registered-inactives-evolution-help-title': 'Evolution des inscriptions',
    //'registered-inactives-evolution-help-message': 'Cet indicateur représente le nombre de collaborateurs inscrits.',

    // ActivityWhasqs
    //'whasqs-answers-title': 'Whasqs & Réponses - {month}',
    //'whasqs-answers-kpi-title': 'Nombre total de Whasqs et de réponses ce mois-ci',
    //'whasqs-answers-kpi-help-title': 'Nombre total de Whasqs et de réponses ce mois-ci',
    //'whasqs-answers-kpi-help-message': 'Cet indicateur représente le nombre de whasqs et de réponses postés au mois de "{month}".',
    //'whasqs-by-whasqer-kpi-title': 'Nombre de Whasqs / Whasqer actif ce mois-ci',
    //'whasqs-by-whasqer-kpi-help-title': 'Nombre de Whasqs / Whasqer actif',
    //'whasqs-by-whasqer-kpi-help-message': 'Cet indicateur représente le nombre de whasqs postés au mois de "{month}" par whasqer actif.',
    //'answers-kpi-title': 'Nombre de réponses ce mois-ci',
    //'answers-kpi-help-title': 'Nombre de réponses',
    //'answers-kpi-help-message': 'Cet indicateur représente le nombre de réponses postées au mois de "{month}".',
    //'answers-by-creator-kpi-title': 'Nombre de réponses / Whasqer actif ce mois-ci',
    //'answers-by-creator-kpi-help-title': 'Nombre de réponses / Whasqer actif',
    //'answers-by-creator-kpi-help-message': 'Cet indicateur représente le nombre de réponses postées au mois de "{month}" par whasqer actif.',
    //'whasqs-with-contribution-kpi-title': 'Pourcentage de Whasqs avec réponse ce mois-ci',
    //'whasqs-with-contribution-kpi-help-title': 'Pourcentage de Whasqs ayant eu au moins une réponse',
    //'whasqs-with-contribution-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont reçu au moins une réponse au mois de "{month}".',
    //'whasqs-with-contribution-dda-kpi-title': 'Pourcentage de Whasqs avec réponse depuis le début',
    //'whasqs-with-contribution-dda-kpi-help-title': 'Pourcentage de Whasqs avec réponse depuis le début',
    //'whasqs-with-contribution-dda-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont reçu au moins 1 réponse depuis le lancement de l\'application.',
    //'whasqs-resolved-part-kpi-title': 'Pourcentage de Whasqs résolus ce mois-ci',
    //'whasqs-resolved-part-kpi-help-title': 'Pourcentage de Whasqs résolus',
    //'whasqs-resolved-part-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont été résolus au mois de "{month}".',
    //'whasqs-resolved-part-dda-kpi-title': 'Pourcentage de Whasqs résolus depuis le début',
    //'whasqs-resolved-part-dda-kpi-help-title': 'Pourcentage de Whasqs résolus depuis le début',
    //'whasqs-resolved-part-dda-kpi-help-message': 'Cet indicateur représente le % de whasqs qui ont été résolus depuis le lancement de l\'application.',
    //'whasqs-evolution-title': 'Suivi du nombre de whasqs par jour',
    //'whasqs-evolution-help-title': 'Suivi du nombre de whasqs par  jour',
    //'whasqs-evolution-help-message': 'Cet indicateur représente le nombre de whasqs par jour.',
    //'answers-evolution-title': 'Suivi du nombre de réponses par jour',
    //'answers-evolution-help-title': 'Suivi du nombre de réponses',
    //'answers-evolution-help-message': 'Cet indicateur représente le nombre de réponses par jour.',

    // ActivitySkills
    'skills-title': 'Skills',
    'skills-dda-kpi-title': 'Nombre total de Skills dans votre organisation ',
    'skills-dda-kpi-help-title': 'Somme de tous Skills de votre organisation',
    'skills-dda-kpi-help-message': 'Cet indicateur représente la somme de tous de Skills présents dans les profils de vos collaborateurs, depuis le lancement de l\'application.',
    //'skills-part-kpi-title': '% de Skills uniques identifiés',
    //'skills-part-kpi-help-title': '% de Skills uniques identifiés',
    //'skills-part-kpi-help-message': 'Cet indicateur représente le % de Skills uniques présents dans les profils de vos collaborateurs par rapport au nombre de Skills existants depuis le lancement de l\'application.',
    //'skills-evolution-title': 'Suivi du nombre de Skills identifiés dans les whasqs chaque jour',
    //'skills-evolution-help-title': 'Suivi du nombre de Skills identifiés dans les whasqs chaque jour',
    //'skills-evolution-help-message': 'Cet indicateur représente le nombre de Skills identifiés dans les whasqs chaquejour.',
    'most-used-cats-whasqs-kpi-title': 'Top 5 Thèmes dans les Whasqs',
    'most-used-cats-whasqs-kpi-help-title': 'Les 5 thèmes les plus utilisés dans les whasqs',
    'most-used-cats-whasqs-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 thèmes dont les Skills sont les plus utilisés dans les Whasqs..',
    'most-used-cats-whasqs-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où les skills du thème en question sont utilisés.',
    'most-used-skills-whasqs-kpi-title': 'Top 5 des Skills dans les Whasqs ',
    'most-used-skills-whasqs-kpi-help-title': 'Les 5 Skills les plus utilisés dans les whasqs',
    'most-used-skills-whasqs-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 skills les plus utilisés dans les Whasqs .',
    'most-used-skills-whasqs-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où le Skill est utilisé dans un Whasq.',
    'most-used-whasqers-kpi-title': 'Top 5 Skills dans les profils',
    'most-used-whasqers-kpi-help-title': 'Les 5 Skills les plus présents dans les profils',
    'most-used-whasqers-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 skills les plus présents dans les profils.',
    'most-used-whasqers-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où le skill est présent dans les profils.',
    'less-used-whasqers-kpi-title': 'Flop 5 Skills dans les profils',
    'less-used-whasqers-kpi-help-title': 'Les 5 Skills les moins utilisés dans les profils',
    'less-used-whasqers-kpi-help-message-1': 'Vous trouverez dans ce tableau les 5 Skills les moins utilisés dans les profils.',
    'less-used-whasqers-kpi-help-message-2': 'Les pastilles colorées représentent le nombre de fois où le Skill a été utilisé dans le profil.',
    'activity-skills-top-five': 'TOP et FLOP 5 !',

    // TimeSavings
    'time-savings-title': 'Gain de temps - {month}',
    'minutes-earned-kpi-title': 'Minutes gagnées ce mois',
    'minutes-earned-kpi-help-title': 'Minutes gagnées ce mois',
    'minutes-earned-kpi-help-message': 'Cet indicateur représente le nombre de minutes gagnées  grâce à l\'entraide collaborative au cours du mois de "{month}".',
    'minutes-earned-dda-kpi-title': 'Minutes gagnées depuis le début',
    'minutes-earned-dda-kpi-help-title': 'Minutes gagnées depuis le début',
    'minutes-earned-dda-kpi-help-message': 'Cet indicateur représente le nombre de minutes gagnées depuis le début du lancement de l\'application.',
    'minutes-earned-month-kpi-title': 'Minutes gagnées du mois',

    // Podium
    //'podium-title': 'PODIUM',
    //'whasqers-of-month': 'Whasqers du mois de',
    //'no-podium-for-selected-month': 'Aucun podium n\'est disponible pour le mois sélectionné',

    // Card-user
    //'answers-label': 'Réponses',
    //'points-label': 'Points',
    //'solutions-label': 'Solutions',
    'see-profile': 'Voir le profil',

    // Search
    'search-title': 'Recherchez des skills',
    'search-by-name-placeholder': 'Recherchez par nom, prenom ou e-mail...',
    'no-result-select-criteria': 'Aucun résultat. Veuillez saisir au moins un Skill.',
    'search-export': 'Exportez les données',

    // CategoriesSearchBlock
    'dynamic-search-title': 'Recherche dynamique',
    'categories-search-block-selected-filters': '{count} fitre(s) sélectionné(s)',

    // SkillsCategories
    'skills-categories-title': 'Base de données des Skills',
    'update-cat-for-lang': 'Modification du thème pour la langue {lang}',
    'update-skill-for-cat-and-lang-fr': 'Modification du Skills pour le thème "{cat}" et la langue FR',
    'add-cat-for-lang-fr': 'Ajout du thème pour la langue FR',
    'add-skill-for-cat-and-lang-fr': 'Ajout du Skill pour le thème "{cat}" et la langue FR',
    'skills-categories-remove-cat-confirm': 'Etes-vous sûr(e) de vouloir supprimer ce thème ?',
    'skills-categories-remove-skill-confirm': 'Etes-vous sûr(e) de vouloir supprimer ce Skill ?',
    'choose-lang': 'Choisissez une langue',
    'add-lang': 'Ajouter une langue et traduire',
    'add-cat': 'Ajoutez un nouveau thème',
    'skills-unavailable': 'Aucun thème ni Skill ne sont créés pour le moment.',
    'skills-categories-add': 'Ajouter un Skill',
    'skills-categories-cat-added': 'Le nouveau thème "{catLabel}" a bien été ajouté.',
    'skills-categories-error-adding-cat': 'Une erreur s\'est produite lors de l\'ajout du thème "{catLabel}".',
    'skills-categories-cat-updated': 'Le thème a bien été modifié en "{catLabel}"',
    'skills-categories-error-updating-cat': 'Une erreur s\'est produite lors de la modification du thème.',
    'skills-categories-skill-created': 'Le Skill "{skillLabel}" a bien été ajouté.',
    'skills-categories-skill-error-creating-skill': 'Une erreur s\'est produite lors de l\'ajout du Skill "{skillLabel}".',
    'skills-categories-skill-updated': 'Le Skill a bien été modifié en "{skillLabel}"',
    'skills-categories-skill-error-updating-skill': 'Une erreur s\'est produite lors de la modification du Skill.',
    'skills-categories-lang-added': 'La nouvelle langue a bien été ajoutée.',
    'skills-categories-error-adding-lang': 'Une erreur s\'est produite lors de l\'ajout de la langue',

    // InfoMessage
    'cat-deleted': 'Le thème "{cat}" a été supprimé.',
    'error-deleting-cat': 'Un problème est survenu lors de la suppression du thème "{cat}".',
    'skill-deleted': 'Le Skill "{skill}" a été supprimé.',
    'error-deleting-skill': 'Un problème est survenu lors de la suppression du Skill "{skill}".',

    // WhasqsList
    'whasqs-title': 'Whasqs',
    'block-whasq-confirm-message': 'Etes-vous sûr(e) de vouloir bloquer ce whasq ?',
    'unblock-whasq-confirm-message': 'Etes-vous sûr(e) de vouloir débloquer ce whasq ?',
    'ban-user-confirm-message': 'Etes-vous sûr(e) de vouloir bannir cette personne ?',
    'unban-user-confirm-message': 'Etes-vous sûr(e) de vouloir réintégrer cette personne dans la communauté ?',
    'remove-whasq-confirm-message': 'Etes-vous sûr(e) de vouloir supprimer ce whasq ?',
    'add-whasq': 'Ecrire un Whasq ',
    'whasqs-list': 'Liste ded Whasqs',
    'whasqs-column-id': 'Id',
    'whasqs-column-creation': 'Créé le',
    'whasqs-column-update': 'Mis à jour le',
    'whasqs-column-title': 'Thème',
    'whasqs-column-status': 'Statut',
    'whasqs-column-urgent': 'Urgent',
    'whasqs-column-answers': 'Réponses',
    'whasqs-column-read': 'Lus',
    'whasqs-column-creator': 'Auteur',
    'whasqs-column-skills': 'Skills',
    'whasqs-column-actions': 'Actions',
    'whasqs-column-type': 'Type de Whasq',
    'whasq-resolved-by': 'Résolu par',
    'whasq-resolved-at': 'le',
    'whasq-resolved': 'Résolu',
    'whasq-not-resolved': 'Non résolu',
    'whasq-archived': 'Archivé',
    'whasqs-action-save-updates': 'Sauvegarder les modifications',
    'whasqs-action-edit-whasq': 'Modifier le whasq',
    'whasqs-action-unblock-whasq': 'Débloquer le whasq',
    'whasqs-action-block-whasq': 'Bloquer le whasq',
    'whasqs-action-see-whasq-channel': 'Voir la discussion du whasq',
    'whasqs-action-unban-user': 'Réintégrer la personne',
    'whasqs-action-ban-user': 'Bannir la personne',
    'whasqs-action-remove-whasq': 'Supprimer le whasq',
    //'whasqs-notify-around': 'Notifier autour',
    'whasqs-language': 'Langue',
    'whasqs-list-reported-filter': 'Signalés',
    'whasqs-list-all-filter': 'Tous',
    'whasqs-list-training-filter': 'Type de whasqs',
    'whasqs-list-training': 'Whasqs de validation',
    'whasqs-list-not-training': 'Whasqs d\'entraide collaborative',
    'whasqs-list-add-btn': 'Ajouter',
    'whasqs-list-add-whasq-success': 'Votre Whasq a bien été créé',
    'whasqs-community': 'Entraide collaborative',
    'whasqs-training': 'Validation',
    'whasqs-user-locked': 'User Bloqué',

    // WhasqChannelModal
    'whasq-channel-title': 'Chaîne de discussion',
    'usefull-answer': 'utile(s)',
    'champion-answer': 'Ingenieux (se) !',
    'whasq-channel-edit-whasq-title': 'Thème',
    'whasq-channel-edit-whasq-message': 'Mon Message/Ma question',
    'whasq-channel-edit-answer-message': 'Mon Message/Ma question',
    'whasq-channel-block-answer-confirm': 'Etes vous sûr(e) de vouloir bloquer cette réponse ?',
    'whasq-channel-unblock-answer-confirm': 'Etes vous sûr(e) de vouloir débloquer cette réponse ?',
    'whasq-channel-delete-answer-confirm': 'Etes vous sûr(e) de vouloir supprimer cette réponse ?',
    'whasq-channel-modal-unblock-answer': 'Débloquer la réponse',
    'whasq-channel-modal-block-answer': 'Bloquer la réponse',
    'whasq-channel-modal-delete-answer': 'Supprimer la réponse',

    // AddWhasqModal
    'add-whasq-title': 'Ajouter un nouveau whasq',
    'add-whasq-item-title': 'Thème *',
    'add-whasq-item-message': 'Posez votre question *',
    'add-whasq-item-import': 'Importez un fichier ou déposez le ici ',
    'add-whasq-item-exchange': 'Troc ?',
    'add-whasq-item-optionnal': 'Optionnel',
    'add-whasq-item-channel': 'Dans quelle langue ?',
    'add-whasq-item-skills': 'Skills recherchés  ? * (3 maximum)',
    'add-whasq-item-urgent': 'Vite, c\'est urgent !',
    'add-whasq-item-send-everyone': 'Envoyer ce Whasq à tout le monde',
    'add-whasq-skill-required': 'Vous devez ajouter au moins un skill recherché.',
    'add-whasq-title-required': 'Vous devez renseigner le thème.',
    'add-whasq-message-required': 'Vous devez poser une question et/ou ajouter un fichier.',
    'add-whasq-modal-drop-file': 'Déposez ici votre fichier ou sélectionnez le depuis votre bureau',
    'add-whasq-modal-file-type': 'Fichiers acceptés de type image, audio, vidéo ou Microsoft Office',
    'add-whasq-modal-file-size': 'Votre fichier doit avoir une taille inférieure à 1Mo',
    'add-whasq-modal-error-importing-file': 'Une erreur s\'est produite lors de l\'import du fichier',
    'add-whasq-modal-import-file': 'Importez votre fichier',
    'add-whasq-modal-media-attachment-no-preview': 'Aucune prévisualisation disponible',
    'add-whasq-modal-change-attachment': 'Changer votre média',
    'add-whasq-modal-add': 'Ajouter',

    // Answers
    'answers-title': 'Réponses',
    'answers-unblock-answer-confirm-message': 'Etes-vous sûr(e) de vouloir débloquer cette réponse ?',
    'answers-block-answer-confirm-message': 'Etes-vous sûr(e) de vouloir bloquer cette réponse ?',
    'answers-unban-user-confirm-message': 'Etes-vous sûr(e) de vouloir réintégrer cette personne ?',
    'answers-ban-user-confirm-message': 'Etes-vous sûr(e) de vouloir bannir cette personne ?',
    'answers-remove-answer-confirm-message': 'Etes-vous sûr(e) de vouloir supprimer cette réponse ?',
    'answers-list': 'Liste des réponses',
    'answers-column-id': 'Id',
    'answers-column-creation': 'Créée le',
    'answers-column-last-update': 'Mise à jour le',
    'answers-column-message': 'Texte',
    'answers-column-usefull-count': 'likes obtenus',
    'answers-column-champion': 'Ingénieuse ?',
    'answers-column-creator': 'Auteur',
    'answers-column-reported-by': 'Signalée par',
    'answers-column-actions': 'Actions',
    'answers-action-save-updates': 'Sauvegarder les modifications',
    'answers-action-edit-answer': 'Editer la réponse',
    'answers-action-block-answer': 'Bloquer la réponse',
    'answers-action-unblock-answer': 'Débloquer la réponse',
    'answers-action-see-whasq-channel': 'Voir la discussion du Whasq',
    'answers-action-unban-user': 'Réintégrer la personne',
    'answers-action-ban-user': 'Bannir le collaborateur',
    'answers-action-remove-answer': 'Supprimerla réponse',
    'answers-reported-filter': 'Signalées',
    'answers-all-filter': 'Toutes',

    // Users
    'users-title': 'Mes collaborateurs',
    //'helper-filter-roles-title': 'Filtrer les collaborateurs selon le rôle', 
    //'helper-filter-roles-message': 'Applique le filtre sur le rôle choisi', 
    //'helper-user-status-title': 'Filtrer les collaborateurs selon leur status', 
    //'helper-user-status-message': 'Applique le filtre sur le statut choisi', 
    'users-ban-confirm-message': 'Etes-vous sûr(e) de vouloir bannir cette personne?',
    'users-unban-confirm-message': 'Etes-vous sûr(e) de vouloir réintégrer cette personne ?',
    //'users-archive-confirm-message': 'Etes-vous sûr(e) de vouloir archiver ce collaborateur ?',
    'users-add': 'Ajouter manuellement',
    'users-import-csv': 'Importer un fichier CSV',
    //'users-list': 'Liste de personnes inscrites',
    'users-column-id': 'Id',
    'users-column-register-date': 'Inscription le',
    'users-column-last-connection': 'Dernière connexion le',
    'users-column-avatar': 'Photo',
    'users-column-fullname': 'Nom et prénom',
    'users-column-title': 'Métier',
    'users-column-email': 'Email',
    'users-column-actions': 'Actions',
    'users-column-role': 'Rôle',
    'users-column-manager': 'Manager',
    'users-column-status': 'Statut',
    'users-action-see-profile': 'Voir le profil',
    'users-action-unban-user': 'Réintégrer la personne',
    'users-action-ban-user': 'Bannir la personne ',
    //'users-action-archive-user': 'Archiver un collaborateur',
    //'users-import-starting': 'L\'import de votre fichier a bien débuté',
    //'users-action-consider-user-admin': 'Considérer ce collaborateur comme étant admin',
    //'users-action-stop-consider-user-admin': 'Ne plus considérer ce collaborateur comme étant admin',
    //'users-confirm-consider-admin': 'Etes-vous sûr de vouloir considérer ce collaborateur comme étant admin ?',
    //'users-confirm-dont-consider-admin': 'Etes-vous sûr de ne plus vouloir considérer ce collaborateur comme étant admin ?',
    //'users-action-consider-user-admin-success': 'Le collaborateur d\'id {userId} est maintenant administrateur.',
    //'users-action-stop-consider-user-admin-success': 'Le collaborateur d\'id {userId} n\'est maintenant plus administrateur.',
    'users-action-switch-role': 'Changer le rôle de ce collaborateur',
    //'users-column-geolocated': 'Géolocalisé',
    'error-file-format': 'Le format du fichier n\'est pas correct',
    'users-roles-filter': 'Rôles',
    'users-roles-filter-all': 'Tout le monde :-)',
    'users-roles-filter-user': 'Internes à votre organisation',
    'users-roles-filter-admin': 'Administrateur',
    'users-roles-filter-trainer': 'Formateur/trices',
    'users-actives-filter': 'Collaborateurs actifs',
    'users-actives-filter-all': 'Tout le monde',
    'users-actives-filter-actives': 'ACTIFS',
    'users-actives-filter-deleted': 'ARCHIVÉS',
    'users-sessions-count': 'Nombre de sessions de formation',
    'users-acquired-skills': 'Nombre total de Skills',
    'users-training-skills': 'Nombre de Skills liés à la formation',
    'users-role-TRAINEE': 'Stagiaires de formation',
    'users-role-TRAINER_INT': 'Formateurs internes',
    'users-role-TRAINER_EXT': 'Formateurs externes',
    'users-role-CONTACT_TC': 'Contacts O.F.',
    'users-role-ADMIN': 'Admin',
    'users-role-SUPER_ADMIN': 'Super Admin',
    'users-role-USER': 'Collaborateurs/trices',
    'users-user-created': 'Le/La collaborateur/trice a bien été ajouté',
    'users-imported': 'La liste de vos collaborateurs a bien été importée',
    'error-importing-users': 'Une erreur s\'est produite lors de l\'import de votre liste de collaborateurs.',

    // ImportUsersModal
    'users-import-title': 'Importer une liste de collaborateurs',
    'import-users-file-limit': 'Seuls les fichiers au format C.S.V. d\'une taille inférieure à 1Mo sont acceptés',
    'import-users-error': 'Une erreur est survenue lors de l\'import de votre fichier. Veuillez réessayer SVP.',
    'import-users-btn': 'Importer la liste de vos collaborateurs',
    'import-users-expected-format': 'Format attendu',
    'import-users-fullname': 'Nom et Prénom',
    'import-users-email': 'Email',
    'import-users-job-position': 'Métier',
    'import-users-phone': 'Téléphone Mobile',
    'import-users-download-exemple': 'Aide : Téléchargez un fichier exemple.',
    'import-users-instructions-part-1': '1. Utilisez l\'exemple téléchargé, complétez le en conservant l\'ordre des  4 colonnes ',
    'import-users-instructions-part-2': '2. Sauvegardez le fichier au format C.S.V (valeurs séparées par des point-virgules)',
    'import-users-err': 'Une erreur s\'est produite lors de l\'importation de votre fichier',

    // Targets
    //'targets-title': 'Objectifs & Gamification',
    //'targets-update-message': 'L\'objectif "{target}" a bien été mis à jour',
    //'targets-geoloc-perimeter-updated': 'Le périmètre de géolocalisation a bien été mis à jour',
    //'targets-points-atribution-updated': 'L\'attribution de points a bien été mise à jour',
    //'targets-target': 'Objectifs',
    //'targets-trimester': '3 mois',
    //'targets-bimester': '6 mois',
    //'targets-year': '12 mois',
    //'targets-active-users': 'collaborateurs actifs',
    //'targets-geoloc-perimeter': 'Périmètre de géolocalisation',
    //'targets-perimeter': 'Périmètre',
    //'targets-gamification': 'Gamification',
    //'targets-approved-answer': 'Réponse approuvée',
    //'targets-usefull-answer': 'Réponse utile',
    //'targets-recommended-skill': 'Savoir recommandé',
    //'targets-points': 'points',

    // Header
    'header-profile': 'Mon profil',
    'header-logout': 'Me déconnecter',
    'french': 'Français',
    'english': 'Anglais',
    'spanish': 'Espagnol',
    'italian': 'Italien',
    'russian': 'Russe',
    'portuguese': 'Portugais',
    'header-choose-lang': 'Choisissez la langue',
    'header-french': 'Français',
    'header-spanish': 'Español',
    'header-english': 'English',
    'header-italian': 'Italiano',
    'header-portuguese': 'Português',
    'header-russian': 'русский',

    // Sidebar
    'sidebar-navigation': 'Menu',
    'sidebar-dashboard': 'Mon dashboard',
    'sidebar-my-kpis': 'Mes chiffres clés',
    'sidebar-my-skills-kpis': 'Mes Infos Skills',
    'sidebar-time-savings-kpis': 'KPI gain de temps',
    'sidebar-training-lab': 'Lab\' Formation',
    'sidebar-my-users': 'Mes collaborateurs',
    'sidebar-skills-management': 'Ma base de données de Skills',
    'sidebar-my-training-centers': 'Mes Organisme de Formation.',
    'sidebar-my-training-references': 'Mon catalogue de formations',
    'sidebar-my-trainings': 'Mes sessions de formation',
    'sidebar-my-interns': 'Mes stagiaires formation',
    'sidebar-my-community': 'Ma communauté',
    'sidebar-search': 'Trouvez des skills',
    'sidebar-active-users': 'Infos Whasqers actifs',
    //'sidebar-whasqs-answers': 'Whasqs et réponses',
    'sidebar-podium': 'Podium',
    'sidebar-platform-activity': 'Flux des Whasqs',
    'sidebar-whasqs': 'Les Whasqs',
    'sidebar-answers': 'Les Réponses',

    // Profile
    'profile': 'Mon Profil',
    'profile-title': 'Profil du collaborateur',
    'profile-ranking-position': 'Position de l\'utilisateur dans le classement',
    'profile-whasqs-sent': 'Whasqs envoyés',
    'profile-answers-sent': 'Réponses données',
    'profile-my-training-reporting': 'Mon suivi formation',
    'profile-his-training-reporting': 'Son suivi formation',
    'profile-my-skills-title': 'Mes Skills',
    'profile-his-skills-title': 'Ses Skills',
    'profile-my-channels-title': 'Mes langues',
    'profile-his-channels-title': 'Ses langues',
    'profile-skills-add': 'Ajouter',
    'profile-trainings-count': 'Nombre de formations suivies',
    'profile-success-rate': 'Taux de réussite (global) ',
    'profile-skills-count': 'Nombre de skills',
    'profile-training-whasqs': 'Whasqs Validation en attente',
    'profile-channels-add': 'Ajouter',
    'profile-edit-label': 'Modifier',
    'profile-save-label': 'Sauvegarder',
    'profile-image-size-limit': 'Seuls les fichiers image d\'une taille inférieure à 1Mo sont acceptés.',
    'profile-image-square-required': 'Conseil : Votre photo doit avoir un format carré.',
    'import-profile-image': 'Importer votre photo ',
    'pick-profile-avatar': 'Timide ? Choisissez votre avatar',
    'profile-delete-channel-confirm': 'Etes-vous sûr(e) de vouloir supprimer la langue "{channelName}" ?',
    'profile-delete-last-channel-impossible': 'Désolé, vous devez choisir au moins une langue pour compléter votre profil.',
    'profile-channel-removed': 'La langue {channelName} a bien été supprimée.',
    'profile-delete-skill-confirm': 'Etes-vous sûr(e) de vouloir supprimer le skill "{skillName}" ?',
    'profile-skill-removed': 'Le skill "{skillName}" a bien été supprimé.',
    'profile-error-removing-skill': 'Une erreur s\'est produite lors de la suppression du savoir "{skillName}".',
    'profile-error-updating-gdpr': 'Une erreur s\'est produite lors de la modification de la visibilité RGPD.',
    'profile-error-updating-user': 'Une erreur s\'est produite lors de la modification de l\'utilisateur.',
    'profile-user-updated': 'L\'utilisateur a bien été modifié.',
    'profile-error-getting-available-skills': 'Une erreur s\'est produite lors de la récupération des savoirs disponibles.',
    'profile-skill-added': 'Le talent a bien été ajouté.',
    'profile-error-adding-skill': 'Une erreur s\'est produite lors de l\'ajout du savoir',
    'profile-error-getting-available-channels': 'Une erreur s\'est produite lors de la récupération des langues disponibles',
    'profile-channel-added': 'La langue {channelName} a bien été ajoutée.',
    'profile-error-adding-channel': 'Une erreur s\'est produite lors de l\'ajout de la langue',
    'profile-training-trace': 'Mon activité formation',
    'profile-collaborative-trace': 'Mon activité collaborative',
    'profile-whasqs-count': 'Whasqs envoyés',
    'profile-answers-count': 'rRponses données',
    'profile-likes-count': 'likes reçus',
    'profile-solutions-count': 'Solutions trouvées',
    'profile-trainings-name-col': 'Formation',
    'profile-trainings-start-col': 'Début',
    'profile-trainings-remaining-days-col': 'Jours restants',
    'profile-trainings-skills-col': 'Skills acquis',
    'profile-participation-rate': 'Taux de participation',
    'profile-mean-success-rate': 'Taux de réussite moyen',
    'profile-evolution-rate': 'Evolution avant/après la formation',
    'profile-training-planned': '(à venir)',
    'profile-email-not-available': 'L\'email n\'est pas visible',
    'profile-phone-not-available': 'Le numéro de téléphone mobile n\'est pas visible',
    'profile-job-position-not-available': 'Le métier n\'est pas visible',
    'profile-place-not-available': 'Le lieu de travail n\'est pas visible',
    'profile-fixed-line-phone-not-available': 'Le numéro de téléphone fixe n\'est pas visible',
    'profile-manager-not-available': 'Le nom du manager n\'est pas visible',
    'profile-manager-label': 'Mon Manager :',
    'profile-add-manager': 'Ajouter un manager',
    'profile-set-manager-succeeded': 'Le nom de votre manager {fullname} a bien été ajouté.',
    'profile-set-manager-failed': 'Une erreur s\'est produite lors de l\'ajout du manager',
    'profile-no-skill': 'Aucun Skill n\'est renseigné',
    'profile-no-channel': 'Aucune langue n\'est renseignée',
    'profile-stat-consult': 'Consulter',

    // AddUserSkillModal
    'add-user-skill-title': 'Ajout d\'un Skill',
    'add-user-skill-subtitle': 'Ne soyez pas modeste ! Vous avez sûrement d\'autres Skills, Ajoutez-les !',
    'add-user-skill-suggest': 'Il manque un skill dans la liste ?',

    // AddUserChannelModal
    'add-user-channel-title': 'Ajouter une langue',
    'add-user-channel-subtitle': 'Sélectionnez les langues que vous pratiquez',

    // SuperAdminStores
    'store-selection': 'Choix de l\'espace client',
    'store-choice-validation': 'Valider le choix de l\'espace client',

    // StoreLogoUpload
    'choose-company-logo': 'Personnalisez les pages avec le logo de votre société',
    'drop-file-here-or-click': 'Déposez votre fichier ici ou cliquez pour sélectionner le fichier à importer.',
    'company-logo-size-limit': 'Seuls les fichiers images d\'une taille inférieure à 1Mo sont acceptés.',
    'company-logo-square-required': 'L\'image doit avoir un format carré.',
    'error-importing-company-logo': 'Une erreur est survenue lors de l\'import de l\'image. Veuillez réessayer SVP.',
    'import-company-logo': 'Importez votre logo',

    // Notifications
    'notifications-title': 'Notifications',
    'notifications-list': 'Liste des notifications',
    'notifications-column-id': 'Id',
    'notifications-column-type': 'Type',
    'notifications-column-data': 'Données',
    'notifications-column-owner': 'Propriétaire',
    'notifications-column-shared': 'Partagé ?',
    'notifications-column-creation': 'Crée le',
    'notifications-column-message': 'Message',
    'notifications-no-data': 'Vous n\'avez actuellement aucune notification',

    // TrainingCenters
    'training-centers-id-col': 'Id',
    'training-centers-title': 'Mes organismes de formation',
    'training-centers-add-btn': 'Ajouter manuellement un O.F.',
    'training-centers-not-defined': 'Aucun organisme de formation n\'est créé à ce jour. Ajoutez-en un.',
    'training-centers-archive-confirm': 'Etes-vous sûr(e) de vouloir archiver cet organisme de formation ?',
    'training-centers-name-col': 'Nom de l\'OF',
    'training-centers-url-col': 'Url',
    'training-centers-training-ref-count-col': 'Nbre de formations', 
    'training-centers-training-count-col': 'Nbre de sessions', 
    'training-centers-respondents-count-col': 'Nbre de stagiaires',
    'training-centers-date-col': 'créée le',
    'training-centers-success-rate-col': 'Taux de réussite',
    'training-centers-actions-col': 'Actions',
    'helper-training-tutorial-title': 'Tutoriel d\'utilisation',
    'helper-training-tutorial-message': 'La vidéo est en cours de création. En attendant, si vous avez une question, contactez nous sur jessie@whasq.com .',
    'training-center-action-show-trainings' : 'Voir les formations de cet OF ',
    'training-center-action-no-trainings': 'Cet OF n\'a aucune formation rattachée pour l\'instant',
    'training-centers-import-btn': 'Importer un fichier CSV',
    'training-centers-recommendation-rate-col': 'Taux de recommandation',
    'training-centers-acquired-skills-col': 'Nombre moyen de Skills acquis par les stagiaires',
    'training-centers-update': 'Modifier l\'OF',
    'training-centers-reporting': 'Accèder au reporting de l\'OF',
    'training-centers-archive': 'Archiver l\'OF',

    // Trainings
    'trainings-id-col': 'Id', 
    'trainings-state-col': 'Statut', 
    'trainings-title': 'Mes sessions de formations',
    'trainings-add-btn': 'Ajouter manuellement une formation',
    'trainings-import-btn': 'Importer un fichier CSV de formation',
    'trainings-name-col': 'Nom de la formation',
    'trainings-level-col': 'Niveau',
    'trainings-training-center-col': 'Nom de l\'OF',
    'trainings-start-col': 'Début',
    'trainings-end-col': 'Fin',
    'trainings-recommendation-rate-col': 'Taux de recommandation',
    'trainings-acquired-skills-col': 'Nb de skills acquis',
    'trainings-support-end-col': 'Date du Bilan ',
    'trainings-trainers-count-col': 'Nbre de formateurs',
    'trainings-participants-count-col': 'Nbre de stagiaires',
    'trainings-whasqs-count-col': 'Nbre de Whasqs',
    'trainings-remaining-days-col': 'Nbre de jours restants',
    'trainings-success-rate-col': 'Taux de réussite',
    'trainings-language-col': 'Langue',
    'trainings-respondents-count-col': 'Nbre de répondants',
    'trainings-actions-col': 'Actions',
    'trainings-not-defined': 'Aucune session de formation n\'est programmée à ce jour. Crééez en une !.',
    'trainings-no-with-search': 'Aucune session de formation ne correspond à votre recherche. Ajoutez la !',
    'trainings-archive-confirm': 'Etes-vous sûr(e) de vouloir archiver cette session de formation ?',
    'trainings-action-plan': 'Planifier les réponses',
    'trainings-action-update': 'Modifier la session de formation',
    'trainings-action-duplicate': 'Dupliquer la session de formation',
    'trainings-action-reporting': 'Accèder au reporting de la session de formation',
    'trainings-action-evaluation': 'Accèder à l\'évaluation de la session de formation',
    'trainings-action-no-evaluation': 'Aucune évaluation pour le moment',
    'trainings-action-archive': 'Archiver la session de formation',
    'trainings-whasqs-count-insufficient': '⚠ Vous ne pouvez pas voir le planning des questions si vous n\'avez pas programmé au moins 10 questions.',
    'trainings-confirm-duplicate': 'Etes-vous sûr(e) de vouloir dupliquer cette session de formation ?',
    'trainings-training-center-filter': 'Filtrer par organisme de formation',
    'trainings-training-center-filter-all': 'TOUS',
    'trainings-training-reference-filter': 'Filtrer par formation',
    'trainings-training-reference-filter-all': 'TOUTES',

    // AddTrainingCenterModal
    'add-training-center-modal-title': 'Ajouter un organisme de formation',
    'add-training-center-modal-title-edit': 'Modification de l\'organisme de formation{br}"{name}"',
    'add-training-center-modal-desc-tab': 'Description',
    'add-training-center-modal-trainers-tab': 'Contact administratif de l\'OF',
    'add-training-center-modal-name': 'Nom de l\'OF',
    'add-training-center-modal-url': 'Site web',
    'add-training-center-modal-validate': 'Créer l\'OF',
    'add-training-center-modal-validate-update': 'Modifier l\'OF',
    'add-training-center-modal-col-name': 'Nom  et prénom du contact',
    'add-training-center-modal-col-email': 'Email',
    'add-training-center-modal-col-job': 'métier',
    'add-training-center-modal-col-actions': 'Actions',
    'add-training-center-modal-delete-trainer-confirm': 'Etes-vous sûr de vouloir supprimer le contact de cet organisme de formation ?',
    'add-training-center-modal-update-successful': '👍 L\'organisme de formation "{name}" a bien été mis à jour !',
    'add-training-center-modal-insert-successful': '👍 L\'organisme de formation "{name}" a bien été créé !',
    'add-training-center-modal-trainer-deleted': '👍 L\'email "{email}" du contact administratif de cet organisme de formation a bien été supprimé .',
    'add-training-center-modal-trainer-added': '👍 L\'email "{email}" du contact a bien été ajouté à cet organisme de formation.',
    'add-training-center-modal-activation-link-trainer-sent': 'Un lien d\'activation vient d\'être envoyé au contact administratif de l\'OF',
    'add-training-center-close-confirm': 'Etes-vous sûr(e) de vouloir quitter cet écran sans enregistrer ?',

    // AddTrainerModal
    'add-trainer-modal-training-center-title': 'Ajouter un contact administratif à l\'organisme de formation',
    'add-trainer-modal-training-title': 'Ajouter un formateur à la session de formation',
    'add-trainer-modal-participant-title': 'Ajouter un participant à la session de formation',
    'add-trainer-modal-trainer-email': 'Email du contact administratif',
    'add-trainer-modal-participant-email': 'Email du futur stagiaire',
    'add-trainer-modal-no-matched-trainer': 'Aucun formateur ne correspond à l\'email renseigné',
    'add-trainer-modal-validate': 'Valider',
    'add-trainer-modal-email-invalid': 'L\'adresse email n\'est pas correcte ou valide',
    'add-trainer-modal-grant-user-confirm': 'Vous êtes sur le point de donner le rôle contact administratif à un de vos collaborateurs. Etes-vous sûr(e) de vouloir continuer ?',
    'add-trainer-modal-at-least-three': 'Veuillez taper au moins 3 caractères pour lancer la recherche parmi les collaborateurs déjà inscrits.',
    'add-trainer-modal-external-trainer': 'Si votre formateur est externe à votre organisation, écrivez l\'email complet. Une invitation mail lui sera envoyée.',

    // AddTrainingModal
    'add-training-modal-title': 'Ajouter une session de formation',
    'add-training-modal-edit-title': 'Ajout d\'une session de formation',
    'add-training-modal-desc-tab': 'Informations générales',
    'add-training-modal-trainers-tab': 'Formateur',
    'add-training-modal-participants-tab': 'Stagiaires',
    'add-training-modal-memory-quiz-tab': 'Quiz mémoriel',
    'add-training-modal-levels-tab': 'Niveaux de difficulté',
    'add-training-modal-training-reference': 'Infos Formation',
    'add-training-modal-start': 'Début',
    'add-training-modal-end': 'Fin',
    'add-training-modal-pro-assessment-starts-at': 'Positionnement',
    'add-training-modal-pro-assessment-starts-at-placeholder': 'Cliquez ici...',
    'add-training-modal-end-support': 'Bilan Final',
    'add-training-modal-start-placeholder': 'Cliquez ici...',
    'add-training-modal-end-placeholder': 'Cliquez ici...',
    'add-training-modal-time': 'Heure',
    'add-training-modal-validate': 'Valider',
    'add-training-modal-trainers-name-col': 'Nom',
    'add-training-modal-trainers-email-col': 'Email',
    'add-training-modal-trainers-job-col': 'Métier',
    'add-training-modal-trainers-actions-col': 'Actions',
    'add-training-modal-add-trainer-btn': 'Ajouter un formateur',
    'add-training-modal-add-participant-btn': 'Ajouter un futur stagiaire',
    'add-training-modal-import-participant-btn': 'Importer un fichier CSV de stagiaires',
    'add-training-modal-participants-name-col': 'Nom',
    'add-training-modal-participants-email-col': 'Email',
    'add-training-modal-participants-job-col': 'Métier',
    'add-training-modal-participants-actions-col': 'Actions',
    'add-training-modal-add-question-btn': 'Ajouter',
    'add-training-modal-edit-question-planning-btn': 'Planning',
    'add-training-modal-quiz-question-number-col': 'N°', 
    'add-training-modal-quiz-index-col': 'Id',
    'add-training-modal-quiz-question-col': 'Thème de la question',
    'add-training-modal-quiz-type-col': 'Type',
    'add-training-modal-quiz-scheduled-col': 'Envoyée le',
    'add-training-modal-quiz-level-col': 'Niveau',
    'add-training-modal-quiz-actions-col': 'Actions',
    'add-training-modal-delete-question-confirm': 'Etes-vous sûr(e) de vouloir supprimer cette question ?',
    'add-training-modal-delete-participant-confirm': 'Etes-vous sûr(e) de vouloir supprimer ce stagiaire ?',
    'add-training-modal-delete-trainer-confirm': 'Etes-vous sûr de vouloir supprimer ce formateur ?',
    'add-training-modal-level-lvl-col': 'Niveau',
    'add-training-modal-level-label-col': 'Label',
    'add-training-modal-level-succes-threshold-col': 'Taux de réussite attendu',
    'add-training-modal-level-actions-col': 'Actions',
    'add-training-modal-remove-lvl-confirm': 'Etes-vous sûr(e) de vouloir supprimer ce niveau ?',
    'add-training-modal-add-lvl-btn': 'Ajouter',
    'add-training-modal-add-question-no-level': 'Vous devez ajouter des niveaux avant de créer vos questions 😉',
    'add-training-modal-training-center': 'Organisme de formation',
    'add-training-modal-quiz': 'Quiz',
    'add-training-modal-bad-mode-configuration': 'Mauvaise configuration des options',
    'add-training-modal-has-preassessment': 'Positionnement',
    'add-training-modal-has-assessment': 'Validation',
    'add-training-modal-has-evaluation': 'Evaluation',
    'add-training-modal-training-center-placeholder': 'Choisissez votre organisme de formation ! 😃',
    'add-training-modal-training-reference-placeholder': 'Choisissez votre formation ! 😃',
    'add-training-modal-missing-field': 'Le champs "{field}" est requis. Merci de le compléter pour pouvoir créer la session de formation 😉',
    'add-training-modal-invalid-field': 'Le champs "{field}" est incorrect. Merci de le corriger pour pouvoir créer la session de formation 😉',
    'add-training-modal-insert-successfull': 'La session de formation a bien été créée ! 😃',
    'add-training-modal-error-insert': 'Une erreur s\'est produite lors de la création de la session de formation.',
    'add-training-modal-update-successfull': 'La session de formation a bien été mise à jour ! 😃',
    'add-training-modal-error-updating': 'Une erreur s\'est produite lors de la modification de la session de formation.',
    'add-training-modal-trainer-added': 'Le formateur a bien été ajouté à la session de formation ! 😃',
    'add-training-modal-trainer-invited': 'Le formateur a bien été invité à cette session de formation ! 😃',
    'add-training-modal-trainer-deleted': 'Le formateur a bien été retiré de la session de formation ! 😃',
    'add-training-modal-participant-added': 'Le stagiaire a bien été ajouté à la session de formation ! 😃',
    'add-training-modal-participant-invited': 'Le stagiaire a bien été invité pour cette session de formation ! 😃',
    'add-training-modal-participant-deleted': 'Le stagiaire a bien été retiré de la session de formation ! 😃',
    'add-training-modal-level-added': 'Le niveau {level} a bien été ajouté ! 😃',
    'add-training-modal-level-updated': 'Le niveau {level} a bien été modifié ! 😃',
    'add-training-modal-level-deleted': 'Le niveau {level} a bien été supprimé ! 😃',
    'add-training-modal-question-deleted': 'La question a bien été supprimée ! 😃',
    'add-training-modal-minimum-whasqs': 'Hey :-), Vous devez ajouter au moins 10 questions à la session de formation',
    'add-training-modal-qcm': 'Choix multiple',
    'add-training-modal-qcu': 'Choix unique',
    'add-training-modal-planification-tab': 'Planning',
    'add-training-modal-update-impossible': 'La modification n\'est pas possible car le process de validation a débuté.',
    'add-training-modal-pending': 'En attente...',
    'add-training-close-confirm': 'Etes-vous sûr(e) de vouloir quitter sans enregistrer ?',
    'add-training-modal-insufficient-rights': 'Vous n\'êtes pas autorisé(e) à réaliser cette action.',
    'add-training-modal-switch-whasq-position-success': 'L\'ordre des questions a bien été modifiée',
    'add-training-modal-action-duplicate': 'Dupliquer la question',
    'add-training-modal-action-update': 'Modifier la question',
    'add-training-modal-action-see': 'Voir la question',
    'add-training-modal-action-delete': 'Supprimer la question',
    'add-training-modal-previous-month': 'Mois précédent',
    'add-training-modal-next-month': 'Mois suivant',
    'add-training-modal-support-start': 'Début de la validation',
    'add-training-modal-support-end': 'Fin de la validation',

    // AddQuestionModal
    'add-question-modal-title': 'Ajouter une question au quiz',
    'add-question-modal-duplicate-title': 'Dupliquer une question',
    'add-question-modal-edit-title': 'Editer d\'une question du quiz',
    'add-question-modal-type': 'Type de question',
    'add-question-modal-options': 'Liste des réponses',
    'add-question-modal-qcm': 'Question à choix multiples',
    'add-question-modal-qcu': 'Question à choix unique',
    'add-question-modal-open': 'Question ouverte',
    'add-question-modal-add-option': 'Ajoutez une réponse',
    'add-question-modal-whasq-title': 'Thème de votre question',
    'add-question-modal-whasq-message': 'Posez votre question',
    'add-question-modal-save': 'Enregistrez la question',
    'add-question-modal-option-label-col': 'Écrivez une réponse',
    'add-question-modal-option-solution-col': 'C\'est une solution',
    'add-question-modal-option-explanation-col': 'Ajoutez une explication,visible lorsque le stagiaire aura répondu',
    'add-question-modal-option-order-col': 'Ordre des réponses',
    'add-question-modal-option-actions-col': 'Actions',
    'add-question-modal-explanations': 'Ajoutez une explication,visible lorsque le stagiaire aura répondu',
    'add-question-modal-level': 'Niveau',
    'add-question-modal-whasq-media': 'Media',
    'add-question-modal-import-drop-here': 'Déposez ici votre média ou téléchargez le depuis votre bureau.',
    'add-question-modal-import-size-limit': 'La taille maximale du fichier est 1Mo',
    'add-question-modal-error-importing-file': 'Une erreur s\'est produite lors de l\'import du fichier.',
    'add-question-modal-import-file-button': 'Importer le fichier',
    'add-question-modal-skills': 'Skill (1 maximum)',
    'add-question-modal-skill': 'Skill',
    'add-question-modal-skills-add': 'Ajouter',
    'add-question-modal-media-attachment-no-preview': 'Aucune prévisualisation possible',
    'add-question-modal-change-attachment': 'Changer de fichier',
    'add-question-modal-delete-option-confirm': 'Etes-vous sûr(e) de vouloir supprimer cette réponse ?',
    'add-question-modal-missing-title': 'Le thème de la question est obligatoire',
    'add-question-modal-missing-message-or-media': 'Vous devez poser au moins une question pour valider le formulaire',
    'add-question-modal-missing-skill': 'Au moins un Skill est nécessaire  pour valider le formulaire',
    'add-question-modal-missing-options': 'Au moins deux choix de réponses doivent être renseignées',
    'add-question-modal-missing-assert-options': 'Choisissez au moins une solution parmi les réponses',
    'add-question-modal-qcu-bad-assert-options': 'Oups ! Votre questionnaire est à choix unique, vous ne devez avoir qu\'une seule solution parmi les réponses',
    'add-question-modal-options-all-assert-confirm': ' Incroyable ! Tous les réponses sont des solutions. Etes-vous sûr(e) de vouloir valider cela ?',
    'add-question-modal-close-confirm': 'Voulez-vous quitter sans enregistrer ?',
    'add-question-modal-switch-options-position-success': 'L\'ordre des réponses a bien été modifié',
    'add-question-modal-action-edit': 'Modifier la question',
    'add-question-modal-action-delete': 'Supprimer la question',

    // AddTrainingSkillModal
    'add-training-skill-modal-title': 'Ajouter un Skill à la session de formation',
    'add-training-skill-modal-suggest': 'Un Skill est manquant ? Demandez à votre administrateur de l\'ajouter :-)',

    // EditPlanningModal
    'edit-planning-modal-title': 'Planification des questions',
    'edit-planning-modal-legend-title': 'Légende',
    'edit-planning-modal-legend-level': 'Niveau {level}',
    'edit-planning-modal-bad-date': 'Vous ne pouvez pas déplacer la planification de cette question à cette date. Veuillez la modifier. 😉',
    'edit-planning-modal-too-many-events': 'Vous ne pouvez pas planifier plus de 2 questions le même jour.',

    // AddLevelModal
    'add-level-modal-title': 'Ajouter le niveau {level}',
    'add-level-modal-edit-title': 'Edition du niveau {level}',
    'add-lvl-modal-label': 'Titre du niveau', 
    'add-lvl-modal-success-treshold': 'Taux de réussite attendu (en %)',
    'add-lvl-modal-validate-btn': 'Valider',
    'add-level-modal-fields-required': 'Merci de compléter tous les champs pour pouvoir valider ce formulaire.',
    'add-lvl-modal-helper': 'Un niveau est une indication de la difficulté de vos questions.', // todo

    // PlanQuestionModal
    'plan-question-modal-title': 'Planifier une question le {date}',
    'plan-question-modal-move-question-title': 'Déplacer la question {question} au {date}',
    'plan-question-modal-move-question-title-unknown-date': 'Déplacer la question {question}',
    'plan-question-modal-plan-btn': 'Planifier',
    'plan-question-modal-move-btn': 'Déplacer',
    'plan-question-modal-question': 'Question #{id}',
    'plan-question-modal-question-level': 'niveau {level}',
    'plan-question-modal-choose-question': 'Quelle question souhaitez-vous planifier ?',
    'plan-question-modal-prior-warning-confirm': '⚠ Attention ⚠\r\nVous ne pouvez pas planifier une question de difficulté {level} après une ou plusieurs questions de niveau supérieur.',
    'plan-question-modal-later-warning-confirm': '⚠ Attention ⚠\r\nVous ne pouvez pas planifier une question de difficulté {level} avant une ou plusieurs questions de niveau inférieur.',
    'edit-planning-modal-all-questions-planned': 'Toutes les questions sont planifiées 😃',
    'plan-question-modal-date-placeholder': 'Date de report',
    'plan-question-modal-select-move-date': 'Nouvelle date de planification',
    'plan-question-modal-question-title': 'Thème',
    'plan-question-modal-question-message': 'La question',
    'plan-question-modal-bad-date': 'Vous ne pouvez pas déplacer cette question à cette date. Veuillez la modifier. 😉',
    'plan-question-modal-update-question': 'Modifier la question',

    // AddQuestionSkillModal
    'add-question-skill-modal-title': 'Ajouter un Skill',
    'add-question-skill-modal-conditions': 'Vous pouvez ajouter jusqu\'à 3 Skills à cette question',

    // AddQuestionOptionModal
    'add-question-option-modal-title': 'Ajouter une réponse',
    'add-question-option-modal-title-update': 'Editer une réponse',
    'add-question-option-modal-label': 'Réponse',
    'add-question-option-modal-assert': 'Solution ?',
    'add-question-option-modal-explanation': 'Explication ?',
    'add-question-option-modal-add': '+ Ajouter',
    'add-question-option-modal-update': 'Editer',
    'add-question-option-modal-solution-ever-defined': '(une réponse est déjà définie comme solution de la question)',
    'add-question-option-modal-error': 'Merci de renseigner au moins une réponse pour pouvoir valider ce formulaire',

    // TrainingReporting
    'training-kpis-title': 'Chiffres clés',
    'training-kpis-updated-at': 'Mis à jour le {date} à {hours}h{minutes}',
    'training-reporting-no-data-title': 'Reporting : En cours de calcul ',
    'training-reporting-participants-count-kpi-title': 'Stagiaires inscrits à la session',
    'training-reporting-participants-count-help-title': 'Somme de tous les stagiaires inscrits à la session de formation ',
    'training-reporting-participants-count-help-message': ', ayant un compte validé ou non',
    'training-reporting-success-rate-pre-kpi-title': 'Taux de réussite de la session (avant formation)',
    'training-reporting-success-rate-pre-help-title': '% de bonnes réponses au questionnaire de positionnement',
    'training-reporting-success-rate-pre-help-message': 'Somme des bonnes réponses données au questionnaire de positionnement / Somme des réponses données) * 100',
    'training-reporting-success-rate-kpi-title': 'Taux de réussite de la session (après formation)',
    'training-reporting-success-rate-help-title': '% de bonnes réponses au questionnaire de validation',
    'training-reporting-success-rate-help-message': 'Somme des bonnes réponses données au Questionnaire de validation / Somme des réponses données au Questionnaire de validation * 100',
    'training-reporting-commitment-rate-kpi-title': 'Taux d\'engagement des stagiaires',
    'training-reporting-commitment-rate-help-title': '% des stagiaires ayant répondu au minimum à un questionnaire',
    'training-reporting-commitment-rate-help-message': 'Somme des stagiaires ayant répondu à au moins 1 questionnaire, avant formation ( positionnement), de satisfaction ou après formation ( validation) / Somme des stagiaires inscrits à la session de formation)*100',
    'training-reporting-satisfaction-rate-kpi-title': 'Taux de satisfaction de la session',
    'training-reporting-satisfaction-rate-help-title': '% des avis positifs des stagiaires suite à la formation',
    'training-reporting-satisfaction-rate-help-message': 'Somme des avis positifs (3 et/ou 4 étoiles données à la 1ère question du questionnaire de satisfaction)/ Somme des avis  du questionnaire de satisfaction reçus * 100',
    'training-reporting-attendance-rate-kpi-title': 'Taux de présence à la session',
    'training-reporting-attendance-rate-help-title': '% des stagiaires présents à cette session',
    'training-reporting-attendance-rate-help-message': 'Somme des stagiaires encore inscrits à la session, 1 jour après la fin de la formation / Somme des stagiaires inscrits à la session 1 jour avant son début * 100',
    'training-reporting-acquired-skills-participant-kpi-title': 'Nombre moyen de Skills acquis',
    'training-reporting-acquired-skills-participant-help-title': 'Permet de savoir combien de skills les stagiaires ont acquis grâce à la formation ',
    'training-reporting-acquired-skills-participant-help-message': 'Somme des Skills acquis / Somme des stagiaires  ayant répondu à 100% au Questionnaire de validation * 100',
    'training-reporting-acquired-skills-kpi-title': 'Skills Acquis',
    'training-reporting-acquired-skills-help-title': 'Somme de l\'ensemble des Skills acquis par les stagiaires',
    'training-reporting-acquired-skills-help-message': 'Somme des Skills par les stagiaires au cours de cette session',
    'training-reporting-levels-tab-title': 'Détails concernant les niveaux ({count})',
    'training-reporting-levels-tab-id-col': 'Id',
    'training-reporting-levels-tab-title-col': 'Thème',
    'training-reporting-levels-tab-whasqs-count-col': 'Nbre de whasqs',
    'training-reporting-levels-tab-participants-count-col': 'Nbre de stagiaires',
    'training-reporting-levels-tab-participants-giving-answers-count-col': 'Nbre de répondants',
    'training-reporting-levels-tab-participation-rate-col': 'Taux de participation',
    'training-reporting-levels-tab-success-rate-col': 'Taux de réussite',
    'training-reporting-whasqs-tab-title': 'Détails concernant les questions de validation ({count})',
    'training-reporting-whasqs-tab-id-col': 'Id',
    'training-reporting-whasqs-tab-skill-col': 'Skills',
    'training-reporting-whasqs-tab-title-col': 'Thème de la question',
    'training-reporting-whasqs-tab-users-pre-count-col': 'Positionnement : Répondants/Stagiaires inscrits',
    'training-reporting-whasqs-tab-success-rate-pre-col': 'Taux de réussite positionnement',
    'training-reporting-whasqs-tab-sent-on-col': 'Date d\'envoi Whasqs Validation',
    'training-reporting-whasqs-tab-users-count-col': 'Validation : Répondants/Stagiaires inscrits',
    'training-reporting-whasqs-tab-success-rate-col': 'Taux de réussite Validation',
    'training-reporting-users-tab-title': 'Détails concernant  concernant les stagiaires ({count})',
    'training-reporting-users-tab-fullname-col': 'Nom', 
    'training-reporting-users-tab-last-whasq-pre-col': 'Dernière réponse positionnement',
    'training-reporting-users-tab-whasqs-pre-count-col': 'Positionnement : Réponses données /Questions posées',
    'training-reporting-users-tab-success-rate-pre-col': 'Taux de réussite positionnement',
    'training-reporting-users-tab-last-whasq-col': 'Dernière réponse formation',
    'training-reporting-users-tab-whasqs-count-col': 'Validation',
    'training-reporting-users-tab-success-rate-col': 'Taux de réussite validation',
    'training-reporting-users-tab-acquired-skills-col': 'Nombre de Skills acquis',
    'training-reporting-users-tab-attendance-confirmation-col': 'A confirmé sa présence le',

    'training-reporting-skills-tab-title': 'Chiffres clés concernant les Skills ({count})',
    'training-reporting-skills-tab-id-col': 'Id',
    'training-reporting-skills-tab-name-col': 'Skill',
    'training-reporting-skills-tab-level-col': 'Niveau',
    'training-reporting-skills-tab-nb-whasqs-col': 'Nbre de questions',
    'training-reporting-skills-tab-participants-giving-answers-count-col': 'Nbre de répondants',
    'training-reporting-skills-tab-participation-rate-col': 'Taux de participation',
    'training-reporting-skills-tab-success-rate-col': 'Taux de réussite',

    // TrainingEvaluation
    'training-evaluation-title': 'Evaluation de session de formation',
    'training-evaluation-title-name': 'Evaluation de la session de formation "{name}"',
    'training-evaluation-title-participation': '(taux de participation {participationRate}%)',
    'training-evaluation-label-col': 'Label',  
    'training-evaluation-participants-count-col': 'Nbre de stagiaires ({count})', 
    'training-evaluation-participants-rate-col': '% de participants',  
    'training-evaluation-not-available': 'L\'évaluation de cette session de formation n\'est pas encore disponible', 
    'training-reporting-users-tab-answered-whasqs-rate-col': 'Taux de réponses', 
    'training-reporting-users-tab-last-answer-date-col': 'Date de la derniére réponse', 
    'training-reporting-users-tab-max-reached-level-col': 'Le niveau atteint',  
    
    // SwitchUserRoleModal
    'switch-user-role-modal-title': 'Changement de rôle pour le collaborateur "{name}"',
    'switch-user-role-modal-new-role': 'Ajouter un rôle au collaborateur :',
    'switch-user-role-modal-remove-role': 'Retirer un rôle au collaborateur :',
    'switch-user-role-modal-role-user': 'Collaborateur',
    'switch-user-role-modal-role-trainer': 'Formateur',
    'switch-user-role-modal-role-admin': 'Administrateur',
    'switch-user-role-modal-add': 'Ajouter',
    'switch-user-role-modal-remove': 'Supprimer',
    'switch-user-role-modal-current-roles': 'L\'utilisateur actuel possède le(s) rôle(s) suivant(s) :',
    'switch-user-role-modal-role-added': 'Le rôle "{role}" a bien été ajouté à ce collaborateur.',
    'switch-user-role-modal-error-adding-role': 'Une erreur s\'est produite lors de l\'ajout du rôle "{role}" à ce collaborateur.',
    'switch-user-role-modal-role-removed': 'Le rôle "{role}" a bien été retiré à ce collaborateur.',
    'switch-user-role-modal-error-removing-role': 'Une erreur s\'est produite lors du retrait du rôle "{role}" à ce collaborateur.',
    'switch-user-role-modal-manager-btn': 'Désigner ce collaborateur comme manager',
    'switch-user-role-modal-unset-manager-btn': 'Ne plus désigner ce collaborateur comme manager',
    'switch-user-role-modal-defining-manager-success': 'Le collaborateur est maintenant manager',
    'switch-user-role-modal-undefining-manager-success': 'Le collaborateur n\'est plus manager',
    'switch-user-role-modal-error-defining-manager': 'Une erreur s\'est produite lors de la définition du collaborateur en tant que manager',
    'switch-user-role-modal-error-undefining-manager': 'Une erreur s\'est produite lors du retrait du type manager du collaborateur',

    // ProfileAddChannel
    'profile-add-channel-title': 'Ajouter une langue à votre profil',

    // ExportSearchUsers
    'export-search-users-sheet-name': 'Collaborateurs recherchés',
    'export-search-users-id-col': 'Id',
    'export-search-users-fullname-col': 'Nom complet',
    'export-search-users-job-position-col': 'Poste',
    'export-search-users-answers-count-col': 'Nbre de réponses',
    'export-search-users-solutions-count-col': 'Nbre de solutions trouvées',
    'export-search-users-search-text-col': 'Texte de recherche',
    'export-search-users-skills-col': 'Skills',
    'export-search-users-search-skills-col': 'Filtres de Skills',
    'export-search-users-common-skills-col': 'Skills communs',
    'export-search-users-relevance-ratio-col': 'Ratio de correspondance',

    // TrainingReferences
    'training-references-title': 'Mes formations',
    'training-references-archive-confirm': 'Etes-vous sûr(e) de vouloir archiver cette formation ?',
    'training-references-add-btn': 'Ajouter',
    'training-references-state-col': 'Statut',
    'training-references-id-col': 'Id',
    'training-references-name-col': 'Nom',
    'training-references-level-col': 'Niveau',
    'training-references-goal-col': 'Objectif',
    'training-references-code-col': 'Code',
    'training-references-estimated-duration-col': 'Durée estimée',
    'training-references-domain-col': 'Thème',
    'training-references-skills-col': 'Skills',
    'training-references-training-count-col': 'Nbre de sessions',
    'training-references-participants-count-col': 'Nbre de stagiaires',
    'training-references-actions-col': 'Actions',
    'training-references-action-show-trainings': 'Voir les sessions de formation',
    'training-references-action-no-trainings': 'Aucune session de formation',
    'training-references-not-defined': 'Aucune formation disponible',
    'training-references-update': 'Modifier la formation',
    'training-references-archive': 'Archiver la formation',
    'training-references-see-reporting': 'Voir le reporting',
    'training-references-add-session': 'Ajouter une session',
    'training-references-duplicate': 'Dupliquer la formation',
    'training-references-confirm-duplicate': 'Etes-vous sûr(e) de vouloir dupliquer cette formation ?',
    'training-references-recommendation-rate-col': 'Taux de recommandation',
    'training-references-success-rate-col': 'Taux de réussite',
    'training-references-acquired-skills-col': 'Nombre de Skills acquis',
    'training-references-training-reference-filter': 'Filtrer par formation',
    'training-references-training-center-filter': 'Filter par organisme de formation',

    // AddTrainingReferenceModal
    'add-training-reference-modal-title': 'Ajouter une formation',
    'add-training-reference-modal-update-title': 'Modifier la formation {br}"{name}"',
    'add-training-reference-modal-name': 'Nom',
    'add-training-reference-modal-level': 'Niveau',
    'add-training-reference-modal-code': 'Code',
    'add-training-reference-modal-content': 'Contenu de la formation',
    'add-training-reference-modal-goal': 'Objectifs',
    'add-training-reference-modal-audience': 'Public concerné',
    'add-training-reference-modal-estimated-duration': 'Durée estimée',
    'add-training-reference-modal-prerequisite': 'Prérequis',
    'add-training-reference-modal-domain': 'Thème',
    'add-training-reference-modal-skills': 'Skills',
    'add-training-reference-modal-add-skill': 'Ajouter',
    'add-training-reference-modal-locale': 'Langue de la formation',
    'add-training-reference-modal-add-training': 'Ajouter une session',
    'add-training-reference-modal-update': 'Modifier',
    'add-training-reference-modal-create': 'Ajouter',
    'add-training-reference-modal-missing-field': 'Le champs "{field}" est requis. Merci de le compléter pour pouvoir créer la formation 😉',
    'add-training-reference-modal-lang-placeholder': 'Langue de la formation',
    'add-training-reference-modal-level-placeholder': 'Niveau de la formation',
    'add-training-reference-modal-added': 'La formation a bien été créée',
    'add-training-reference-modal-updated': 'La formation a bien été modifiée',
    'add-training-reference-close-confirm': 'Etes-vous sûr(e) de vouloir quitter sans enregistrer ?',

    // TrainingReferenceReporting
    'training-ref-kpis-title': 'Chiffres clés',
    'training-ref-kpis-updated-at': 'Mis à jour le {date} à {hours}h{minutes}',
    'training-ref-reporting-title': 'Reporting de la formation',
    'training-ref-reporting-title-name': 'Reporting "{name}"',
    'training-ref-reporting-no-data-title': 'Reporting : en cours de calcul',
    'training-ref-reporting-respondents': '{respondentsCount} répondants',
    'training-ref-reporting-participants-count-kpi-title': 'Stagiaires inscrits à la formation',
    'training-ref-reporting-participants-count-help-title': 'Somme des stagiaires inscrits à cette formation',
    'training-ref-reporting-participants-count-help-message': ', ayant un compte validé ou non',
    'training-ref-reporting-success-rate-pre-kpi-title': 'Taux de réussite (avant la formation)',
    'training-ref-reporting-success-rate-pre-help-title': '% de bonnes réponses au questionnaire de positionnement',
    'training-ref-reporting-success-rate-pre-help-message': 'Somme des bonnes réponses données au questionnaire de positionnement / Somme des réponses données) * 100',
    'training-ref-reporting-success-rate-kpi-title': 'Taux de réussite (après la formation)',
    'training-ref-reporting-success-rate-help-title': '% de bonnes réponses au questionnaire de validation',
    'training-ref-reporting-success-rate-help-message': 'Somme des bonnes réponses données au Questionnaire de validation / Somme des réponses données au Questionnaire de validation * 100',
    'training-ref-reporting-commitment-rate-kpi-title': 'Taux d\'engagement des stagiaires',
    'training-ref-reporting-commitment-rate-help-title': '% des stagiaires ayant répondu au minimum à un questionnaire',
    'training-ref-reporting-commitment-rate-help-message': 'Somme des stagiaires ayant répondu à au moins 1 questionnaire, avant formation ( positionnement), de satisfaction ou après formation ( validation) / Somme des stagiaires inscrits à la session de formation * 100',
    'training-ref-reporting-satisfaction-rate-kpi-title': 'Taux de satisfaction de la formation',
    'training-ref-reporting-satisfaction-rate-help-title': '% des avis positifs des stagiaires suite à la formation',
    'training-ref-reporting-satisfaction-rate-help-message': 'Somme des avis positifs (3 et/ou 4 étoiles données à la 1ère question du questionnaire de satisfaction)/ Somme des avis  du questionnaire de satisfaction reçus * 100',
    'training-ref-reporting-attendance-rate-kpi-title': 'Taux de présence',
    'training-ref-reporting-attendance-rate-help-title': '% des stagiaires présents lors des sessions',
    'training-ref-reporting-attendance-rate-help-message': 'Somme des stagiaires encore inscrits à la session, 1 jour après la fin de la formation / Somme des stagiaires inscrits à la session 1 jour avant son début * 100',
    'training-ref-reporting-acquired-skills-participant-kpi-title': 'Nombre moyen de Skills acquis',
    'training-ref-reporting-acquired-skills-participant-help-title': 'Permet de savoir combien de SKills les stagiaires ont acquis grâce à la formation',
    'training-ref-reporting-acquired-skills-participant-help-message': 'Somme des Skills acquis / Somme des stagiaires  ayant répondu à 100% au Questionnaire de validation',
    'training-ref-reporting-sessions-count-kpi-title': 'Somme des sessions liées à cette formation',
    'training-ref-reporting-sessions-count-help-title': 'Somme des sessions de formation programmées',
    'training-ref-reporting-sessions-count-help-message': 'Somme de toutes les sessions de cette formation programmées au cours de l\'année séléctionnée ',
    'training-ref-reporting-sessions-tab-title': 'infos concernant les sessions ({count})',
    'training-ref-reporting-sessions-tab-id-col': 'Id',
    'training-ref-reporting-sessions-tab-session-col': 'Session',
    'training-ref-reporting-sessions-tab-periode-col': 'Période',
    'training-ref-reporting-sessions-tab-support-ends-at-col': 'Fin de la validation',
    'training-ref-reporting-sessions-tab-whasqs-count-col': 'Nbre de whasqs',
    'training-ref-reporting-sessions-tab-participants-count-col': 'Nbre de stagiaires',
    'training-ref-reporting-sessions-tab-participation-rate-col': 'Taux de participation',
    'training-ref-reporting-sessions-tab-respondents-col': 'Nbre de répondants',
    'training-ref-reporting-sessions-tab-success-rate-col': 'Taux de réussite',
    'training-ref-reporting-sessions-tab-action-col': 'Actions',

    // AddUserModal
    'add-user-modal-title': 'Ajouter un collaborateur',
    'add-user-modal-fullname': 'Nom complet (*)',
    'add-user-modal-email': 'Email (*)',
    'add-user-modal-phone': 'Téléphone (*)',
    'add-user-modal-job-position': 'Poste (*)',
    'add-user-modal-add-btn': 'Ajouter',
    'add-user-modal-missing-field': 'Le champs "{field}" est requis. Merci de le compléter pour pouvoir ajouter le collaborateur 😉',
    'add-user-modal-close-confirm': 'Etes-vous sûr de vouloir quitter sans enregistrer ?',

    // MyKPIs
    'my-kpis-title': 'Mes Chiffres clés',
    'my-kpis-no-data-title': 'Mes Chiffres clés : Pas de donnée disponible',
    'my-kpis-trainer': 'Formateur',
    'my-kpis-drh': 'Admin',
    'my-kpis-contact-of': 'Contact organisme de formation',
    'my-kpis-participants-count-kpi-title': 'Stagiaires',
    'my-kpis-participants-count-help-title': 'Somme de tous les stagiaires inscrits à des sessions de formations',
    'my-kpis-participants-count-help-message': 'ayant validés ou non leurs comptes au cours de l\'année sélectionnée',
    'my-kpis-participants-count-trainer-help-message': 'Somme de tous les stagiaires inscrits à vos sessions de formation au cours de l\'année sélectionnée, ayant validés ou non leurs comptes',
    'my-kpis-participants-count-contact-of-help-message': 'Somme de tous les stagiaires inscrits à vos sessions de formation au cours de l\'année sélectionnée, ayant validés ou non leurs comptes',
    'my-kpis-success-rate-kpi-title': 'Taux de réussite général (après formation)',
    'my-kpis-success-rate-help-title': '% de bonnes réponses aux questionnaires de validation',
    'my-kpis-success-rate-help-message': 'Somme des bonnes réponses données à tous les questionnaires de validation / Somme de toutes les réponses données à tous les questionnaires de validation * 100, au cours de l\'année séléctionnée',
    'my-kpis-success-rate-trainer-help-message': 'Somme des bonnes réponses données à tous vos questionnaires de validation / Somme de toutes les réponses données à tous vos questionnaires de validation * 100, au cours de l\'année séléctionnée, pour vos sessions de formation ',
    'my-kpis-success-rate-contact-of-help-message': 'Somme des bonnes réponses données à tous les questionnaires de validation / Somme de toutes les réponses données à tous les questionnaires de validation * 100, au cours de  l\'année séléctionnée, pour votre OF',
    'my-kpis-commitment-rate-kpi-title': 'Taux d\'engagement des stagiaires',
    'my-kpis-commitment-rate-help-title': '% des stagiaires ayant répondu au minimum à un questionnaire',
    'my-kpis-commitment-rate-help-message': 'Somme de tous les stagiaires ayant répondu à au moins 1 questionnaire, avant formation ( positionnement), de satisfaction ou après formation ( validation) / Somme de tous les stagiaires inscrits à une session de formation * 100, au cours de  l\'année séléctionnée',
    'my-kpis-commitment-rate-contact-of-help-message': 'Somme de tous les stagiaires ayant répondu à au moins 1 questionnaire, avant formation ( positionnement), de satisfaction ou après formation ( validation) / Somme de tous les stagiaires inscrits à une session de formation * 100, au cours de  l\'année séléctionnée, pour votre OF',
    'my-kpis-commitment-rate-trainer-help-message': 'Somme de tous les stagiaires ayant répondu à au moins 1 questionnaire, avant formation ( positionnement), de satisfaction ou après formation ( validation) / Somme de tous les stagiaires inscrits à une session de formation * 100, au cours de  l\'année séléctionnée, pour vos sessions de formation',
    'my-kpis-satisfaction-rate-kpi-title': 'Taux de satisfaction',
    'my-kpis-satisfaction-rate-help-title': '% des avis positifs des stagiaires suite aux sessions de formation',
    'my-kpis-satisfaction-rate-help-message': 'Somme de tous les avis positifs (3 et/ou 4 étoiles données à la 1ère question du questionnaire de satisfaction)/ Somme des avis  du questionnaire de satisfaction reçus * 100, au cours de  l\'année séléctionnée',
    'my-kpis-satisfaction-rate-trainer-help-message': 'Somme de tous les avis positifs (3 et/ou 4 étoiles données à la 1ère question du questionnaire de satisfaction)/ Somme des avis  du questionnaire de satisfaction reçus * 100, au cours de  l\'année séléctionnée, pour vos sessions de formation',
    'my-kpis-satisfaction-rate-contact-of-help-message': 'Somme de tous les avis positifs (3 et/ou 4 étoiles données à la 1ère question du questionnaire de satisfaction)/ Somme des avis  du questionnaire de satisfaction reçus * 100, au cours de  l\'année séléctionnée,pour votre OF ',
    'my-kpis-attendance-rate-kpi-title': 'Taux de présence',
    'my-kpis-attendance-rate-help-title': '% des stagiaires présents lors des formations',
    'my-kpis-attendance-rate-help-message': 'Somme de tous les stagiaires encore inscrits à la session, 1 jour après la fin de la formation / Somme de tous les stagiaires inscrits à la session 1 jour avant son début * 100, , au cours de l\'année séléctionnée',
    'my-kpis-attendance-rate-trainer-help-message': 'Somme de tous les stagiaires encore inscrits à la session, 1 jour après la fin de la formation / Somme de tous les stagiaires inscrits à la session 1 jour avant son début * 100, au cours de l\'année séléctionnée, pour vos sessions de formation ',
    'my-kpis-attendance-rate-contact-of-help-message': 'Somme de tous les stagiaires encore inscrits à la session, 1 jour après la fin de la formation / Somme de tous les stagiaires inscrits à la session 1 jour avant son début * 100,au cours de l\'année séléctionnée, pour votre OF ',
    'my-kpis-acquired-skills-per-participant-kpi-title': 'Nombre moyen de Skills acquis',
    'my-kpis-acquired-skills-per-participant-help-title': 'Permet de savoir combien de SKills les stagiaires ont acquis grâce à la formation',
    'my-kpis-acquired-skills-per-participant-help-message': 'Somme des Skills acquis / Somme de tous les stagiaires  ayant répondu à 100% au Questionnaire de validation',
    'my-kpis-acquired-skills-per-participant-trainer-help-message': 'Somme des Skills acquis / Somme de tous les stagiaires  ayant répondu à 100% au Questionnaire de validation au cours de l\'année séléctionnée, pour vos sessions',
    'my-kpis-acquired-skills-per-participant-contact-of-help-message': 'Somme des Skills acquis / Somme de tous stagiaires  ayant répondu à 100% au Questionnaire de validation au cours de l\'année séléctionnée, pour votre OF',
    'my-kpis-acquired-skills-kpi-title': 'Nombre total de Skills acquis',
    'my-kpis-acquired-skills-help-title': 'Somme de tous les Skills acquis en formation par les stagiaires au cours de l\'année séléctionnée',
    'my-kpis-acquired-skills-help-message': 'Somme de tous les Skills acquis en formation par les stagiaires au cours de l\'année séléctionnée)',
    'my-kpis-acquired-skills-trainer-help-message': 'Somme de tous les Skills acquis en formation par les stagiaires au cours de l\'année séléctionnée pour vos sessions de formation',
    'my-kpis-acquired-skills-contact-of-help-message': 'Somme de tous les Skills acquis en formation par les stagiaires au cours de l\'année séléctionnée pour votre OF',
    'my-kpis-trainings-count-kpi-title': 'Nombre de formations programmées',
    'my-kpis-trainings-count-help-title': 'indique le nombre de formations programmées dans la base',
    'my-kpis-trainings-count-help-message': 'Somme de  toutes les formations programmées au cours de l\'année séléctionnée ',
    'my-kpis-trainings-count-trainer-help-message': 'Somme de  toutes les formations  programmées dont vous êtes le formateur  au cours de l\'année séléctionnée',
    'my-kpis-trainings-count-contact-of-help-message': 'Somme de  toutes les formations  programmées que vous animez au cours de l\'année séléctionnée',
    'my-kpis-training-centers-count-kpi-title': 'Nombre d\'OF',
    'my-kpis-training-centers-count-help-title': 'Nombre d\'organismes de formation créés dans la base Whasq',
    'my-kpis-training-centers-count-help-message': 'Somme de tous les organismes de formation ayant accès à Whasq',
    'my-kpis-training-sessions-count-kpi-title': 'Nombre de sessions de formation',
    'my-kpis-training-sessions-count-help-title': 'Somme des sessions de formations programmées',
    'my-kpis-training-sessions-count-help-message': 'Somme de toutes les sessions programmées dans la base Whasq au cours de l\'année séléctionnée',
    'my-kpis-training-sessions-count-trainer-help-message': 'Somme de toutes les sessions programmées dans la base Whasq dont vous êtes le formateur au cours de l\'année séléctionnée',
    'my-kpis-training-sessions-count-contact-of-help-message': 'Nombre total des sessions programmées que vous animez dans la base Whasq au cours de l\'année séléctionnée ',
    'my-kpis-recommendation-rate-kpi-title': 'Taux de recommandation',
    'my-kpis-recommendation-rate-help-title': '% des stagiaires recommandant les formations',
    'my-kpis-recommendation-rate-help-message': 'Somme de tous les stagiaires ayant recommandé une formation / somme de tous les stagiaires répondants total) * 100 au cours de l\'année séléctionnée',
    'my-kpis-recommendation-rate-trainer-help-message': 'Somme de tous les stagiaires ayant recommandé vos formations / somme de tous les stagiaires répondants total) * 100 au cours de l\'année séléctionnée',
    'my-kpis-recommendation-rate-contact-of-help-message': 'Somme de tous les stagiaires ayant recommandé une de vos formations / somme de tous les stagiaires répondants total) * 100 au cours de l\'année séléctionnée',
    'my-kpis-roi-kpi-title': 'ROI',
    'my-kpis-roi-help-title': 'Retour sur investissement',
    'my-kpis-roi-help-message': 'Budget d\'une session de formation * nombre de particpants / nombre de partipants répondants ayant réussi le formation',

    // LevelChoiceModal
    'level-choice-modal-title': 'Choisissez le(s) niveau(x)',
    'level-choice-modal-subtitle': 'Choisissez le ou les niveau(x) pour le Skill "{skillName}"',
    'level-choice-modal-expert': 'Expert',
    'level-choice-modal-confirmed': 'Confirmé(e)',
    'level-choice-modal-intermediate': 'Intermédiaire',
    'level-choice-modal-begginer': 'Débutant(e)',
    'level-choice-modal-declared': 'Déclaré',
    'level-choice-modal-error-title': 'Erreur',
    'level-choice-modal-error-message': 'Vous devez sélectionner au minimum un niveau pour lancer la recherche.',

    // Interns
    'interns-title': 'Mes stagiaires',

    // TrainingCenterReporting
    'training-center-kpis-title': 'Chiffres clés',
    'training-center-kpis-updated-at': 'Mis à jour le {date} à {hours}h{minutes}',
    'training-center-reporting-no-data-title': 'En attente de donnée pour cet organisme de formation.',
    'training-center-reporting-participants-count-kpi-title': 'Stagiaires inscrits aux formations',
    'training-center-reporting-participants-count-help-title': 'Somme des stagiaires inscrits aux formations ',
    'training-center-reporting-participants-count-help-message': 'Somme des stagiaires ayant été inscrit à une session de formation, ayant validés ou non leurs comptes',
    'training-center-reporting-success-rate-pre-kpi-title': 'Taux de réussite général (avant formation)',
    'training-center-reporting-success-rate-pre-help-title': '% de bonnes réponses aux questionnaires de positionnement',
    'training-center-reporting-success-rate-pre-help-message': 'Somme des bonnes réponses données à tous les questionnaires de positionnement / Somme de toutes les réponses données à tous les questionnaires de positionnement * 100, au cours de l\'année séléctionnée',
    'training-center-reporting-success-rate-kpi-title': 'Taux de réussite général (après formation)',
    'training-center-reporting-success-rate-help-title': '% de bonnes réponses aux questionnaires de validation',
    'training-center-reporting-success-rate-help-message': 'Somme des bonnes réponses données à tous les questionnaires de validation / Somme de toutes les réponses données à tous les questionnaires de validation * 100, au cours de l\'année séléctionnée',
    'training-center-reporting-commitment-rate-kpi-title': 'Taux d\'engagement des stagiaires',
    'training-center-reporting-commitment-rate-help-title': '% des stagiaires ayant répondu au minimum à un questionnaire',
    'training-center-reporting-commitment-rate-help-message': 'Somme de tous les stagiaires ayant répondu à au moins 1 questionnaire, avant formation ( positionnement), de satisfaction ou après formation ( validation) / Somme de tous les stagiaires inscrits à une session de formation * 100, au cours de  l\'année séléctionnée',
    'training-center-reporting-satisfaction-rate-kpi-title': 'Taux de satisfaction',
    'training-center-reporting-satisfaction-rate-help-title': '% des avis positifs des stagiaires suite aux sessions de formation',
    'training-center-reporting-satisfaction-rate-help-message': 'Somme de tous les avis positifs (3 et/ou 4 étoiles données à la 1ère question du questionnaire de satisfaction)/ Somme des avis  du questionnaire de satisfaction reçus * 100, au cours de  l\'année séléctionnée',
    'training-center-reporting-attendance-rate-kpi-title': 'Taux de présence',
    'training-center-reporting-attendance-rate-help-title': '% des stagiaires présents lors des formations',
    'training-center-reporting-attendance-rate-help-message': 'Somme de tous les stagiaires encore inscrits à la session, 1 jour après la fin de la formation / Somme de tous les stagiaires inscrits à la session 1 jour avant son début * 100, , au cours de l\'année séléctionnée',
    'training-center-reporting-acquired-skills-kpi-title': 'Nombre moyen de Skills acquis',
    'training-center-reporting-acquired-skills-help-title': 'Permet de savoir combien de SKills les stagiaires ont acquis grâce à la formation',
    'training-center-reporting-acquired-skills-help-message': 'Somme des Skills acquis / Somme de tous les stagiaires  ayant répondu à 100% au Questionnaire de validation',
    'training-center-reporting-sessions-count-kpi-title': 'Nombre de sessions de formation',
    'training-center-reporting-sessions-count-help-title': 'Somme des sessions de formations programmées',
    'training-center-reporting-sessions-count-help-message': 'Somme de toutes les sessions programmées dans la base Whasq au cours de l\'année séléctionnée',

    // CardUser
    'card-user-collaborative-actions': 'Actions collaboratives',

    // Podium
    'ranking-title': 'Podium',
    'ranking-ytd-label': 'Depuis le début {year}',
    'ranking-all-label': 'Depuis le début de l\'activité',
    'ranking-no-podium-for-selected-month': 'Il n\'y a pas de podium pour la période sélectionnée',

    // LanguageDropdown
    'language-dropdown-placeholder': 'Choisir la langue',
    'language-dropdown-empty-list': 'Il n\'y a aucune langue disponible',

    // AddSkillCatLangModal
    'add-skill-cat-lang-modal-title': 'Ajouter une langue',
    'add-skill-cat-lang-modal-explanation': 'L\'ajout d\'une langue permet à vos collaborateurs de naviguer dans une autre langue',
    'add-skill-cat-lang-modal-unavailable': 'Menu déjà disponible en',
    'add-skill-cat-lang-modal-add': 'Ajouter',
    'add-skill-cat-lang-modal-remember': 'N\'oubliez pas de traduire votre référenciel de Skills après l\'avoir dupliqué',
    'add-skill-cat-lang-modal-error-adding': 'Vous devez sélectionner une langue pour pouvoir l\'ajouter',

    // AddCategoryModal
    'add-category-modal-add-cat-title': 'Ajouter un thème',
    'add-category-modal-update-cat-title': 'Modifier un thème',
    'add-category-modal-add-skill-title': 'Ajouter un savoir',
    'add-category-modal-update-skill-title': 'Modifier un savoir',
    'add-category-modal-existing-cats': 'Thèmes existants',
    'add-category-modal-existing-skills': 'Skills existants',
    'add-category-modal-add': 'Ajouter',
    'add-category-modal-update': 'Modifier',
    'add-category-modal-no-filtered-cats': 'Aucun thème ne correspond à votre recherche.',
    'add-category-modal-no-filtered-skills': 'Aucun Skills ne correspond à votre recherche.',
    'add-category-modal-cat-ever-exist': 'Vous ne pouvez pas choisir ce mot car un thème porte déjà ce nom.',
    'add-category-modal-skill-ever-exist': 'Vous ne pouvez pas choisir ce mot car un Skill porte déjà ce nom.',

    // AddManagerModal
    'add-manager-modal-title': 'Ajouter un manager',
    'add-manager-modal-update-title': 'Modifier d\'un manager',
    'add-manager-modal-select': 'Veuillez choisir un manager dans la liste déroulante :',
    'add-manager-modal-select-placeholder': 'Cliquer pour sélectionner un manager',
    'add-manager-modal-validate': 'Valider',

    // AddWhasqSkillModal
    'add-whasq-skill-title': 'Vous pouvez ajouter jusqu\'à 3 Skills maximum',

    // UploadProfileImageModal
    'choose-profile-image': 'Choisissez votre image de profil',
}

export default messages
