const messages = {
    
    // Login
    'Email': 'E-mail',
    'Login': 'Iniciar sessão',
    'Password': 'Palavra-passe',
    'Provided by your administrator': 'Fornecida pelo seu administrador',
    'Remember me': 'Lembrar-se de mim',
    'no-identification-info': 'Se não tiver os seus dados da conta para iniciar a sesaão, entre em contato com o seu administrador',
    'bad-credentials': 'Os seus dados estão incorretos. Por favor, tente novamente',
    'not-enough-rights': 'Não têm as autorizações necessárias para iniciar a sessão.',
    'user-not-found': 'Esse utilizador não foi encontrado.',

    // General
    'more-info': 'Mais informações',
    'from': 'De',
    'to': 'A',
    'real-time': 'em tempo real',
    'update': 'Modificar',
    'delete': 'Apagar',
    'previous': 'Anterior',
    'next': 'Seguinte',
    'send': 'Enviar',
    'export-all': 'Exportar tudo',
    'yes': 'Sim',
    'no': 'Não',
    'open': 'Em curso',
    'fullname': 'Nome completo',
    'job-position': 'Emprego',
    'assistance': 'Precisa de ajuda? Contate jessie@whasq.com  (De segunda à sexta-feira, das 9:00 ao 12:00 e das 14:00 às 18:00) ',
    'download-attachment': 'Fazer download do anexo',

    // Menu
    'activity': 'Atividade',
    'actives-users': 'Utilizadores Ativos',
    'registered-users': 'Utilizadores inscritos',
    'whasqs-answers': 'Whasqs & Respostas',
    'skills': 'Competências',
    'time-savings': 'Ganho de tempo',
    'whasqers': 'Whasqers',
    'podium': 'Pódio',
    'search': 'Procura',
    'manage': 'Gestão',
    'skills-categories': 'Competências & Categorias',
    'whasqs': 'Whasqs',
    'whasqs-reports': 'Whasqs denúnciados',
    'answers-reports': 'Respostas denúnciadas',
    'users': 'Utilizadores',
    'admin': 'Administração',
    'targets': 'Objetivos & Jogos',
    'notifications': 'Notificações',

    // Activity
    'eve-computed-kpi': 'indicador calculado em  D-1',
    'no-data-for-selected-period': 'Nenhuma procura corresponde ao período selecionado',
    'no-data-available': 'Nenhum dado disponível',

    // ActivityActiveUsers
    'actives-title': 'Utilizadores ativos',
    'actives-kpi-title': 'Ativos',
    'actives-kpi-help-title': 'Ativos',
    'actives-kpi-help-message': 'Este indicador representa o número de utilizadores que iniciaram uma sessão pelo menos uma vez no mês de "{month}".',
    'actives-dda-kpi-title': 'Ativos DIA',
    'actives-dda-kpi-help-title': 'Ativos "DIA" (Desde o Início da Atividade)',
    'actives-dda-kpi-help-message': 'Este indicador representa o número de utilizadores que iniciaram uma sessão desde o início da atividade',
    'actives-target-kpi-title': 'Ativos - Objetivos',
    'actives-target-kpi-help-title': 'Ativos - Objetivos',
    'actives-target-kpi-help-message': 'Este indicador representa a porporção entre o número de utilizadores que iniciaram uma sessão pelo menos uma vez no mês de "{month}"  em relação aos objetivos defenidos.',
    'actives-evolution-title': 'Evolução dos ativos',
    'actives-evolution-help-title': 'Evolução dos ativos',
    'actives-evolution-help-message': 'Este indicador representa o número de utilizadores ativos.',
    'actives-dda-evolution-title': 'Evolução dos ativos DIA',
    'actives-dda-evolution-help-title': 'Evolução dos ativos DIA',
    'actives-dda-evolution-help-message': 'Este indicador representa o número de utilizadores ativos acumulados desde a criação da store.',
    'actives-notregistered-evolution-title': 'Evolução dos ativos - inscrição',
    'actives-notregistered-evolution-help-title': 'Evolução dos ativos - inscrição',
    'actives-notregistered-evolution-help-message': 'Este indicador representa o número de utilizadores ativos subtraindo os utilizadores registrados .',

    // ActivityRegisteredUsers
    'registered-title': 'utilizadores registrados - {month}',
    'registered-kpi-title': 'Inscritos',
    'registered-kpi-help-title': 'Inscritos',
    'registered-kpi-help-message': 'Este indicador representa o número de utilizadores que se inscreveram no mês de "{month}".',
    'registered-inactives-kpi-title': 'Percentagem de inscritos inativos',
    'registered-inactives-kpi-help-title': 'Percentagem de inscritos inativos',
    'registered-inactives-kpi-help-message': 'Este indicador representa a porporção entre o número de utilizadores que se inscreveram no mês de "{month}" sem estarem relacionados com o número total de utilizadores registrados no mês.',
    'registered-inactives-evolution-title': 'Evolução das inscrições',
    'registered-inactives-evolution-help-title': 'Evolução das inscrições',
    'registered-inactives-evolution-help-message': 'Este indicador representa o número de utilizadores inscritos.',

    // ActivityWhasqs
    'whasqs-answers-title': 'Whasqs & Respostas - {month}',
    'whasqs-answers-kpi-title': 'Número de Whasqs et respostas',
    'whasqs-answers-kpi-help-title': 'Número de Whasqs et respostas',
    'whasqs-answers-kpi-help-message': 'Este indicador representa o número de whasqs publicados mais o número de respostas publicadas no mês de "{month}".',
    'whasqs-by-whasqer-kpi-title': 'Número de Whasqs/ autor de whasqs',
    'whasqs-by-whasqer-kpi-help-title': 'Número de Whasqs/ autor de whasqs',
    'whasqs-by-whasqer-kpi-help-message': 'Este indicador representa o número de whasqs publicados no mês de "{month}" por autor de whasqs.',
    'answers-kpi-title': 'Número de respostas',
    'answers-kpi-help-title': 'Número de respostas',
    'answers-kpi-help-message': 'Este indicador representa o número de respostas publicadas no mês de "{month}".',
    'answers-by-creator-kpi-title': 'Número de respostas / autor de respostas',
    'answers-by-creator-kpi-help-title': 'Número de respostas / autor de respostas',
    'answers-by-creator-kpi-help-message': 'Este indicador representa o número de respostas publicadas no mês de "{month}" por autor de resposta.',
    'whasqs-with-contribution-kpi-title': 'Percentagem de Whasqs com interação',
    'whasqs-with-contribution-kpi-help-title': 'Percentagem de Whasqs com interação',
    'whasqs-with-contribution-kpi-help-message': 'Este indicador representa a participação dos Whasqs que receberam respostas no mês de "{month}".',
    'whasqs-with-contribution-dda-kpi-title': 'Percentagem de Whasqs com interação DIA',
    'whasqs-with-contribution-dda-kpi-help-title': 'Percentagem de Whasqs com interação DIA',
    'whasqs-with-contribution-dda-kpi-help-message': 'Este indicador representa o número de whasqs que recebream respostas.',
    'whasqs-resolved-part-kpi-title': 'Percentagem de Whasqs resolvidos',
    'whasqs-resolved-part-kpi-help-title': 'Percentagem de Whasqs resolvidos',
    'whasqs-resolved-part-kpi-help-message': 'Este indicador representa o número de whasqs que foram resolvidos no mês de"{month}".',
    'whasqs-resolved-part-dda-kpi-title': 'Percentagem de Whasqs resolvidos DIA',
    'whasqs-resolved-part-dda-kpi-help-title': 'Percentagem de Whasqs resolvidos DIA',
    'whasqs-resolved-part-dda-kpi-help-message': 'Este indicador representa o número de whasqs que foram resolvidos.',
    'whasqs-evolution-title': 'Evolução do número de whasqs',
    'whasqs-evolution-help-title': 'Evolução do número de whasqs',
    'whasqs-evolution-help-message': 'Este indicador representa o número de whasqs acumulados.',
    'answers-evolution-title': 'Evolução do número de respostas',
    'answers-evolution-help-title': 'Evolução do número de respostas',
    'answers-evolution-help-message': 'Este indicador representa o número de respostas acumuladas.',

    // ActivitySkills
    'skills-title': 'Competências',
    'skills-dda-kpi-title': 'Número total de competências identificadas DIA',
    'skills-dda-kpi-help-title': 'Número total de competências identificadas DIA',
    'skills-dda-kpi-help-message': 'Este indicador representa o número de competências que foram identificadas pelos whaqers desde o início da actividade.',
    'skills-part-kpi-title': 'Parte das competências ùnicas identificadas ',
    'skills-part-kpi-help-title': 'Parte das competências únicas identificadas',
    'skills-part-kpi-help-message': 'Este indicador representa a porporção entre o número de competências únicas identificadas pelos whasqers desde a criação da atividade em relação ao número de comptências existentes.',
    'skills-evolution-title': 'Evolução do número de competências identificadas nos whasqs',
    'skills-evolution-help-title': 'Evolução do número de competências identificadas nos whasqs',
    'skills-evolution-help-message': 'Este indicador representa o número de competências identificadas nos whasqs .',
    'most-used-cats-whasqs-kpi-title': 'Top 5 das principais categorias mais utilizadas no whasqs',
    'most-used-cats-whasqs-kpi-help-title': 'Top 5 das principais categorias mais utilizadas no whasqs',
    'most-used-cats-whasqs-kpi-help-message-1': 'Nesta tabela pode aceder às 5 categorias que contêm o maior número de competências  usadas nos whasqs.',
    'most-used-cats-whasqs-kpi-help-message-2': 'As bolas coloridas representam o número de comptências usadas nos whasqs de categorias correspondentes.',
    'most-used-skills-whasqs-kpi-title': 'Top 5 das principais competências mais utilizadas nos whasqs',
    'most-used-skills-whasqs-kpi-help-title': 'Top 5 das principais competências mais utilizadas nos whasqs',
    'most-used-skills-whasqs-kpi-help-message-1': 'Nesta tabela pode aceder às 5 competências mais usadas nos whasqs.',
    'most-used-skills-whasqs-kpi-help-message-2': 'As bolas coloridas representam o número utilizações dos whasqs de cada competência.',
    'most-used-whasqers-kpi-title': 'Top 5 das competências mais sugeridas pelos whasqers',
    'most-used-whasqers-kpi-help-title': 'Top 5 das competências mais sugeridas pelos whasqers',
    'most-used-whasqers-kpi-help-message-1': 'Nesta tabela pode aceder às 5 competências mais sugeridas nos whasqs.',
    'most-used-whasqers-kpi-help-message-2': 'As bolas coloridas representam o número de sugestões dadas pelos whasqers por cada competência.',
    'less-used-whasqers-kpi-title': 'Top 5 das competências menos sugeridas pelos whasqers',
    'less-used-whasqers-kpi-help-title': 'Top 5 das competências menos sugeridas pelos whasqers',
    'less-used-whasqers-kpi-help-message-1': 'Nesta tabela pode aceder às 5 competências menos sugeridas nos whasqs.',
    'less-used-whasqers-kpi-help-message-2': 'As bolas coloridas representam o número de sugestões dadas pelos whasqers por cada competência.',

    // TimeSavings
    'time-savings-title': 'Ganho de tempo - {month}',
    'minutes-earned-kpi-title': 'Minutos ganhos no mês',
    'minutes-earned-kpi-help-title': 'Minutos ganhos no mês',
    'minutes-earned-kpi-help-message': 'Este indicador representa o número de minutos ganhos no mês de "{month}".',
    'minutes-earned-dda-kpi-title': 'Minutos ganhos DIA',
    'minutes-earned-dda-kpi-help-title': 'Minutos ganhos DIA',
    'minutes-earned-dda-kpi-help-message': 'Este indicador representa o número de minutos ganhos desde o início da atividade.',
    'minutes-earned-month-kpi-title': 'Minutos ganhos no mês',

    // Podium
    'podium-title': 'Pódio',
    'whasqers-of-month': 'Whasqers do mês de',
    'no-podium-for-selected-month': 'Nenhum pódio está disponível para o mês selecionado',

    // Card-user
    'answers-label': 'RESPOSTAS',
    'solutions-label': 'SOLUÇÕES',
    'see-profile': 'Ver perfil',

    // Search
    'search-title': 'Pesquisa',
    'search-by-name-placeholder': 'Pesquisa por nome...',
    'no-result-select-criteria': 'Nenhum resultado. Preencha pelo menos um critério.',

    // CategoriesSearchBlock
    'dynamic-search-title': 'Pesquisa dinâmica',

    // SkillsCategories
    'skills-categories-title': 'Competências & Categorias',
    'update-cat-for-lang': 'Modificação da categoria pelo idioma {lang}',
    'update-skill-for-cat-and-lang-fr': 'Modificação da competência pela categoria "{cat}" e o idioma PT',
    'add-cat-for-lang-fr': 'Adicionar a categoria para o idioma PT',
    'add-skill-for-cat-and-lang-fr': 'Adicionar a competência  para a categoria"{cat}" e o idioma PT',
    'delete-cat-confirm-message': 'Tem certeza de que deseja excluir esta categoria? ?',
    'delete-skill-confirm-message': 'Tem certeza de que deseja excluir esta competência ?',
    'choose-lang': 'Escolher um idioma',
    'add-lang': 'Adicionar um idioma',
    'add-cat': 'Adicionar uma categoria',

    // InfoMessage
    'cat-deleted': 'A categoria "{cat}" foi apagada.',
    'error-deleting-cat': 'Ocorreu um erro no momento de excluir a categoria"{cat}".',
    'skill-deleted': 'A competência "{skill}" foi apagada.',
    'error-deleting-skill': 'Ocorreu um erro no momento de apagar a competência"{skill}".',

    // SkillCategoriesModal
    'already-existing-cat': 'Categoria(s) que já existe(m)',
    'already-existing-skill': 'Competência (s) que já existe(m)',
    'no-existing-cat': 'Nenhuma categoria existente',
    'no-existing-skill': 'Nenhuma competência existente',

    // CreateLanguageModal
    'add-new-lang': 'Adicionar um novo idioma',
    'already-implemented-langs': 'Idiomas já adicionados',

    // WhasqsList
    'whasqs-title': 'Whasqs',
    'block-whasq-confirm-message': 'Tem a certeza de que deseja bloquear este whasq ?',
    'unblock-whasq-confirm-message': 'Tem a certeza de que deseja desbloquear este whasq ?',
    'ban-user-confirm-message': 'Tem a certeza de que deseja banir este utilizador  ?',
    'unban-user-confirm-message': 'Tem a certeza de que deseja remover a proibição para este utilizador ?',
    'remove-whasq-confirm-message': 'Tem a certeza de que deseja apagar este whasq ?',
    'add-whasq': 'Adicionar um Whasq',
    'whasqs-list': 'Lista de Whasqs',
    'whasqs-column-id': 'ID',
    'whasqs-column-creation': 'Criação',
    'whasqs-column-update': 'Atualização',
    'whasqs-column-title': 'Título',
    'whasqs-column-status': 'Estatuto',
    'whasqs-column-urgent': 'Urgente',
    'whasqs-column-answers': 'Respostas',
    'whasqs-column-read': 'Lidas',
    'whasqs-column-creator': 'Autor',
    'whasqs-column-skills': 'Competências',
    'whasqs-column-actions': 'Ações',
    'whasq-resolved-by': 'Resolvido pelo(a)',
    'whasq-resolved-at': 'no',
    'whasqs-action-save-updates': 'Guardar as modificações',
    'whasqs-action-edit-whasq': 'Editar o whasq',
    'whasqs-action-unblock-whasq': 'Desbloquear o whasq',
    'whasqs-action-block-whasq': 'Bloquear o whasq',
    'whasqs-action-see-whasq-channel': 'Veja o fio de atualidade do whasq',
    'whasqs-action-unban-user': 'Remover a proibição para este utilizador',
    'whasqs-action-ban-user': 'Banir utilizador ',
    'whasqs-action-remove-whasq': 'Apagar o whasq',
    'whasqs-notify-around': 'Notificar ao meu redor',
    'whasqs-language': 'Idioma',

    // WhasqChannelModal
    'whasq-channel-title': 'Conversa do whasq "{whasq-title}"',
    'usefull-answer': 'útil(s)',
    'champion-answer': 'CAMPEÃO(Ã)',
    'whasq-channel-edit-whasq-title': 'Título',
    'whasq-channel-edit-whasq-message': 'Mensagem',
    'whasq-channel-edit-answer-message': 'Mensagem',
    'whasq-channel-block-answer-confirm': 'Tem a certeza de que deseja bloquear esta resposta ?',
    'whasq-channel-unblock-answer-confirm': 'Tem a certeza de que deseja desbloquear esta resposta ?',
    'whasq-channel-delete-answer-confirm': 'Tem a certeza de que deseja apagar esta resposta ?',

    // AddWhasqModal
    'add-whasq-title': 'Adicionar um novo whasq',
    'add-whasq-item-title': 'Título',
    'add-whasq-item-message': 'Mensagem',
    'add-whasq-item-exchange': 'Em troca',
    'add-whasq-item-optionnal': 'Opcional',
    'add-whasq-item-channel': 'Canal',
    'add-whasq-item-first-skill': 'Primeira competência',
    'add-whasq-item-second-skill': 'Segunda competência',
    'add-whasq-item-third-skill': 'Terceira competência',
    'add-whasq-item-notify-around': 'Notificar ao meu redor ?',
    'add-whasq-item-urgent': 'Urgente ?',
    'add-whasq-item-send-everyone': 'Enviar a toda a gente ?',
    'add-whasq-skill-required': 'É obrigatório especificar pelo menos uma competência.',
    'add-whasq-title-required': 'É obrigatório especificar pelo menos o título.',
    'add-whasq-message-required': 'É obrigatório especificar a mensagem.',

    // WhasqsReports
    'whasqs-reports-title': 'Whasqs denúnciados',
    'whasqs-reports-unblock-whasq-confirm-message': 'Tem a certeza de que deseja desbloquear este whasq ?',
    'whasqs-reports-unban-user-confirm-message': 'Tem a certeza de que deseja remover a proibição para este utilizador ?',
    'whasqs-reports-ban-user-confirm-message': 'Tem a certeza de que deseja banir este utilizador ?',
    'whasqs-reports-remove-whasq-confirm-message': 'Tem a certeza de que deseja apagar este whasq ?',
    'whasqs-reports-list': 'Lista de Whasqs denúnciados',
    'whasqs-reports-column-id': 'ID',
    'whasqs-reports-column-creation-date': 'Data de criação',
    'whasqs-reports-column-last-update': 'Ùltima atualização',
    'whasqs-reports-column-title': 'Título',
    'whasqs-reports-column-status': 'Estatuto',
    'whasqs-reports-column-urgent': 'Urgente',
    'whasqs-reports-column-answers': 'Respostas',
    'whasqs-reports-column-creator': 'Autor',
    'whasqs-reports-column-reported-by': 'Denúnciado por',
    'whasqs-reports-column-actions': 'Ação',
    'whasq-reports-resolved-by': 'Resolvido pelo(a)',
    'whasq-reports-resolved-at': 'no',
    'whasqs-reports-action-save-updates': 'Guardar as modificações',
    'whasqs-reports-action-edit-whasq': 'Editar o whasq',
    'whasqs-reports-action-unblock-whasq': 'Desbloquear o whasq',
    'whasqs-reports-action-see-whasq-channel': 'Veja o fio de atualidade do whasq',
    'whasqs-reports-action-unban-user': 'Remover a proibição para este utilizador',
    'whasqs-reports-action-ban-user': 'Banir utilizador',
    'whasqs-reports-action-remove-whasq': 'Apagar do whasq',

    // AnswersReports
    'answers-reports-title': 'Lista de respostas denúnciadas',
    'answers-reports-unblock-answer-confirm-message': 'Tem a certeza de que deseja desbloquear esta resposta ?',
    'answers-reports-unban-user-confirm-message': 'Tem a certeza de que deseja remover a proibição para este utilizador ?',
    'answers-reports-ban-user-confirm-message': 'Tem a certeza de que deseja banir este utilizador ?',
    'answers-reports-remove-answer-confirm-message': 'Tem a certeza de que deseja apagar esta resposta ?',
    'answers-reports-list': 'Lista de respostas denúnciadas',
    'answers-reports-column-id': 'ID',
    'answers-reports-column-creation': 'Data de criação',
    'answers-reports-column-last-update': 'Ùltima atualização',
    'answers-reports-column-message': 'Mensagem',
    'answers-reports-column-usefull-count': 'n° uteis',
    'answers-reports-column-champion': 'Campeão ?',
    'answers-reports-column-creator': 'Autor',
    'answers-reports-column-reported-by': 'Denúnciado por',
    'answers-reports-column-actions': 'Ações',
    'answers-reports-action-save-updates': 'Guardar as modificações',
    'answers-reports-action-edit-answer': 'Editar a resposta',
    'answers-reports-action-unblock-answer': 'Desbloquear a resposta',
    'answers-reports-action-see-whasq-channel': 'Veja o fio de atualidade do whasq',
    'answers-reports-action-unban-user': 'Remover a proibição para este utilizador',
    'answers-reports-action-ban-user': 'Banir utilizador',
    'answers-reports-action-remove-answer': 'Apagar reposta',

    // Users
    'users-title': 'Utilizadores',
    'users-ban-confirm-message': 'Tem a certeza de que deseja banir este utilizador ?',
    'users-unban-confirm-message': 'Tem a certeza de que deseja remover a proibição para este utilizador ?',
    'users-archive-confirm-message': 'Tem a certeza de que deseja arquivar este utilizador ?',
    'users-import-csv': 'Importar CSV',
    'users-list': 'Lista de Whasqers',
    'users-column-id': 'ID',
    'users-column-register-date': 'Data de inscrição',
    'users-column-last-connection': 'Última conexão',
    'users-column-avatar': 'Avatar',
    'users-column-fullname': 'Nome completo',
    'users-column-title': 'Título',
    'users-column-email': 'E-mail',
    'users-column-actions': 'Ações',
    'users-action-see-profile': 'Ver perfil',
    'users-action-unban-user': 'Remover a proibição para este utilizador',
    'users-action-ban-user': 'Banir utilizador',
    'users-action-archive-user': 'Arquivar este utilizador',
    'users-import-starting': 'A importação de utilizadores começou bem',
    'users-action-consider-user-admin': 'Considere este utilizador como administrador',
    'users-action-stop-consider-user-admin': 'Não considere mais este utilizador como administrador',
    'users-confirm-consider-admin': 'Tem a certeza de que deseja considerar este utilizador como administrador ?',
    'users-confirm-dont-consider-admin': 'Tem a certeza de que já não deseja considerar este utilizador como administrador ?',
    'users-action-consider-user-admin-success': 'Este utilizador agora é administrador.',
    'users-action-stop-consider-user-admin-success': 'O utilizador id {userId} já não é administrador .',
    'users-column-geolocated': 'Geolocalizado',
    'error-file-format': 'O formato do ficheiro não está correto',

    // ImportUsersModal
    'users-import-title': 'Importação de utilizadores',
    'import-users-file-limit': 'Apenas os  ficheiros CSV inferiores a 1 MB são aceitos',
    'import-users-error': 'Ocorreu um erro durante a importação. Por favor, tente novamente.',
    'import-users-btn': 'Importar de utilizadores',
    'import-users-expected-format': 'Formato pré-definido',
    'import-users-fullname': 'Nome completo',
    'import-users-email': 'E-mail',
    'import-users-job-position': 'Cargo',
    'import-users-phone': 'Telefone',
    'import-users-download-exemple': 'Fazer o download do exemplo',
    'import-users-instructions-part-1': 'Complete o exemplo e salvaguarde-o no formato csv (separado por ponto e vírgula)',
    'import-users-instructions-part-2': '(4 colunas APENAS na ordem DEFINIDA)',

    // Targets
    'targets-title': 'Objectivos & Jogos',
    'targets-update-message': 'O objectivo "{target}" foi atualizado',
    'targets-geoloc-perimeter-updated': 'O perímetro da geolocalização foi atualizado',
    'targets-points-atribution-updated': 'A atribuição de pontos foi atualizada',
    'targets-target': 'Objectivos',
    'targets-trimester': '3 meses',
    'targets-bimester': '6 meses',
    'targets-year': '12 meses',
    'targets-active-users': 'utilizadores ativos',
    'targets-geoloc-perimeter': 'O perímetro de geolocalização',
    'targets-perimeter': 'Perímetro',
    'targets-gamification': 'Jogos',
    'targets-approved-answer': 'Resposta aprovada',
    'targets-usefull-answer': 'Resposta útil',
    'targets-recommended-skill': 'Competência sugerida',
    'targets-points': 'pontos',
    
    // Header
    'header-profile': 'Perfil',
    'header-logout': 'Fechar sessão',
    'french': 'Francês',
    'english': 'Iglês',
    'spanish': 'Espanhol',
    'italian': 'Italiano',
    'russian': 'Russo',

    // Sidebar
    'sidebar-navigation': 'Navigação',

    // Profile
    'profile': 'Perfil',
    'profile-title': 'Perfil do utilizador',
    'profile-ban-user-confirm-message': 'Tem a certeza de que deseja bloquar este utilizador ?',
    'profile-edit-skill-confirm-message': 'Atenção, a mudança na competênia será feita de forma global para todos os utilizadores. Tem a  certeza de que deseja continuar?',
    'profile-remove-skill-confirm-message': ' Tem a certeza de que deseja apagar a competência deste utilizador ?',
    'profile-archive-user-confirm-message': 'Tem a certeza de que deseja  arquivar este utilizador ?',
    'whasqer-profile': 'Perfil do Whasqer',
    'profile-account-creation': 'Criação da conta',
    'profile-last-connection': 'Última conexão',
    'profile-last-update': 'Última atualização',
    'profile-whasqs-column': 'WHASQS',
    'profile-answers-column': 'RESPOSTAS',
    'profile-solutions-column': 'SOLUÇÕES',
    'profile-block-button': 'Bloquear',
    'profile-archive-button': 'Arquivar',
    'profile-user-archived': 'Este utilizador foi arquivado',
    'profile-skills-subtitle': 'Competências',
    'profile-no-listed-skill': 'Nenhuma competência identificada',

    // AddUserSkillModal
    'add-skill-for-user': 'Adicionar a competência para {fullname}',
    'already-existing-skills-for-user': 'Competências(s) já existe(m) para o utilizador',
    'available-skills-for-user': 'Competências(s) disponível(eis) para o utilizador',

    // SuperAdminStores
    'store-selection': 'Escolha da store',
    'store-choice-validation': 'Confirmar a escolha da store',

    // StoreLogoUpload
    'choose-company-logo': 'Escolha o logotipo da sua empresa',
    'drop-file-here-or-click': 'Deslize o seu ficheiro aqui ou clique para selecionar o ficheiro a ser importado.',
    'company-logo-size-limit': 'Apenas os ficheiros de imagem inferiores a 1 MB são aceitos.',
    'company-logo-square-required': 'O formato da imagem deve ser quadrado.',
    'error-importing-company-logo': 'Ocorreu um erro durante a importação. Por favor, tente novamente.',
    'import-company-logo': 'Importar o logotipo',

    // Notifications
    'notifications-title': 'Notificações',
    'notifications-list': 'Lista de notificações',
    'notifications-column-id': 'Id',
    'notifications-column-type': 'Tipo',
    'notifications-column-data': 'Dados',
    'notifications-column-owner': 'Proprietário',
    'notifications-column-shared': 'Partilha ?',
    'notifications-column-creation': 'Data de criação',
    'notifications-column-message': 'Mensagem',
    'notifications-no-data': ' Atualmente, não há notificações',
}

export default messages
